// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/chuyen-gia-crypto/backend/internal/db/ent/account"
	"github.com/chuyen-gia-crypto/backend/internal/db/ent/accountsnapshot"
	"github.com/chuyen-gia-crypto/backend/internal/db/ent/predicate"
)

// AccountSnapshotUpdate is the builder for updating AccountSnapshot entities.
type AccountSnapshotUpdate struct {
	config
	hooks    []Hook
	mutation *AccountSnapshotMutation
}

// Where appends a list predicates to the AccountSnapshotUpdate builder.
func (_u *AccountSnapshotUpdate) Where(ps ...predicate.AccountSnapshot) *AccountSnapshotUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *AccountSnapshotUpdate) SetAccountID(v int) *AccountSnapshotUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountSnapshotUpdate) SetNillableAccountID(v *int) *AccountSnapshotUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetBalance sets the "balance" field.
func (_u *AccountSnapshotUpdate) SetBalance(v float64) *AccountSnapshotUpdate {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *AccountSnapshotUpdate) SetNillableBalance(v *float64) *AccountSnapshotUpdate {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *AccountSnapshotUpdate) AddBalance(v float64) *AccountSnapshotUpdate {
	_u.mutation.AddBalance(v)
	return _u
}

// SetEquity sets the "equity" field.
func (_u *AccountSnapshotUpdate) SetEquity(v float64) *AccountSnapshotUpdate {
	_u.mutation.ResetEquity()
	_u.mutation.SetEquity(v)
	return _u
}

// SetNillableEquity sets the "equity" field if the given value is not nil.
func (_u *AccountSnapshotUpdate) SetNillableEquity(v *float64) *AccountSnapshotUpdate {
	if v != nil {
		_u.SetEquity(*v)
	}
	return _u
}

// AddEquity adds value to the "equity" field.
func (_u *AccountSnapshotUpdate) AddEquity(v float64) *AccountSnapshotUpdate {
	_u.mutation.AddEquity(v)
	return _u
}

// SetUnrealizedPnl sets the "unrealized_pnl" field.
func (_u *AccountSnapshotUpdate) SetUnrealizedPnl(v float64) *AccountSnapshotUpdate {
	_u.mutation.ResetUnrealizedPnl()
	_u.mutation.SetUnrealizedPnl(v)
	return _u
}

// SetNillableUnrealizedPnl sets the "unrealized_pnl" field if the given value is not nil.
func (_u *AccountSnapshotUpdate) SetNillableUnrealizedPnl(v *float64) *AccountSnapshotUpdate {
	if v != nil {
		_u.SetUnrealizedPnl(*v)
	}
	return _u
}

// AddUnrealizedPnl adds value to the "unrealized_pnl" field.
func (_u *AccountSnapshotUpdate) AddUnrealizedPnl(v float64) *AccountSnapshotUpdate {
	_u.mutation.AddUnrealizedPnl(v)
	return _u
}

// SetOpenPositions sets the "open_positions" field.
func (_u *AccountSnapshotUpdate) SetOpenPositions(v int) *AccountSnapshotUpdate {
	_u.mutation.ResetOpenPositions()
	_u.mutation.SetOpenPositions(v)
	return _u
}

// SetNillableOpenPositions sets the "open_positions" field if the given value is not nil.
func (_u *AccountSnapshotUpdate) SetNillableOpenPositions(v *int) *AccountSnapshotUpdate {
	if v != nil {
		_u.SetOpenPositions(*v)
	}
	return _u
}

// AddOpenPositions adds value to the "open_positions" field.
func (_u *AccountSnapshotUpdate) AddOpenPositions(v int) *AccountSnapshotUpdate {
	_u.mutation.AddOpenPositions(v)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *AccountSnapshotUpdate) SetAccount(v *Account) *AccountSnapshotUpdate {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the AccountSnapshotMutation object of the builder.
func (_u *AccountSnapshotUpdate) Mutation() *AccountSnapshotMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *AccountSnapshotUpdate) ClearAccount() *AccountSnapshotUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountSnapshotUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountSnapshotUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountSnapshotUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountSnapshotUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountSnapshotUpdate) check() error {
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountSnapshot.account"`)
	}
	return nil
}

func (_u *AccountSnapshotUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountsnapshot.Table, accountsnapshot.Columns, sqlgraph.NewFieldSpec(accountsnapshot.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(accountsnapshot.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(accountsnapshot.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Equity(); ok {
		_spec.SetField(accountsnapshot.FieldEquity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEquity(); ok {
		_spec.AddField(accountsnapshot.FieldEquity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UnrealizedPnl(); ok {
		_spec.SetField(accountsnapshot.FieldUnrealizedPnl, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUnrealizedPnl(); ok {
		_spec.AddField(accountsnapshot.FieldUnrealizedPnl, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OpenPositions(); ok {
		_spec.SetField(accountsnapshot.FieldOpenPositions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOpenPositions(); ok {
		_spec.AddField(accountsnapshot.FieldOpenPositions, field.TypeInt, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountsnapshot.AccountTable,
			Columns: []string{accountsnapshot.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountsnapshot.AccountTable,
			Columns: []string{accountsnapshot.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountsnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountSnapshotUpdateOne is the builder for updating a single AccountSnapshot entity.
type AccountSnapshotUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountSnapshotMutation
}

// SetAccountID sets the "account_id" field.
func (_u *AccountSnapshotUpdateOne) SetAccountID(v int) *AccountSnapshotUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountSnapshotUpdateOne) SetNillableAccountID(v *int) *AccountSnapshotUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetBalance sets the "balance" field.
func (_u *AccountSnapshotUpdateOne) SetBalance(v float64) *AccountSnapshotUpdateOne {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *AccountSnapshotUpdateOne) SetNillableBalance(v *float64) *AccountSnapshotUpdateOne {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *AccountSnapshotUpdateOne) AddBalance(v float64) *AccountSnapshotUpdateOne {
	_u.mutation.AddBalance(v)
	return _u
}

// SetEquity sets the "equity" field.
func (_u *AccountSnapshotUpdateOne) SetEquity(v float64) *AccountSnapshotUpdateOne {
	_u.mutation.ResetEquity()
	_u.mutation.SetEquity(v)
	return _u
}

// SetNillableEquity sets the "equity" field if the given value is not nil.
func (_u *AccountSnapshotUpdateOne) SetNillableEquity(v *float64) *AccountSnapshotUpdateOne {
	if v != nil {
		_u.SetEquity(*v)
	}
	return _u
}

// AddEquity adds value to the "equity" field.
func (_u *AccountSnapshotUpdateOne) AddEquity(v float64) *AccountSnapshotUpdateOne {
	_u.mutation.AddEquity(v)
	return _u
}

// SetUnrealizedPnl sets the "unrealized_pnl" field.
func (_u *AccountSnapshotUpdateOne) SetUnrealizedPnl(v float64) *AccountSnapshotUpdateOne {
	_u.mutation.ResetUnrealizedPnl()
	_u.mutation.SetUnrealizedPnl(v)
	return _u
}

// SetNillableUnrealizedPnl sets the "unrealized_pnl" field if the given value is not nil.
func (_u *AccountSnapshotUpdateOne) SetNillableUnrealizedPnl(v *float64) *AccountSnapshotUpdateOne {
	if v != nil {
		_u.SetUnrealizedPnl(*v)
	}
	return _u
}

// AddUnrealizedPnl adds value to the "unrealized_pnl" field.
func (_u *AccountSnapshotUpdateOne) AddUnrealizedPnl(v float64) *AccountSnapshotUpdateOne {
	_u.mutation.AddUnrealizedPnl(v)
	return _u
}

// SetOpenPositions sets the "open_positions" field.
func (_u *AccountSnapshotUpdateOne) SetOpenPositions(v int) *AccountSnapshotUpdateOne {
	_u.mutation.ResetOpenPositions()
	_u.mutation.SetOpenPositions(v)
	return _u
}

// SetNillableOpenPositions sets the "open_positions" field if the given value is not nil.
func (_u *AccountSnapshotUpdateOne) SetNillableOpenPositions(v *int) *AccountSnapshotUpdateOne {
	if v != nil {
		_u.SetOpenPositions(*v)
	}
	return _u
}

// AddOpenPositions adds value to the "open_positions" field.
func (_u *AccountSnapshotUpdateOne) AddOpenPositions(v int) *AccountSnapshotUpdateOne {
	_u.mutation.AddOpenPositions(v)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *AccountSnapshotUpdateOne) SetAccount(v *Account) *AccountSnapshotUpdateOne {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the AccountSnapshotMutation object of the builder.
func (_u *AccountSnapshotUpdateOne) Mutation() *AccountSnapshotMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *AccountSnapshotUpdateOne) ClearAccount() *AccountSnapshotUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// Where appends a list predicates to the AccountSnapshotUpdate builder.
func (_u *AccountSnapshotUpdateOne) Where(ps ...predicate.AccountSnapshot) *AccountSnapshotUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountSnapshotUpdateOne) Select(field string, fields ...string) *AccountSnapshotUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccountSnapshot entity.
func (_u *AccountSnapshotUpdateOne) Save(ctx context.Context) (*AccountSnapshot, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountSnapshotUpdateOne) SaveX(ctx context.Context) *AccountSnapshot {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountSnapshotUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountSnapshotUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountSnapshotUpdateOne) check() error {
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountSnapshot.account"`)
	}
	return nil
}

func (_u *AccountSnapshotUpdateOne) sqlSave(ctx context.Context) (_node *AccountSnapshot, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountsnapshot.Table, accountsnapshot.Columns, sqlgraph.NewFieldSpec(accountsnapshot.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccountSnapshot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accountsnapshot.FieldID)
		for _, f := range fields {
			if !accountsnapshot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accountsnapshot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(accountsnapshot.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(accountsnapshot.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Equity(); ok {
		_spec.SetField(accountsnapshot.FieldEquity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEquity(); ok {
		_spec.AddField(accountsnapshot.FieldEquity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UnrealizedPnl(); ok {
		_spec.SetField(accountsnapshot.FieldUnrealizedPnl, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUnrealizedPnl(); ok {
		_spec.AddField(accountsnapshot.FieldUnrealizedPnl, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OpenPositions(); ok {
		_spec.SetField(accountsnapshot.FieldOpenPositions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOpenPositions(); ok {
		_spec.AddField(accountsnapshot.FieldOpenPositions, field.TypeInt, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountsnapshot.AccountTable,
			Columns: []string{accountsnapshot.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountsnapshot.AccountTable,
			Columns: []string{accountsnapshot.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AccountSnapshot{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountsnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
