// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/chuyen-gia-crypto/backend/internal/db/ent/account"
	"github.com/chuyen-gia-crypto/backend/internal/db/ent/accountsnapshot"
)

// AccountSnapshot is the model entity for the AccountSnapshot schema.
type AccountSnapshot struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int `json:"account_id,omitempty"`
	// Balance holds the value of the "balance" field.
	Balance float64 `json:"balance,omitempty"`
	// Equity holds the value of the "equity" field.
	Equity float64 `json:"equity,omitempty"`
	// UnrealizedPnl holds the value of the "unrealized_pnl" field.
	UnrealizedPnl float64 `json:"unrealized_pnl,omitempty"`
	// OpenPositions holds the value of the "open_positions" field.
	OpenPositions int `json:"open_positions,omitempty"`
	// Timestamp holds the value of the "timestamp" field.
	Timestamp time.Time `json:"timestamp,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AccountSnapshotQuery when eager-loading is set.
	Edges        AccountSnapshotEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AccountSnapshotEdges holds the relations/edges for other nodes in the graph.
type AccountSnapshotEdges struct {
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccountSnapshotEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccountSnapshot) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accountsnapshot.FieldBalance, accountsnapshot.FieldEquity, accountsnapshot.FieldUnrealizedPnl:
			values[i] = new(sql.NullFloat64)
		case accountsnapshot.FieldID, accountsnapshot.FieldAccountID, accountsnapshot.FieldOpenPositions:
			values[i] = new(sql.NullInt64)
		case accountsnapshot.FieldTimestamp:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccountSnapshot fields.
func (_m *AccountSnapshot) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accountsnapshot.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case accountsnapshot.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = int(value.Int64)
			}
		case accountsnapshot.FieldBalance:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance", values[i])
			} else if value.Valid {
				_m.Balance = value.Float64
			}
		case accountsnapshot.FieldEquity:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field equity", values[i])
			} else if value.Valid {
				_m.Equity = value.Float64
			}
		case accountsnapshot.FieldUnrealizedPnl:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field unrealized_pnl", values[i])
			} else if value.Valid {
				_m.UnrealizedPnl = value.Float64
			}
		case accountsnapshot.FieldOpenPositions:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field open_positions", values[i])
			} else if value.Valid {
				_m.OpenPositions = int(value.Int64)
			}
		case accountsnapshot.FieldTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field timestamp", values[i])
			} else if value.Valid {
				_m.Timestamp = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccountSnapshot.
// This includes values selected through modifiers, order, etc.
func (_m *AccountSnapshot) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccount queries the "account" edge of the AccountSnapshot entity.
func (_m *AccountSnapshot) QueryAccount() *AccountQuery {
	return NewAccountSnapshotClient(_m.config).QueryAccount(_m)
}

// Update returns a builder for updating this AccountSnapshot.
// Note that you need to call AccountSnapshot.Unwrap() before calling this method if this AccountSnapshot
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccountSnapshot) Update() *AccountSnapshotUpdateOne {
	return NewAccountSnapshotClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccountSnapshot entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccountSnapshot) Unwrap() *AccountSnapshot {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccountSnapshot is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccountSnapshot) String() string {
	var builder strings.Builder
	builder.WriteString("AccountSnapshot(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("balance=")
	builder.WriteString(fmt.Sprintf("%v", _m.Balance))
	builder.WriteString(", ")
	builder.WriteString("equity=")
	builder.WriteString(fmt.Sprintf("%v", _m.Equity))
	builder.WriteString(", ")
	builder.WriteString("unrealized_pnl=")
	builder.WriteString(fmt.Sprintf("%v", _m.UnrealizedPnl))
	builder.WriteString(", ")
	builder.WriteString("open_positions=")
	builder.WriteString(fmt.Sprintf("%v", _m.OpenPositions))
	builder.WriteString(", ")
	builder.WriteString("timestamp=")
	builder.WriteString(_m.Timestamp.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AccountSnapshots is a parsable slice of AccountSnapshot.
type AccountSnapshots []*AccountSnapshot
