// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/chuyen-gia-crypto/backend/internal/db/ent/analysishistory"
	"github.com/chuyen-gia-crypto/backend/internal/db/ent/keylevels"
	"github.com/chuyen-gia-crypto/backend/internal/db/ent/prediction"
)

// AnalysisHistoryCreate is the builder for creating a AnalysisHistory entity.
type AnalysisHistoryCreate struct {
	config
	mutation *AnalysisHistoryMutation
	hooks    []Hook
}

// SetCoin sets the "coin" field.
func (_c *AnalysisHistoryCreate) SetCoin(v string) *AnalysisHistoryCreate {
	_c.mutation.SetCoin(v)
	return _c
}

// SetTimestamp sets the "timestamp" field.
func (_c *AnalysisHistoryCreate) SetTimestamp(v time.Time) *AnalysisHistoryCreate {
	_c.mutation.SetTimestamp(v)
	return _c
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_c *AnalysisHistoryCreate) SetNillableTimestamp(v *time.Time) *AnalysisHistoryCreate {
	if v != nil {
		_c.SetTimestamp(*v)
	}
	return _c
}

// SetCurrentPrice sets the "current_price" field.
func (_c *AnalysisHistoryCreate) SetCurrentPrice(v float64) *AnalysisHistoryCreate {
	_c.mutation.SetCurrentPrice(v)
	return _c
}

// SetBias sets the "bias" field.
func (_c *AnalysisHistoryCreate) SetBias(v string) *AnalysisHistoryCreate {
	_c.mutation.SetBias(v)
	return _c
}

// SetAction sets the "action" field.
func (_c *AnalysisHistoryCreate) SetAction(v string) *AnalysisHistoryCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetConfidence sets the "confidence" field.
func (_c *AnalysisHistoryCreate) SetConfidence(v float64) *AnalysisHistoryCreate {
	_c.mutation.SetConfidence(v)
	return _c
}

// SetNarrative sets the "narrative" field.
func (_c *AnalysisHistoryCreate) SetNarrative(v string) *AnalysisHistoryCreate {
	_c.mutation.SetNarrative(v)
	return _c
}

// SetNillableNarrative sets the "narrative" field if the given value is not nil.
func (_c *AnalysisHistoryCreate) SetNillableNarrative(v *string) *AnalysisHistoryCreate {
	if v != nil {
		_c.SetNarrative(*v)
	}
	return _c
}

// SetComparison sets the "comparison" field.
func (_c *AnalysisHistoryCreate) SetComparison(v string) *AnalysisHistoryCreate {
	_c.mutation.SetComparison(v)
	return _c
}

// SetNillableComparison sets the "comparison" field if the given value is not nil.
func (_c *AnalysisHistoryCreate) SetNillableComparison(v *string) *AnalysisHistoryCreate {
	if v != nil {
		_c.SetComparison(*v)
	}
	return _c
}

// SetMarketSentiment sets the "market_sentiment" field.
func (_c *AnalysisHistoryCreate) SetMarketSentiment(v string) *AnalysisHistoryCreate {
	_c.mutation.SetMarketSentiment(v)
	return _c
}

// SetNillableMarketSentiment sets the "market_sentiment" field if the given value is not nil.
func (_c *AnalysisHistoryCreate) SetNillableMarketSentiment(v *string) *AnalysisHistoryCreate {
	if v != nil {
		_c.SetMarketSentiment(*v)
	}
	return _c
}

// SetDisclaimer sets the "disclaimer" field.
func (_c *AnalysisHistoryCreate) SetDisclaimer(v string) *AnalysisHistoryCreate {
	_c.mutation.SetDisclaimer(v)
	return _c
}

// SetNillableDisclaimer sets the "disclaimer" field if the given value is not nil.
func (_c *AnalysisHistoryCreate) SetNillableDisclaimer(v *string) *AnalysisHistoryCreate {
	if v != nil {
		_c.SetDisclaimer(*v)
	}
	return _c
}

// SetMethodID sets the "method_id" field.
func (_c *AnalysisHistoryCreate) SetMethodID(v string) *AnalysisHistoryCreate {
	_c.mutation.SetMethodID(v)
	return _c
}

// SetNillableMethodID sets the "method_id" field if the given value is not nil.
func (_c *AnalysisHistoryCreate) SetNillableMethodID(v *string) *AnalysisHistoryCreate {
	if v != nil {
		_c.SetMethodID(*v)
	}
	return _c
}

// SetBreakoutRetest sets the "breakout_retest" field.
func (_c *AnalysisHistoryCreate) SetBreakoutRetest(v string) *AnalysisHistoryCreate {
	_c.mutation.SetBreakoutRetest(v)
	return _c
}

// SetNillableBreakoutRetest sets the "breakout_retest" field if the given value is not nil.
func (_c *AnalysisHistoryCreate) SetNillableBreakoutRetest(v *string) *AnalysisHistoryCreate {
	if v != nil {
		_c.SetBreakoutRetest(*v)
	}
	return _c
}

// SetPositionDecisions sets the "position_decisions" field.
func (_c *AnalysisHistoryCreate) SetPositionDecisions(v string) *AnalysisHistoryCreate {
	_c.mutation.SetPositionDecisions(v)
	return _c
}

// SetNillablePositionDecisions sets the "position_decisions" field if the given value is not nil.
func (_c *AnalysisHistoryCreate) SetNillablePositionDecisions(v *string) *AnalysisHistoryCreate {
	if v != nil {
		_c.SetPositionDecisions(*v)
	}
	return _c
}

// SetAlternativeScenario sets the "alternative_scenario" field.
func (_c *AnalysisHistoryCreate) SetAlternativeScenario(v string) *AnalysisHistoryCreate {
	_c.mutation.SetAlternativeScenario(v)
	return _c
}

// SetNillableAlternativeScenario sets the "alternative_scenario" field if the given value is not nil.
func (_c *AnalysisHistoryCreate) SetNillableAlternativeScenario(v *string) *AnalysisHistoryCreate {
	if v != nil {
		_c.SetAlternativeScenario(*v)
	}
	return _c
}

// SetSuggestedEntry sets the "suggested_entry" field.
func (_c *AnalysisHistoryCreate) SetSuggestedEntry(v float64) *AnalysisHistoryCreate {
	_c.mutation.SetSuggestedEntry(v)
	return _c
}

// SetNillableSuggestedEntry sets the "suggested_entry" field if the given value is not nil.
func (_c *AnalysisHistoryCreate) SetNillableSuggestedEntry(v *float64) *AnalysisHistoryCreate {
	if v != nil {
		_c.SetSuggestedEntry(*v)
	}
	return _c
}

// SetSuggestedStopLoss sets the "suggested_stop_loss" field.
func (_c *AnalysisHistoryCreate) SetSuggestedStopLoss(v float64) *AnalysisHistoryCreate {
	_c.mutation.SetSuggestedStopLoss(v)
	return _c
}

// SetNillableSuggestedStopLoss sets the "suggested_stop_loss" field if the given value is not nil.
func (_c *AnalysisHistoryCreate) SetNillableSuggestedStopLoss(v *float64) *AnalysisHistoryCreate {
	if v != nil {
		_c.SetSuggestedStopLoss(*v)
	}
	return _c
}

// SetSuggestedTakeProfit sets the "suggested_take_profit" field.
func (_c *AnalysisHistoryCreate) SetSuggestedTakeProfit(v float64) *AnalysisHistoryCreate {
	_c.mutation.SetSuggestedTakeProfit(v)
	return _c
}

// SetNillableSuggestedTakeProfit sets the "suggested_take_profit" field if the given value is not nil.
func (_c *AnalysisHistoryCreate) SetNillableSuggestedTakeProfit(v *float64) *AnalysisHistoryCreate {
	if v != nil {
		_c.SetSuggestedTakeProfit(*v)
	}
	return _c
}

// SetExpectedRr sets the "expected_rr" field.
func (_c *AnalysisHistoryCreate) SetExpectedRr(v float64) *AnalysisHistoryCreate {
	_c.mutation.SetExpectedRr(v)
	return _c
}

// SetNillableExpectedRr sets the "expected_rr" field if the given value is not nil.
func (_c *AnalysisHistoryCreate) SetNillableExpectedRr(v *float64) *AnalysisHistoryCreate {
	if v != nil {
		_c.SetExpectedRr(*v)
	}
	return _c
}

// SetInvalidationLevel sets the "invalidation_level" field.
func (_c *AnalysisHistoryCreate) SetInvalidationLevel(v float64) *AnalysisHistoryCreate {
	_c.mutation.SetInvalidationLevel(v)
	return _c
}

// SetNillableInvalidationLevel sets the "invalidation_level" field if the given value is not nil.
func (_c *AnalysisHistoryCreate) SetNillableInvalidationLevel(v *float64) *AnalysisHistoryCreate {
	if v != nil {
		_c.SetInvalidationLevel(*v)
	}
	return _c
}

// SetRawQuestion sets the "raw_question" field.
func (_c *AnalysisHistoryCreate) SetRawQuestion(v string) *AnalysisHistoryCreate {
	_c.mutation.SetRawQuestion(v)
	return _c
}

// SetNillableRawQuestion sets the "raw_question" field if the given value is not nil.
func (_c *AnalysisHistoryCreate) SetNillableRawQuestion(v *string) *AnalysisHistoryCreate {
	if v != nil {
		_c.SetRawQuestion(*v)
	}
	return _c
}

// SetRawAnswer sets the "raw_answer" field.
func (_c *AnalysisHistoryCreate) SetRawAnswer(v string) *AnalysisHistoryCreate {
	_c.mutation.SetRawAnswer(v)
	return _c
}

// SetNillableRawAnswer sets the "raw_answer" field if the given value is not nil.
func (_c *AnalysisHistoryCreate) SetNillableRawAnswer(v *string) *AnalysisHistoryCreate {
	if v != nil {
		_c.SetRawAnswer(*v)
	}
	return _c
}

// AddPredictionIDs adds the "predictions" edge to the Prediction entity by IDs.
func (_c *AnalysisHistoryCreate) AddPredictionIDs(ids ...int) *AnalysisHistoryCreate {
	_c.mutation.AddPredictionIDs(ids...)
	return _c
}

// AddPredictions adds the "predictions" edges to the Prediction entity.
func (_c *AnalysisHistoryCreate) AddPredictions(v ...*Prediction) *AnalysisHistoryCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPredictionIDs(ids...)
}

// AddKeyLevelIDs adds the "key_levels" edge to the KeyLevels entity by IDs.
func (_c *AnalysisHistoryCreate) AddKeyLevelIDs(ids ...int) *AnalysisHistoryCreate {
	_c.mutation.AddKeyLevelIDs(ids...)
	return _c
}

// AddKeyLevels adds the "key_levels" edges to the KeyLevels entity.
func (_c *AnalysisHistoryCreate) AddKeyLevels(v ...*KeyLevels) *AnalysisHistoryCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddKeyLevelIDs(ids...)
}

// Mutation returns the AnalysisHistoryMutation object of the builder.
func (_c *AnalysisHistoryCreate) Mutation() *AnalysisHistoryMutation {
	return _c.mutation
}

// Save creates the AnalysisHistory in the database.
func (_c *AnalysisHistoryCreate) Save(ctx context.Context) (*AnalysisHistory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AnalysisHistoryCreate) SaveX(ctx context.Context) *AnalysisHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AnalysisHistoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AnalysisHistoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AnalysisHistoryCreate) defaults() {
	if _, ok := _c.mutation.Timestamp(); !ok {
		v := analysishistory.DefaultTimestamp()
		_c.mutation.SetTimestamp(v)
	}
	if _, ok := _c.mutation.MethodID(); !ok {
		v := analysishistory.DefaultMethodID
		_c.mutation.SetMethodID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AnalysisHistoryCreate) check() error {
	if _, ok := _c.mutation.Coin(); !ok {
		return &ValidationError{Name: "coin", err: errors.New(`ent: missing required field "AnalysisHistory.coin"`)}
	}
	if v, ok := _c.mutation.Coin(); ok {
		if err := analysishistory.CoinValidator(v); err != nil {
			return &ValidationError{Name: "coin", err: fmt.Errorf(`ent: validator failed for field "AnalysisHistory.coin": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "AnalysisHistory.timestamp"`)}
	}
	if _, ok := _c.mutation.CurrentPrice(); !ok {
		return &ValidationError{Name: "current_price", err: errors.New(`ent: missing required field "AnalysisHistory.current_price"`)}
	}
	if _, ok := _c.mutation.Bias(); !ok {
		return &ValidationError{Name: "bias", err: errors.New(`ent: missing required field "AnalysisHistory.bias"`)}
	}
	if v, ok := _c.mutation.Bias(); ok {
		if err := analysishistory.BiasValidator(v); err != nil {
			return &ValidationError{Name: "bias", err: fmt.Errorf(`ent: validator failed for field "AnalysisHistory.bias": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "AnalysisHistory.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := analysishistory.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AnalysisHistory.action": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Confidence(); !ok {
		return &ValidationError{Name: "confidence", err: errors.New(`ent: missing required field "AnalysisHistory.confidence"`)}
	}
	if _, ok := _c.mutation.MethodID(); !ok {
		return &ValidationError{Name: "method_id", err: errors.New(`ent: missing required field "AnalysisHistory.method_id"`)}
	}
	if v, ok := _c.mutation.MethodID(); ok {
		if err := analysishistory.MethodIDValidator(v); err != nil {
			return &ValidationError{Name: "method_id", err: fmt.Errorf(`ent: validator failed for field "AnalysisHistory.method_id": %w`, err)}
		}
	}
	return nil
}

func (_c *AnalysisHistoryCreate) sqlSave(ctx context.Context) (*AnalysisHistory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AnalysisHistoryCreate) createSpec() (*AnalysisHistory, *sqlgraph.CreateSpec) {
	var (
		_node = &AnalysisHistory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(analysishistory.Table, sqlgraph.NewFieldSpec(analysishistory.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Coin(); ok {
		_spec.SetField(analysishistory.FieldCoin, field.TypeString, value)
		_node.Coin = value
	}
	if value, ok := _c.mutation.Timestamp(); ok {
		_spec.SetField(analysishistory.FieldTimestamp, field.TypeTime, value)
		_node.Timestamp = value
	}
	if value, ok := _c.mutation.CurrentPrice(); ok {
		_spec.SetField(analysishistory.FieldCurrentPrice, field.TypeFloat64, value)
		_node.CurrentPrice = value
	}
	if value, ok := _c.mutation.Bias(); ok {
		_spec.SetField(analysishistory.FieldBias, field.TypeString, value)
		_node.Bias = value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(analysishistory.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.Confidence(); ok {
		_spec.SetField(analysishistory.FieldConfidence, field.TypeFloat64, value)
		_node.Confidence = value
	}
	if value, ok := _c.mutation.Narrative(); ok {
		_spec.SetField(analysishistory.FieldNarrative, field.TypeString, value)
		_node.Narrative = value
	}
	if value, ok := _c.mutation.Comparison(); ok {
		_spec.SetField(analysishistory.FieldComparison, field.TypeString, value)
		_node.Comparison = value
	}
	if value, ok := _c.mutation.MarketSentiment(); ok {
		_spec.SetField(analysishistory.FieldMarketSentiment, field.TypeString, value)
		_node.MarketSentiment = value
	}
	if value, ok := _c.mutation.Disclaimer(); ok {
		_spec.SetField(analysishistory.FieldDisclaimer, field.TypeString, value)
		_node.Disclaimer = value
	}
	if value, ok := _c.mutation.MethodID(); ok {
		_spec.SetField(analysishistory.FieldMethodID, field.TypeString, value)
		_node.MethodID = value
	}
	if value, ok := _c.mutation.BreakoutRetest(); ok {
		_spec.SetField(analysishistory.FieldBreakoutRetest, field.TypeString, value)
		_node.BreakoutRetest = value
	}
	if value, ok := _c.mutation.PositionDecisions(); ok {
		_spec.SetField(analysishistory.FieldPositionDecisions, field.TypeString, value)
		_node.PositionDecisions = value
	}
	if value, ok := _c.mutation.AlternativeScenario(); ok {
		_spec.SetField(analysishistory.FieldAlternativeScenario, field.TypeString, value)
		_node.AlternativeScenario = value
	}
	if value, ok := _c.mutation.SuggestedEntry(); ok {
		_spec.SetField(analysishistory.FieldSuggestedEntry, field.TypeFloat64, value)
		_node.SuggestedEntry = value
	}
	if value, ok := _c.mutation.SuggestedStopLoss(); ok {
		_spec.SetField(analysishistory.FieldSuggestedStopLoss, field.TypeFloat64, value)
		_node.SuggestedStopLoss = value
	}
	if value, ok := _c.mutation.SuggestedTakeProfit(); ok {
		_spec.SetField(analysishistory.FieldSuggestedTakeProfit, field.TypeFloat64, value)
		_node.SuggestedTakeProfit = value
	}
	if value, ok := _c.mutation.ExpectedRr(); ok {
		_spec.SetField(analysishistory.FieldExpectedRr, field.TypeFloat64, value)
		_node.ExpectedRr = value
	}
	if value, ok := _c.mutation.InvalidationLevel(); ok {
		_spec.SetField(analysishistory.FieldInvalidationLevel, field.TypeFloat64, value)
		_node.InvalidationLevel = value
	}
	if value, ok := _c.mutation.RawQuestion(); ok {
		_spec.SetField(analysishistory.FieldRawQuestion, field.TypeString, value)
		_node.RawQuestion = value
	}
	if value, ok := _c.mutation.RawAnswer(); ok {
		_spec.SetField(analysishistory.FieldRawAnswer, field.TypeString, value)
		_node.RawAnswer = value
	}
	if nodes := _c.mutation.PredictionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   analysishistory.PredictionsTable,
			Columns: []string{analysishistory.PredictionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(prediction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.KeyLevelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   analysishistory.KeyLevelsTable,
			Columns: []string{analysishistory.KeyLevelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(keylevels.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AnalysisHistoryCreateBulk is the builder for creating many AnalysisHistory entities in bulk.
type AnalysisHistoryCreateBulk struct {
	config
	err      error
	builders []*AnalysisHistoryCreate
}

// Save creates the AnalysisHistory entities in the database.
func (_c *AnalysisHistoryCreateBulk) Save(ctx context.Context) ([]*AnalysisHistory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AnalysisHistory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AnalysisHistoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AnalysisHistoryCreateBulk) SaveX(ctx context.Context) []*AnalysisHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AnalysisHistoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AnalysisHistoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
