// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/chuyen-gia-crypto/backend/internal/db/ent/analysishistory"
)

// AnalysisHistory is the model entity for the AnalysisHistory schema.
type AnalysisHistory struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Coin holds the value of the "coin" field.
	Coin string `json:"coin,omitempty"`
	// Timestamp holds the value of the "timestamp" field.
	Timestamp time.Time `json:"timestamp,omitempty"`
	// CurrentPrice holds the value of the "current_price" field.
	CurrentPrice float64 `json:"current_price,omitempty"`
	// Bias holds the value of the "bias" field.
	Bias string `json:"bias,omitempty"`
	// Action holds the value of the "action" field.
	Action string `json:"action,omitempty"`
	// Confidence holds the value of the "confidence" field.
	Confidence float64 `json:"confidence,omitempty"`
	// Narrative holds the value of the "narrative" field.
	Narrative string `json:"narrative,omitempty"`
	// Comparison holds the value of the "comparison" field.
	Comparison string `json:"comparison,omitempty"`
	// MarketSentiment holds the value of the "market_sentiment" field.
	MarketSentiment string `json:"market_sentiment,omitempty"`
	// Disclaimer holds the value of the "disclaimer" field.
	Disclaimer string `json:"disclaimer,omitempty"`
	// MethodID holds the value of the "method_id" field.
	MethodID string `json:"method_id,omitempty"`
	// BreakoutRetest holds the value of the "breakout_retest" field.
	BreakoutRetest string `json:"breakout_retest,omitempty"`
	// PositionDecisions holds the value of the "position_decisions" field.
	PositionDecisions string `json:"position_decisions,omitempty"`
	// AlternativeScenario holds the value of the "alternative_scenario" field.
	AlternativeScenario string `json:"alternative_scenario,omitempty"`
	// SuggestedEntry holds the value of the "suggested_entry" field.
	SuggestedEntry float64 `json:"suggested_entry,omitempty"`
	// SuggestedStopLoss holds the value of the "suggested_stop_loss" field.
	SuggestedStopLoss float64 `json:"suggested_stop_loss,omitempty"`
	// SuggestedTakeProfit holds the value of the "suggested_take_profit" field.
	SuggestedTakeProfit float64 `json:"suggested_take_profit,omitempty"`
	// ExpectedRr holds the value of the "expected_rr" field.
	ExpectedRr float64 `json:"expected_rr,omitempty"`
	// InvalidationLevel holds the value of the "invalidation_level" field.
	InvalidationLevel float64 `json:"invalidation_level,omitempty"`
	// RawQuestion holds the value of the "raw_question" field.
	RawQuestion string `json:"raw_question,omitempty"`
	// RawAnswer holds the value of the "raw_answer" field.
	RawAnswer string `json:"raw_answer,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AnalysisHistoryQuery when eager-loading is set.
	Edges        AnalysisHistoryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AnalysisHistoryEdges holds the relations/edges for other nodes in the graph.
type AnalysisHistoryEdges struct {
	// Predictions holds the value of the predictions edge.
	Predictions []*Prediction `json:"predictions,omitempty"`
	// KeyLevels holds the value of the key_levels edge.
	KeyLevels []*KeyLevels `json:"key_levels,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PredictionsOrErr returns the Predictions value or an error if the edge
// was not loaded in eager-loading.
func (e AnalysisHistoryEdges) PredictionsOrErr() ([]*Prediction, error) {
	if e.loadedTypes[0] {
		return e.Predictions, nil
	}
	return nil, &NotLoadedError{edge: "predictions"}
}

// KeyLevelsOrErr returns the KeyLevels value or an error if the edge
// was not loaded in eager-loading.
func (e AnalysisHistoryEdges) KeyLevelsOrErr() ([]*KeyLevels, error) {
	if e.loadedTypes[1] {
		return e.KeyLevels, nil
	}
	return nil, &NotLoadedError{edge: "key_levels"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AnalysisHistory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case analysishistory.FieldCurrentPrice, analysishistory.FieldConfidence, analysishistory.FieldSuggestedEntry, analysishistory.FieldSuggestedStopLoss, analysishistory.FieldSuggestedTakeProfit, analysishistory.FieldExpectedRr, analysishistory.FieldInvalidationLevel:
			values[i] = new(sql.NullFloat64)
		case analysishistory.FieldID:
			values[i] = new(sql.NullInt64)
		case analysishistory.FieldCoin, analysishistory.FieldBias, analysishistory.FieldAction, analysishistory.FieldNarrative, analysishistory.FieldComparison, analysishistory.FieldMarketSentiment, analysishistory.FieldDisclaimer, analysishistory.FieldMethodID, analysishistory.FieldBreakoutRetest, analysishistory.FieldPositionDecisions, analysishistory.FieldAlternativeScenario, analysishistory.FieldRawQuestion, analysishistory.FieldRawAnswer:
			values[i] = new(sql.NullString)
		case analysishistory.FieldTimestamp:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AnalysisHistory fields.
func (_m *AnalysisHistory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case analysishistory.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case analysishistory.FieldCoin:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field coin", values[i])
			} else if value.Valid {
				_m.Coin = value.String
			}
		case analysishistory.FieldTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field timestamp", values[i])
			} else if value.Valid {
				_m.Timestamp = value.Time
			}
		case analysishistory.FieldCurrentPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field current_price", values[i])
			} else if value.Valid {
				_m.CurrentPrice = value.Float64
			}
		case analysishistory.FieldBias:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bias", values[i])
			} else if value.Valid {
				_m.Bias = value.String
			}
		case analysishistory.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = value.String
			}
		case analysishistory.FieldConfidence:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field confidence", values[i])
			} else if value.Valid {
				_m.Confidence = value.Float64
			}
		case analysishistory.FieldNarrative:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field narrative", values[i])
			} else if value.Valid {
				_m.Narrative = value.String
			}
		case analysishistory.FieldComparison:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field comparison", values[i])
			} else if value.Valid {
				_m.Comparison = value.String
			}
		case analysishistory.FieldMarketSentiment:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field market_sentiment", values[i])
			} else if value.Valid {
				_m.MarketSentiment = value.String
			}
		case analysishistory.FieldDisclaimer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field disclaimer", values[i])
			} else if value.Valid {
				_m.Disclaimer = value.String
			}
		case analysishistory.FieldMethodID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field method_id", values[i])
			} else if value.Valid {
				_m.MethodID = value.String
			}
		case analysishistory.FieldBreakoutRetest:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field breakout_retest", values[i])
			} else if value.Valid {
				_m.BreakoutRetest = value.String
			}
		case analysishistory.FieldPositionDecisions:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field position_decisions", values[i])
			} else if value.Valid {
				_m.PositionDecisions = value.String
			}
		case analysishistory.FieldAlternativeScenario:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field alternative_scenario", values[i])
			} else if value.Valid {
				_m.AlternativeScenario = value.String
			}
		case analysishistory.FieldSuggestedEntry:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field suggested_entry", values[i])
			} else if value.Valid {
				_m.SuggestedEntry = value.Float64
			}
		case analysishistory.FieldSuggestedStopLoss:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field suggested_stop_loss", values[i])
			} else if value.Valid {
				_m.SuggestedStopLoss = value.Float64
			}
		case analysishistory.FieldSuggestedTakeProfit:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field suggested_take_profit", values[i])
			} else if value.Valid {
				_m.SuggestedTakeProfit = value.Float64
			}
		case analysishistory.FieldExpectedRr:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field expected_rr", values[i])
			} else if value.Valid {
				_m.ExpectedRr = value.Float64
			}
		case analysishistory.FieldInvalidationLevel:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field invalidation_level", values[i])
			} else if value.Valid {
				_m.InvalidationLevel = value.Float64
			}
		case analysishistory.FieldRawQuestion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field raw_question", values[i])
			} else if value.Valid {
				_m.RawQuestion = value.String
			}
		case analysishistory.FieldRawAnswer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field raw_answer", values[i])
			} else if value.Valid {
				_m.RawAnswer = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AnalysisHistory.
// This includes values selected through modifiers, order, etc.
func (_m *AnalysisHistory) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPredictions queries the "predictions" edge of the AnalysisHistory entity.
func (_m *AnalysisHistory) QueryPredictions() *PredictionQuery {
	return NewAnalysisHistoryClient(_m.config).QueryPredictions(_m)
}

// QueryKeyLevels queries the "key_levels" edge of the AnalysisHistory entity.
func (_m *AnalysisHistory) QueryKeyLevels() *KeyLevelsQuery {
	return NewAnalysisHistoryClient(_m.config).QueryKeyLevels(_m)
}

// Update returns a builder for updating this AnalysisHistory.
// Note that you need to call AnalysisHistory.Unwrap() before calling this method if this AnalysisHistory
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AnalysisHistory) Update() *AnalysisHistoryUpdateOne {
	return NewAnalysisHistoryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AnalysisHistory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AnalysisHistory) Unwrap() *AnalysisHistory {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AnalysisHistory is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AnalysisHistory) String() string {
	var builder strings.Builder
	builder.WriteString("AnalysisHistory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("coin=")
	builder.WriteString(_m.Coin)
	builder.WriteString(", ")
	builder.WriteString("timestamp=")
	builder.WriteString(_m.Timestamp.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("current_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.CurrentPrice))
	builder.WriteString(", ")
	builder.WriteString("bias=")
	builder.WriteString(_m.Bias)
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(_m.Action)
	builder.WriteString(", ")
	builder.WriteString("confidence=")
	builder.WriteString(fmt.Sprintf("%v", _m.Confidence))
	builder.WriteString(", ")
	builder.WriteString("narrative=")
	builder.WriteString(_m.Narrative)
	builder.WriteString(", ")
	builder.WriteString("comparison=")
	builder.WriteString(_m.Comparison)
	builder.WriteString(", ")
	builder.WriteString("market_sentiment=")
	builder.WriteString(_m.MarketSentiment)
	builder.WriteString(", ")
	builder.WriteString("disclaimer=")
	builder.WriteString(_m.Disclaimer)
	builder.WriteString(", ")
	builder.WriteString("method_id=")
	builder.WriteString(_m.MethodID)
	builder.WriteString(", ")
	builder.WriteString("breakout_retest=")
	builder.WriteString(_m.BreakoutRetest)
	builder.WriteString(", ")
	builder.WriteString("position_decisions=")
	builder.WriteString(_m.PositionDecisions)
	builder.WriteString(", ")
	builder.WriteString("alternative_scenario=")
	builder.WriteString(_m.AlternativeScenario)
	builder.WriteString(", ")
	builder.WriteString("suggested_entry=")
	builder.WriteString(fmt.Sprintf("%v", _m.SuggestedEntry))
	builder.WriteString(", ")
	builder.WriteString("suggested_stop_loss=")
	builder.WriteString(fmt.Sprintf("%v", _m.SuggestedStopLoss))
	builder.WriteString(", ")
	builder.WriteString("suggested_take_profit=")
	builder.WriteString(fmt.Sprintf("%v", _m.SuggestedTakeProfit))
	builder.WriteString(", ")
	builder.WriteString("expected_rr=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExpectedRr))
	builder.WriteString(", ")
	builder.WriteString("invalidation_level=")
	builder.WriteString(fmt.Sprintf("%v", _m.InvalidationLevel))
	builder.WriteString(", ")
	builder.WriteString("raw_question=")
	builder.WriteString(_m.RawQuestion)
	builder.WriteString(", ")
	builder.WriteString("raw_answer=")
	builder.WriteString(_m.RawAnswer)
	builder.WriteByte(')')
	return builder.String()
}

// AnalysisHistories is a parsable slice of AnalysisHistory.
type AnalysisHistories []*AnalysisHistory
