// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/chuyen-gia-crypto/backend/internal/db/ent/latestprice"
)

// LatestPriceCreate is the builder for creating a LatestPrice entity.
type LatestPriceCreate struct {
	config
	mutation *LatestPriceMutation
	hooks    []Hook
}

// SetCoin sets the "coin" field.
func (_c *LatestPriceCreate) SetCoin(v string) *LatestPriceCreate {
	_c.mutation.SetCoin(v)
	return _c
}

// SetPrice sets the "price" field.
func (_c *LatestPriceCreate) SetPrice(v float64) *LatestPriceCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetChange24h sets the "change_24h" field.
func (_c *LatestPriceCreate) SetChange24h(v float64) *LatestPriceCreate {
	_c.mutation.SetChange24h(v)
	return _c
}

// SetNillableChange24h sets the "change_24h" field if the given value is not nil.
func (_c *LatestPriceCreate) SetNillableChange24h(v *float64) *LatestPriceCreate {
	if v != nil {
		_c.SetChange24h(*v)
	}
	return _c
}

// SetChange7d sets the "change_7d" field.
func (_c *LatestPriceCreate) SetChange7d(v float64) *LatestPriceCreate {
	_c.mutation.SetChange7d(v)
	return _c
}

// SetNillableChange7d sets the "change_7d" field if the given value is not nil.
func (_c *LatestPriceCreate) SetNillableChange7d(v *float64) *LatestPriceCreate {
	if v != nil {
		_c.SetChange7d(*v)
	}
	return _c
}

// SetMarketCap sets the "market_cap" field.
func (_c *LatestPriceCreate) SetMarketCap(v float64) *LatestPriceCreate {
	_c.mutation.SetMarketCap(v)
	return _c
}

// SetNillableMarketCap sets the "market_cap" field if the given value is not nil.
func (_c *LatestPriceCreate) SetNillableMarketCap(v *float64) *LatestPriceCreate {
	if v != nil {
		_c.SetMarketCap(*v)
	}
	return _c
}

// SetVolume24h sets the "volume_24h" field.
func (_c *LatestPriceCreate) SetVolume24h(v float64) *LatestPriceCreate {
	_c.mutation.SetVolume24h(v)
	return _c
}

// SetNillableVolume24h sets the "volume_24h" field if the given value is not nil.
func (_c *LatestPriceCreate) SetNillableVolume24h(v *float64) *LatestPriceCreate {
	if v != nil {
		_c.SetVolume24h(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LatestPriceCreate) SetUpdatedAt(v time.Time) *LatestPriceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LatestPriceCreate) SetNillableUpdatedAt(v *time.Time) *LatestPriceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the LatestPriceMutation object of the builder.
func (_c *LatestPriceCreate) Mutation() *LatestPriceMutation {
	return _c.mutation
}

// Save creates the LatestPrice in the database.
func (_c *LatestPriceCreate) Save(ctx context.Context) (*LatestPrice, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LatestPriceCreate) SaveX(ctx context.Context) *LatestPrice {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LatestPriceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LatestPriceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LatestPriceCreate) defaults() {
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := latestprice.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LatestPriceCreate) check() error {
	if _, ok := _c.mutation.Coin(); !ok {
		return &ValidationError{Name: "coin", err: errors.New(`ent: missing required field "LatestPrice.coin"`)}
	}
	if v, ok := _c.mutation.Coin(); ok {
		if err := latestprice.CoinValidator(v); err != nil {
			return &ValidationError{Name: "coin", err: fmt.Errorf(`ent: validator failed for field "LatestPrice.coin": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "LatestPrice.price"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "LatestPrice.updated_at"`)}
	}
	return nil
}

func (_c *LatestPriceCreate) sqlSave(ctx context.Context) (*LatestPrice, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LatestPriceCreate) createSpec() (*LatestPrice, *sqlgraph.CreateSpec) {
	var (
		_node = &LatestPrice{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(latestprice.Table, sqlgraph.NewFieldSpec(latestprice.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Coin(); ok {
		_spec.SetField(latestprice.FieldCoin, field.TypeString, value)
		_node.Coin = value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(latestprice.FieldPrice, field.TypeFloat64, value)
		_node.Price = value
	}
	if value, ok := _c.mutation.Change24h(); ok {
		_spec.SetField(latestprice.FieldChange24h, field.TypeFloat64, value)
		_node.Change24h = value
	}
	if value, ok := _c.mutation.Change7d(); ok {
		_spec.SetField(latestprice.FieldChange7d, field.TypeFloat64, value)
		_node.Change7d = value
	}
	if value, ok := _c.mutation.MarketCap(); ok {
		_spec.SetField(latestprice.FieldMarketCap, field.TypeFloat64, value)
		_node.MarketCap = value
	}
	if value, ok := _c.mutation.Volume24h(); ok {
		_spec.SetField(latestprice.FieldVolume24h, field.TypeFloat64, value)
		_node.Volume24h = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(latestprice.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// LatestPriceCreateBulk is the builder for creating many LatestPrice entities in bulk.
type LatestPriceCreateBulk struct {
	config
	err      error
	builders []*LatestPriceCreate
}

// Save creates the LatestPrice entities in the database.
func (_c *LatestPriceCreateBulk) Save(ctx context.Context) ([]*LatestPrice, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LatestPrice, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LatestPriceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LatestPriceCreateBulk) SaveX(ctx context.Context) []*LatestPrice {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LatestPriceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LatestPriceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
