// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/chuyen-gia-crypto/backend/internal/db/ent/account"
	"github.com/chuyen-gia-crypto/backend/internal/db/ent/pendingorder"
)

// PendingOrder is the model entity for the PendingOrder schema.
type PendingOrder struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// OrderID holds the value of the "order_id" field.
	OrderID string `json:"order_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int `json:"account_id,omitempty"`
	// Symbol holds the value of the "symbol" field.
	Symbol string `json:"symbol,omitempty"`
	// Side holds the value of the "side" field.
	Side string `json:"side,omitempty"`
	// EntryPrice holds the value of the "entry_price" field.
	EntryPrice float64 `json:"entry_price,omitempty"`
	// StopLoss holds the value of the "stop_loss" field.
	StopLoss float64 `json:"stop_loss,omitempty"`
	// TakeProfit holds the value of the "take_profit" field.
	TakeProfit float64 `json:"take_profit,omitempty"`
	// SizeUsd holds the value of the "size_usd" field.
	SizeUsd float64 `json:"size_usd,omitempty"`
	// SizeQty holds the value of the "size_qty" field.
	SizeQty float64 `json:"size_qty,omitempty"`
	// RiskUsd holds the value of the "risk_usd" field.
	RiskUsd float64 `json:"risk_usd,omitempty"`
	// RiskPercent holds the value of the "risk_percent" field.
	RiskPercent float64 `json:"risk_percent,omitempty"`
	// ExpectedRr holds the value of the "expected_rr" field.
	ExpectedRr float64 `json:"expected_rr,omitempty"`
	// LinkedPredictionID holds the value of the "linked_prediction_id" field.
	LinkedPredictionID *int `json:"linked_prediction_id,omitempty"`
	// InvalidationLevel holds the value of the "invalidation_level" field.
	InvalidationLevel *float64 `json:"invalidation_level,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// ExecutedAt holds the value of the "executed_at" field.
	ExecutedAt *time.Time `json:"executed_at,omitempty"`
	// ExecutedPrice holds the value of the "executed_price" field.
	ExecutedPrice *float64 `json:"executed_price,omitempty"`
	// ExecutedSizeQty holds the value of the "executed_size_qty" field.
	ExecutedSizeQty *float64 `json:"executed_size_qty,omitempty"`
	// ExecutedSizeUsd holds the value of the "executed_size_usd" field.
	ExecutedSizeUsd *float64 `json:"executed_size_usd,omitempty"`
	// RealizedPnl holds the value of the "realized_pnl" field.
	RealizedPnl *float64 `json:"realized_pnl,omitempty"`
	// RealizedPnlPercent holds the value of the "realized_pnl_percent" field.
	RealizedPnlPercent *float64 `json:"realized_pnl_percent,omitempty"`
	// CloseReason holds the value of the "close_reason" field.
	CloseReason *string `json:"close_reason,omitempty"`
	// BinanceOrderID holds the value of the "binance_order_id" field.
	BinanceOrderID *string `json:"binance_order_id,omitempty"`
	// MethodID holds the value of the "method_id" field.
	MethodID string `json:"method_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PendingOrderQuery when eager-loading is set.
	Edges        PendingOrderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PendingOrderEdges holds the relations/edges for other nodes in the graph.
type PendingOrderEdges struct {
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PendingOrderEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PendingOrder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pendingorder.FieldEntryPrice, pendingorder.FieldStopLoss, pendingorder.FieldTakeProfit, pendingorder.FieldSizeUsd, pendingorder.FieldSizeQty, pendingorder.FieldRiskUsd, pendingorder.FieldRiskPercent, pendingorder.FieldExpectedRr, pendingorder.FieldInvalidationLevel, pendingorder.FieldExecutedPrice, pendingorder.FieldExecutedSizeQty, pendingorder.FieldExecutedSizeUsd, pendingorder.FieldRealizedPnl, pendingorder.FieldRealizedPnlPercent:
			values[i] = new(sql.NullFloat64)
		case pendingorder.FieldID, pendingorder.FieldAccountID, pendingorder.FieldLinkedPredictionID:
			values[i] = new(sql.NullInt64)
		case pendingorder.FieldOrderID, pendingorder.FieldSymbol, pendingorder.FieldSide, pendingorder.FieldStatus, pendingorder.FieldCloseReason, pendingorder.FieldBinanceOrderID, pendingorder.FieldMethodID:
			values[i] = new(sql.NullString)
		case pendingorder.FieldCreatedAt, pendingorder.FieldExecutedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PendingOrder fields.
func (_m *PendingOrder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pendingorder.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case pendingorder.FieldOrderID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field order_id", values[i])
			} else if value.Valid {
				_m.OrderID = value.String
			}
		case pendingorder.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = int(value.Int64)
			}
		case pendingorder.FieldSymbol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field symbol", values[i])
			} else if value.Valid {
				_m.Symbol = value.String
			}
		case pendingorder.FieldSide:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field side", values[i])
			} else if value.Valid {
				_m.Side = value.String
			}
		case pendingorder.FieldEntryPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field entry_price", values[i])
			} else if value.Valid {
				_m.EntryPrice = value.Float64
			}
		case pendingorder.FieldStopLoss:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field stop_loss", values[i])
			} else if value.Valid {
				_m.StopLoss = value.Float64
			}
		case pendingorder.FieldTakeProfit:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field take_profit", values[i])
			} else if value.Valid {
				_m.TakeProfit = value.Float64
			}
		case pendingorder.FieldSizeUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field size_usd", values[i])
			} else if value.Valid {
				_m.SizeUsd = value.Float64
			}
		case pendingorder.FieldSizeQty:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field size_qty", values[i])
			} else if value.Valid {
				_m.SizeQty = value.Float64
			}
		case pendingorder.FieldRiskUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field risk_usd", values[i])
			} else if value.Valid {
				_m.RiskUsd = value.Float64
			}
		case pendingorder.FieldRiskPercent:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field risk_percent", values[i])
			} else if value.Valid {
				_m.RiskPercent = value.Float64
			}
		case pendingorder.FieldExpectedRr:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field expected_rr", values[i])
			} else if value.Valid {
				_m.ExpectedRr = value.Float64
			}
		case pendingorder.FieldLinkedPredictionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field linked_prediction_id", values[i])
			} else if value.Valid {
				_m.LinkedPredictionID = new(int)
				*_m.LinkedPredictionID = int(value.Int64)
			}
		case pendingorder.FieldInvalidationLevel:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field invalidation_level", values[i])
			} else if value.Valid {
				_m.InvalidationLevel = new(float64)
				*_m.InvalidationLevel = value.Float64
			}
		case pendingorder.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case pendingorder.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case pendingorder.FieldExecutedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field executed_at", values[i])
			} else if value.Valid {
				_m.ExecutedAt = new(time.Time)
				*_m.ExecutedAt = value.Time
			}
		case pendingorder.FieldExecutedPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field executed_price", values[i])
			} else if value.Valid {
				_m.ExecutedPrice = new(float64)
				*_m.ExecutedPrice = value.Float64
			}
		case pendingorder.FieldExecutedSizeQty:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field executed_size_qty", values[i])
			} else if value.Valid {
				_m.ExecutedSizeQty = new(float64)
				*_m.ExecutedSizeQty = value.Float64
			}
		case pendingorder.FieldExecutedSizeUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field executed_size_usd", values[i])
			} else if value.Valid {
				_m.ExecutedSizeUsd = new(float64)
				*_m.ExecutedSizeUsd = value.Float64
			}
		case pendingorder.FieldRealizedPnl:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field realized_pnl", values[i])
			} else if value.Valid {
				_m.RealizedPnl = new(float64)
				*_m.RealizedPnl = value.Float64
			}
		case pendingorder.FieldRealizedPnlPercent:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field realized_pnl_percent", values[i])
			} else if value.Valid {
				_m.RealizedPnlPercent = new(float64)
				*_m.RealizedPnlPercent = value.Float64
			}
		case pendingorder.FieldCloseReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field close_reason", values[i])
			} else if value.Valid {
				_m.CloseReason = new(string)
				*_m.CloseReason = value.String
			}
		case pendingorder.FieldBinanceOrderID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field binance_order_id", values[i])
			} else if value.Valid {
				_m.BinanceOrderID = new(string)
				*_m.BinanceOrderID = value.String
			}
		case pendingorder.FieldMethodID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field method_id", values[i])
			} else if value.Valid {
				_m.MethodID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PendingOrder.
// This includes values selected through modifiers, order, etc.
func (_m *PendingOrder) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccount queries the "account" edge of the PendingOrder entity.
func (_m *PendingOrder) QueryAccount() *AccountQuery {
	return NewPendingOrderClient(_m.config).QueryAccount(_m)
}

// Update returns a builder for updating this PendingOrder.
// Note that you need to call PendingOrder.Unwrap() before calling this method if this PendingOrder
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PendingOrder) Update() *PendingOrderUpdateOne {
	return NewPendingOrderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PendingOrder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PendingOrder) Unwrap() *PendingOrder {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PendingOrder is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PendingOrder) String() string {
	var builder strings.Builder
	builder.WriteString("PendingOrder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("order_id=")
	builder.WriteString(_m.OrderID)
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("symbol=")
	builder.WriteString(_m.Symbol)
	builder.WriteString(", ")
	builder.WriteString("side=")
	builder.WriteString(_m.Side)
	builder.WriteString(", ")
	builder.WriteString("entry_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.EntryPrice))
	builder.WriteString(", ")
	builder.WriteString("stop_loss=")
	builder.WriteString(fmt.Sprintf("%v", _m.StopLoss))
	builder.WriteString(", ")
	builder.WriteString("take_profit=")
	builder.WriteString(fmt.Sprintf("%v", _m.TakeProfit))
	builder.WriteString(", ")
	builder.WriteString("size_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.SizeUsd))
	builder.WriteString(", ")
	builder.WriteString("size_qty=")
	builder.WriteString(fmt.Sprintf("%v", _m.SizeQty))
	builder.WriteString(", ")
	builder.WriteString("risk_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.RiskUsd))
	builder.WriteString(", ")
	builder.WriteString("risk_percent=")
	builder.WriteString(fmt.Sprintf("%v", _m.RiskPercent))
	builder.WriteString(", ")
	builder.WriteString("expected_rr=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExpectedRr))
	builder.WriteString(", ")
	if v := _m.LinkedPredictionID; v != nil {
		builder.WriteString("linked_prediction_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.InvalidationLevel; v != nil {
		builder.WriteString("invalidation_level=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ExecutedAt; v != nil {
		builder.WriteString("executed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ExecutedPrice; v != nil {
		builder.WriteString("executed_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ExecutedSizeQty; v != nil {
		builder.WriteString("executed_size_qty=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ExecutedSizeUsd; v != nil {
		builder.WriteString("executed_size_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RealizedPnl; v != nil {
		builder.WriteString("realized_pnl=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RealizedPnlPercent; v != nil {
		builder.WriteString("realized_pnl_percent=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CloseReason; v != nil {
		builder.WriteString("close_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.BinanceOrderID; v != nil {
		builder.WriteString("binance_order_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("method_id=")
	builder.WriteString(_m.MethodID)
	builder.WriteByte(')')
	return builder.String()
}

// PendingOrders is a parsable slice of PendingOrder.
type PendingOrders []*PendingOrder
