// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/chuyen-gia-crypto/backend/internal/db/ent/account"
	"github.com/chuyen-gia-crypto/backend/internal/db/ent/position"
	"github.com/chuyen-gia-crypto/backend/internal/db/ent/predicate"
	"github.com/chuyen-gia-crypto/backend/internal/db/ent/tradeevent"
)

// PositionUpdate is the builder for updating Position entities.
type PositionUpdate struct {
	config
	hooks    []Hook
	mutation *PositionMutation
}

// Where appends a list predicates to the PositionUpdate builder.
func (_u *PositionUpdate) Where(ps ...predicate.Position) *PositionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPositionID sets the "position_id" field.
func (_u *PositionUpdate) SetPositionID(v string) *PositionUpdate {
	_u.mutation.SetPositionID(v)
	return _u
}

// SetNillablePositionID sets the "position_id" field if the given value is not nil.
func (_u *PositionUpdate) SetNillablePositionID(v *string) *PositionUpdate {
	if v != nil {
		_u.SetPositionID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *PositionUpdate) SetAccountID(v int) *PositionUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *PositionUpdate) SetNillableAccountID(v *int) *PositionUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetSymbol sets the "symbol" field.
func (_u *PositionUpdate) SetSymbol(v string) *PositionUpdate {
	_u.mutation.SetSymbol(v)
	return _u
}

// SetNillableSymbol sets the "symbol" field if the given value is not nil.
func (_u *PositionUpdate) SetNillableSymbol(v *string) *PositionUpdate {
	if v != nil {
		_u.SetSymbol(*v)
	}
	return _u
}

// SetSide sets the "side" field.
func (_u *PositionUpdate) SetSide(v string) *PositionUpdate {
	_u.mutation.SetSide(v)
	return _u
}

// SetNillableSide sets the "side" field if the given value is not nil.
func (_u *PositionUpdate) SetNillableSide(v *string) *PositionUpdate {
	if v != nil {
		_u.SetSide(*v)
	}
	return _u
}

// SetEntryPrice sets the "entry_price" field.
func (_u *PositionUpdate) SetEntryPrice(v float64) *PositionUpdate {
	_u.mutation.ResetEntryPrice()
	_u.mutation.SetEntryPrice(v)
	return _u
}

// SetNillableEntryPrice sets the "entry_price" field if the given value is not nil.
func (_u *PositionUpdate) SetNillableEntryPrice(v *float64) *PositionUpdate {
	if v != nil {
		_u.SetEntryPrice(*v)
	}
	return _u
}

// AddEntryPrice adds value to the "entry_price" field.
func (_u *PositionUpdate) AddEntryPrice(v float64) *PositionUpdate {
	_u.mutation.AddEntryPrice(v)
	return _u
}

// SetCurrentPrice sets the "current_price" field.
func (_u *PositionUpdate) SetCurrentPrice(v float64) *PositionUpdate {
	_u.mutation.ResetCurrentPrice()
	_u.mutation.SetCurrentPrice(v)
	return _u
}

// SetNillableCurrentPrice sets the "current_price" field if the given value is not nil.
func (_u *PositionUpdate) SetNillableCurrentPrice(v *float64) *PositionUpdate {
	if v != nil {
		_u.SetCurrentPrice(*v)
	}
	return _u
}

// AddCurrentPrice adds value to the "current_price" field.
func (_u *PositionUpdate) AddCurrentPrice(v float64) *PositionUpdate {
	_u.mutation.AddCurrentPrice(v)
	return _u
}

// SetStopLoss sets the "stop_loss" field.
func (_u *PositionUpdate) SetStopLoss(v float64) *PositionUpdate {
	_u.mutation.ResetStopLoss()
	_u.mutation.SetStopLoss(v)
	return _u
}

// SetNillableStopLoss sets the "stop_loss" field if the given value is not nil.
func (_u *PositionUpdate) SetNillableStopLoss(v *float64) *PositionUpdate {
	if v != nil {
		_u.SetStopLoss(*v)
	}
	return _u
}

// AddStopLoss adds value to the "stop_loss" field.
func (_u *PositionUpdate) AddStopLoss(v float64) *PositionUpdate {
	_u.mutation.AddStopLoss(v)
	return _u
}

// SetTakeProfit sets the "take_profit" field.
func (_u *PositionUpdate) SetTakeProfit(v float64) *PositionUpdate {
	_u.mutation.ResetTakeProfit()
	_u.mutation.SetTakeProfit(v)
	return _u
}

// SetNillableTakeProfit sets the "take_profit" field if the given value is not nil.
func (_u *PositionUpdate) SetNillableTakeProfit(v *float64) *PositionUpdate {
	if v != nil {
		_u.SetTakeProfit(*v)
	}
	return _u
}

// AddTakeProfit adds value to the "take_profit" field.
func (_u *PositionUpdate) AddTakeProfit(v float64) *PositionUpdate {
	_u.mutation.AddTakeProfit(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PositionUpdate) SetStatus(v string) *PositionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PositionUpdate) SetNillableStatus(v *string) *PositionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSizeUsd sets the "size_usd" field.
func (_u *PositionUpdate) SetSizeUsd(v float64) *PositionUpdate {
	_u.mutation.ResetSizeUsd()
	_u.mutation.SetSizeUsd(v)
	return _u
}

// SetNillableSizeUsd sets the "size_usd" field if the given value is not nil.
func (_u *PositionUpdate) SetNillableSizeUsd(v *float64) *PositionUpdate {
	if v != nil {
		_u.SetSizeUsd(*v)
	}
	return _u
}

// AddSizeUsd adds value to the "size_usd" field.
func (_u *PositionUpdate) AddSizeUsd(v float64) *PositionUpdate {
	_u.mutation.AddSizeUsd(v)
	return _u
}

// SetSizeQty sets the "size_qty" field.
func (_u *PositionUpdate) SetSizeQty(v float64) *PositionUpdate {
	_u.mutation.ResetSizeQty()
	_u.mutation.SetSizeQty(v)
	return _u
}

// SetNillableSizeQty sets the "size_qty" field if the given value is not nil.
func (_u *PositionUpdate) SetNillableSizeQty(v *float64) *PositionUpdate {
	if v != nil {
		_u.SetSizeQty(*v)
	}
	return _u
}

// AddSizeQty adds value to the "size_qty" field.
func (_u *PositionUpdate) AddSizeQty(v float64) *PositionUpdate {
	_u.mutation.AddSizeQty(v)
	return _u
}

// SetRiskUsd sets the "risk_usd" field.
func (_u *PositionUpdate) SetRiskUsd(v float64) *PositionUpdate {
	_u.mutation.ResetRiskUsd()
	_u.mutation.SetRiskUsd(v)
	return _u
}

// SetNillableRiskUsd sets the "risk_usd" field if the given value is not nil.
func (_u *PositionUpdate) SetNillableRiskUsd(v *float64) *PositionUpdate {
	if v != nil {
		_u.SetRiskUsd(*v)
	}
	return _u
}

// AddRiskUsd adds value to the "risk_usd" field.
func (_u *PositionUpdate) AddRiskUsd(v float64) *PositionUpdate {
	_u.mutation.AddRiskUsd(v)
	return _u
}

// SetRiskPercent sets the "risk_percent" field.
func (_u *PositionUpdate) SetRiskPercent(v float64) *PositionUpdate {
	_u.mutation.ResetRiskPercent()
	_u.mutation.SetRiskPercent(v)
	return _u
}

// SetNillableRiskPercent sets the "risk_percent" field if the given value is not nil.
func (_u *PositionUpdate) SetNillableRiskPercent(v *float64) *PositionUpdate {
	if v != nil {
		_u.SetRiskPercent(*v)
	}
	return _u
}

// AddRiskPercent adds value to the "risk_percent" field.
func (_u *PositionUpdate) AddRiskPercent(v float64) *PositionUpdate {
	_u.mutation.AddRiskPercent(v)
	return _u
}

// SetExpectedRr sets the "expected_rr" field.
func (_u *PositionUpdate) SetExpectedRr(v float64) *PositionUpdate {
	_u.mutation.ResetExpectedRr()
	_u.mutation.SetExpectedRr(v)
	return _u
}

// SetNillableExpectedRr sets the "expected_rr" field if the given value is not nil.
func (_u *PositionUpdate) SetNillableExpectedRr(v *float64) *PositionUpdate {
	if v != nil {
		_u.SetExpectedRr(*v)
	}
	return _u
}

// AddExpectedRr adds value to the "expected_rr" field.
func (_u *PositionUpdate) AddExpectedRr(v float64) *PositionUpdate {
	_u.mutation.AddExpectedRr(v)
	return _u
}

// SetRealizedPnl sets the "realized_pnl" field.
func (_u *PositionUpdate) SetRealizedPnl(v float64) *PositionUpdate {
	_u.mutation.ResetRealizedPnl()
	_u.mutation.SetRealizedPnl(v)
	return _u
}

// SetNillableRealizedPnl sets the "realized_pnl" field if the given value is not nil.
func (_u *PositionUpdate) SetNillableRealizedPnl(v *float64) *PositionUpdate {
	if v != nil {
		_u.SetRealizedPnl(*v)
	}
	return _u
}

// AddRealizedPnl adds value to the "realized_pnl" field.
func (_u *PositionUpdate) AddRealizedPnl(v float64) *PositionUpdate {
	_u.mutation.AddRealizedPnl(v)
	return _u
}

// SetUnrealizedPnl sets the "unrealized_pnl" field.
func (_u *PositionUpdate) SetUnrealizedPnl(v float64) *PositionUpdate {
	_u.mutation.ResetUnrealizedPnl()
	_u.mutation.SetUnrealizedPnl(v)
	return _u
}

// SetNillableUnrealizedPnl sets the "unrealized_pnl" field if the given value is not nil.
func (_u *PositionUpdate) SetNillableUnrealizedPnl(v *float64) *PositionUpdate {
	if v != nil {
		_u.SetUnrealizedPnl(*v)
	}
	return _u
}

// AddUnrealizedPnl adds value to the "unrealized_pnl" field.
func (_u *PositionUpdate) AddUnrealizedPnl(v float64) *PositionUpdate {
	_u.mutation.AddUnrealizedPnl(v)
	return _u
}

// SetClosePrice sets the "close_price" field.
func (_u *PositionUpdate) SetClosePrice(v float64) *PositionUpdate {
	_u.mutation.ResetClosePrice()
	_u.mutation.SetClosePrice(v)
	return _u
}

// SetNillableClosePrice sets the "close_price" field if the given value is not nil.
func (_u *PositionUpdate) SetNillableClosePrice(v *float64) *PositionUpdate {
	if v != nil {
		_u.SetClosePrice(*v)
	}
	return _u
}

// AddClosePrice adds value to the "close_price" field.
func (_u *PositionUpdate) AddClosePrice(v float64) *PositionUpdate {
	_u.mutation.AddClosePrice(v)
	return _u
}

// ClearClosePrice clears the value of the "close_price" field.
func (_u *PositionUpdate) ClearClosePrice() *PositionUpdate {
	_u.mutation.ClearClosePrice()
	return _u
}

// SetCloseTime sets the "close_time" field.
func (_u *PositionUpdate) SetCloseTime(v time.Time) *PositionUpdate {
	_u.mutation.SetCloseTime(v)
	return _u
}

// SetNillableCloseTime sets the "close_time" field if the given value is not nil.
func (_u *PositionUpdate) SetNillableCloseTime(v *time.Time) *PositionUpdate {
	if v != nil {
		_u.SetCloseTime(*v)
	}
	return _u
}

// ClearCloseTime clears the value of the "close_time" field.
func (_u *PositionUpdate) ClearCloseTime() *PositionUpdate {
	_u.mutation.ClearCloseTime()
	return _u
}

// SetCloseReason sets the "close_reason" field.
func (_u *PositionUpdate) SetCloseReason(v string) *PositionUpdate {
	_u.mutation.SetCloseReason(v)
	return _u
}

// SetNillableCloseReason sets the "close_reason" field if the given value is not nil.
func (_u *PositionUpdate) SetNillableCloseReason(v *string) *PositionUpdate {
	if v != nil {
		_u.SetCloseReason(*v)
	}
	return _u
}

// ClearCloseReason clears the value of the "close_reason" field.
func (_u *PositionUpdate) ClearCloseReason() *PositionUpdate {
	_u.mutation.ClearCloseReason()
	return _u
}

// SetLinkedPredictionID sets the "linked_prediction_id" field.
func (_u *PositionUpdate) SetLinkedPredictionID(v int) *PositionUpdate {
	_u.mutation.ResetLinkedPredictionID()
	_u.mutation.SetLinkedPredictionID(v)
	return _u
}

// SetNillableLinkedPredictionID sets the "linked_prediction_id" field if the given value is not nil.
func (_u *PositionUpdate) SetNillableLinkedPredictionID(v *int) *PositionUpdate {
	if v != nil {
		_u.SetLinkedPredictionID(*v)
	}
	return _u
}

// AddLinkedPredictionID adds value to the "linked_prediction_id" field.
func (_u *PositionUpdate) AddLinkedPredictionID(v int) *PositionUpdate {
	_u.mutation.AddLinkedPredictionID(v)
	return _u
}

// ClearLinkedPredictionID clears the value of the "linked_prediction_id" field.
func (_u *PositionUpdate) ClearLinkedPredictionID() *PositionUpdate {
	_u.mutation.ClearLinkedPredictionID()
	return _u
}

// SetInvalidationLevel sets the "invalidation_level" field.
func (_u *PositionUpdate) SetInvalidationLevel(v float64) *PositionUpdate {
	_u.mutation.ResetInvalidationLevel()
	_u.mutation.SetInvalidationLevel(v)
	return _u
}

// SetNillableInvalidationLevel sets the "invalidation_level" field if the given value is not nil.
func (_u *PositionUpdate) SetNillableInvalidationLevel(v *float64) *PositionUpdate {
	if v != nil {
		_u.SetInvalidationLevel(*v)
	}
	return _u
}

// AddInvalidationLevel adds value to the "invalidation_level" field.
func (_u *PositionUpdate) AddInvalidationLevel(v float64) *PositionUpdate {
	_u.mutation.AddInvalidationLevel(v)
	return _u
}

// ClearInvalidationLevel clears the value of the "invalidation_level" field.
func (_u *PositionUpdate) ClearInvalidationLevel() *PositionUpdate {
	_u.mutation.ClearInvalidationLevel()
	return _u
}

// SetTp1Hit sets the "tp1_hit" field.
func (_u *PositionUpdate) SetTp1Hit(v int) *PositionUpdate {
	_u.mutation.ResetTp1Hit()
	_u.mutation.SetTp1Hit(v)
	return _u
}

// SetNillableTp1Hit sets the "tp1_hit" field if the given value is not nil.
func (_u *PositionUpdate) SetNillableTp1Hit(v *int) *PositionUpdate {
	if v != nil {
		_u.SetTp1Hit(*v)
	}
	return _u
}

// AddTp1Hit adds value to the "tp1_hit" field.
func (_u *PositionUpdate) AddTp1Hit(v int) *PositionUpdate {
	_u.mutation.AddTp1Hit(v)
	return _u
}

// SetIctStrategy sets the "ict_strategy" field.
func (_u *PositionUpdate) SetIctStrategy(v string) *PositionUpdate {
	_u.mutation.SetIctStrategy(v)
	return _u
}

// SetNillableIctStrategy sets the "ict_strategy" field if the given value is not nil.
func (_u *PositionUpdate) SetNillableIctStrategy(v *string) *PositionUpdate {
	if v != nil {
		_u.SetIctStrategy(*v)
	}
	return _u
}

// ClearIctStrategy clears the value of the "ict_strategy" field.
func (_u *PositionUpdate) ClearIctStrategy() *PositionUpdate {
	_u.mutation.ClearIctStrategy()
	return _u
}

// SetTpLevels sets the "tp_levels" field.
func (_u *PositionUpdate) SetTpLevels(v string) *PositionUpdate {
	_u.mutation.SetTpLevels(v)
	return _u
}

// SetNillableTpLevels sets the "tp_levels" field if the given value is not nil.
func (_u *PositionUpdate) SetNillableTpLevels(v *string) *PositionUpdate {
	if v != nil {
		_u.SetTpLevels(*v)
	}
	return _u
}

// ClearTpLevels clears the value of the "tp_levels" field.
func (_u *PositionUpdate) ClearTpLevels() *PositionUpdate {
	_u.mutation.ClearTpLevels()
	return _u
}

// SetTpHitCount sets the "tp_hit_count" field.
func (_u *PositionUpdate) SetTpHitCount(v int) *PositionUpdate {
	_u.mutation.ResetTpHitCount()
	_u.mutation.SetTpHitCount(v)
	return _u
}

// SetNillableTpHitCount sets the "tp_hit_count" field if the given value is not nil.
func (_u *PositionUpdate) SetNillableTpHitCount(v *int) *PositionUpdate {
	if v != nil {
		_u.SetTpHitCount(*v)
	}
	return _u
}

// AddTpHitCount adds value to the "tp_hit_count" field.
func (_u *PositionUpdate) AddTpHitCount(v int) *PositionUpdate {
	_u.mutation.AddTpHitCount(v)
	return _u
}

// SetPartialClosed sets the "partial_closed" field.
func (_u *PositionUpdate) SetPartialClosed(v float64) *PositionUpdate {
	_u.mutation.ResetPartialClosed()
	_u.mutation.SetPartialClosed(v)
	return _u
}

// SetNillablePartialClosed sets the "partial_closed" field if the given value is not nil.
func (_u *PositionUpdate) SetNillablePartialClosed(v *float64) *PositionUpdate {
	if v != nil {
		_u.SetPartialClosed(*v)
	}
	return _u
}

// AddPartialClosed adds value to the "partial_closed" field.
func (_u *PositionUpdate) AddPartialClosed(v float64) *PositionUpdate {
	_u.mutation.AddPartialClosed(v)
	return _u
}

// SetRMultiple sets the "r_multiple" field.
func (_u *PositionUpdate) SetRMultiple(v float64) *PositionUpdate {
	_u.mutation.ResetRMultiple()
	_u.mutation.SetRMultiple(v)
	return _u
}

// SetNillableRMultiple sets the "r_multiple" field if the given value is not nil.
func (_u *PositionUpdate) SetNillableRMultiple(v *float64) *PositionUpdate {
	if v != nil {
		_u.SetRMultiple(*v)
	}
	return _u
}

// AddRMultiple adds value to the "r_multiple" field.
func (_u *PositionUpdate) AddRMultiple(v float64) *PositionUpdate {
	_u.mutation.AddRMultiple(v)
	return _u
}

// SetMethodID sets the "method_id" field.
func (_u *PositionUpdate) SetMethodID(v string) *PositionUpdate {
	_u.mutation.SetMethodID(v)
	return _u
}

// SetNillableMethodID sets the "method_id" field if the given value is not nil.
func (_u *PositionUpdate) SetNillableMethodID(v *string) *PositionUpdate {
	if v != nil {
		_u.SetMethodID(*v)
	}
	return _u
}

// ClearMethodID clears the value of the "method_id" field.
func (_u *PositionUpdate) ClearMethodID() *PositionUpdate {
	_u.mutation.ClearMethodID()
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *PositionUpdate) SetAccount(v *Account) *PositionUpdate {
	return _u.SetAccountID(v.ID)
}

// AddEventIDs adds the "events" edge to the TradeEvent entity by IDs.
func (_u *PositionUpdate) AddEventIDs(ids ...int) *PositionUpdate {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the TradeEvent entity.
func (_u *PositionUpdate) AddEvents(v ...*TradeEvent) *PositionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// Mutation returns the PositionMutation object of the builder.
func (_u *PositionUpdate) Mutation() *PositionMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *PositionUpdate) ClearAccount() *PositionUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// ClearEvents clears all "events" edges to the TradeEvent entity.
func (_u *PositionUpdate) ClearEvents() *PositionUpdate {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to TradeEvent entities by IDs.
func (_u *PositionUpdate) RemoveEventIDs(ids ...int) *PositionUpdate {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to TradeEvent entities.
func (_u *PositionUpdate) RemoveEvents(v ...*TradeEvent) *PositionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PositionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PositionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PositionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PositionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PositionUpdate) check() error {
	if v, ok := _u.mutation.PositionID(); ok {
		if err := position.PositionIDValidator(v); err != nil {
			return &ValidationError{Name: "position_id", err: fmt.Errorf(`ent: validator failed for field "Position.position_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Symbol(); ok {
		if err := position.SymbolValidator(v); err != nil {
			return &ValidationError{Name: "symbol", err: fmt.Errorf(`ent: validator failed for field "Position.symbol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Side(); ok {
		if err := position.SideValidator(v); err != nil {
			return &ValidationError{Name: "side", err: fmt.Errorf(`ent: validator failed for field "Position.side": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := position.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Position.status": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Position.account"`)
	}
	return nil
}

func (_u *PositionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(position.Table, position.Columns, sqlgraph.NewFieldSpec(position.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PositionID(); ok {
		_spec.SetField(position.FieldPositionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Symbol(); ok {
		_spec.SetField(position.FieldSymbol, field.TypeString, value)
	}
	if value, ok := _u.mutation.Side(); ok {
		_spec.SetField(position.FieldSide, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntryPrice(); ok {
		_spec.SetField(position.FieldEntryPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEntryPrice(); ok {
		_spec.AddField(position.FieldEntryPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CurrentPrice(); ok {
		_spec.SetField(position.FieldCurrentPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCurrentPrice(); ok {
		_spec.AddField(position.FieldCurrentPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.StopLoss(); ok {
		_spec.SetField(position.FieldStopLoss, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedStopLoss(); ok {
		_spec.AddField(position.FieldStopLoss, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TakeProfit(); ok {
		_spec.SetField(position.FieldTakeProfit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTakeProfit(); ok {
		_spec.AddField(position.FieldTakeProfit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(position.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeUsd(); ok {
		_spec.SetField(position.FieldSizeUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSizeUsd(); ok {
		_spec.AddField(position.FieldSizeUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SizeQty(); ok {
		_spec.SetField(position.FieldSizeQty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSizeQty(); ok {
		_spec.AddField(position.FieldSizeQty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RiskUsd(); ok {
		_spec.SetField(position.FieldRiskUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRiskUsd(); ok {
		_spec.AddField(position.FieldRiskUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RiskPercent(); ok {
		_spec.SetField(position.FieldRiskPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRiskPercent(); ok {
		_spec.AddField(position.FieldRiskPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ExpectedRr(); ok {
		_spec.SetField(position.FieldExpectedRr, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedExpectedRr(); ok {
		_spec.AddField(position.FieldExpectedRr, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RealizedPnl(); ok {
		_spec.SetField(position.FieldRealizedPnl, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRealizedPnl(); ok {
		_spec.AddField(position.FieldRealizedPnl, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UnrealizedPnl(); ok {
		_spec.SetField(position.FieldUnrealizedPnl, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUnrealizedPnl(); ok {
		_spec.AddField(position.FieldUnrealizedPnl, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ClosePrice(); ok {
		_spec.SetField(position.FieldClosePrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedClosePrice(); ok {
		_spec.AddField(position.FieldClosePrice, field.TypeFloat64, value)
	}
	if _u.mutation.ClosePriceCleared() {
		_spec.ClearField(position.FieldClosePrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CloseTime(); ok {
		_spec.SetField(position.FieldCloseTime, field.TypeTime, value)
	}
	if _u.mutation.CloseTimeCleared() {
		_spec.ClearField(position.FieldCloseTime, field.TypeTime)
	}
	if value, ok := _u.mutation.CloseReason(); ok {
		_spec.SetField(position.FieldCloseReason, field.TypeString, value)
	}
	if _u.mutation.CloseReasonCleared() {
		_spec.ClearField(position.FieldCloseReason, field.TypeString)
	}
	if value, ok := _u.mutation.LinkedPredictionID(); ok {
		_spec.SetField(position.FieldLinkedPredictionID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLinkedPredictionID(); ok {
		_spec.AddField(position.FieldLinkedPredictionID, field.TypeInt, value)
	}
	if _u.mutation.LinkedPredictionIDCleared() {
		_spec.ClearField(position.FieldLinkedPredictionID, field.TypeInt)
	}
	if value, ok := _u.mutation.InvalidationLevel(); ok {
		_spec.SetField(position.FieldInvalidationLevel, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInvalidationLevel(); ok {
		_spec.AddField(position.FieldInvalidationLevel, field.TypeFloat64, value)
	}
	if _u.mutation.InvalidationLevelCleared() {
		_spec.ClearField(position.FieldInvalidationLevel, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Tp1Hit(); ok {
		_spec.SetField(position.FieldTp1Hit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTp1Hit(); ok {
		_spec.AddField(position.FieldTp1Hit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IctStrategy(); ok {
		_spec.SetField(position.FieldIctStrategy, field.TypeString, value)
	}
	if _u.mutation.IctStrategyCleared() {
		_spec.ClearField(position.FieldIctStrategy, field.TypeString)
	}
	if value, ok := _u.mutation.TpLevels(); ok {
		_spec.SetField(position.FieldTpLevels, field.TypeString, value)
	}
	if _u.mutation.TpLevelsCleared() {
		_spec.ClearField(position.FieldTpLevels, field.TypeString)
	}
	if value, ok := _u.mutation.TpHitCount(); ok {
		_spec.SetField(position.FieldTpHitCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTpHitCount(); ok {
		_spec.AddField(position.FieldTpHitCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PartialClosed(); ok {
		_spec.SetField(position.FieldPartialClosed, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPartialClosed(); ok {
		_spec.AddField(position.FieldPartialClosed, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RMultiple(); ok {
		_spec.SetField(position.FieldRMultiple, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRMultiple(); ok {
		_spec.AddField(position.FieldRMultiple, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MethodID(); ok {
		_spec.SetField(position.FieldMethodID, field.TypeString, value)
	}
	if _u.mutation.MethodIDCleared() {
		_spec.ClearField(position.FieldMethodID, field.TypeString)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   position.AccountTable,
			Columns: []string{position.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   position.AccountTable,
			Columns: []string{position.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.EventsTable,
			Columns: []string{position.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tradeevent.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.EventsTable,
			Columns: []string{position.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tradeevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.EventsTable,
			Columns: []string{position.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tradeevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{position.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PositionUpdateOne is the builder for updating a single Position entity.
type PositionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PositionMutation
}

// SetPositionID sets the "position_id" field.
func (_u *PositionUpdateOne) SetPositionID(v string) *PositionUpdateOne {
	_u.mutation.SetPositionID(v)
	return _u
}

// SetNillablePositionID sets the "position_id" field if the given value is not nil.
func (_u *PositionUpdateOne) SetNillablePositionID(v *string) *PositionUpdateOne {
	if v != nil {
		_u.SetPositionID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *PositionUpdateOne) SetAccountID(v int) *PositionUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *PositionUpdateOne) SetNillableAccountID(v *int) *PositionUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetSymbol sets the "symbol" field.
func (_u *PositionUpdateOne) SetSymbol(v string) *PositionUpdateOne {
	_u.mutation.SetSymbol(v)
	return _u
}

// SetNillableSymbol sets the "symbol" field if the given value is not nil.
func (_u *PositionUpdateOne) SetNillableSymbol(v *string) *PositionUpdateOne {
	if v != nil {
		_u.SetSymbol(*v)
	}
	return _u
}

// SetSide sets the "side" field.
func (_u *PositionUpdateOne) SetSide(v string) *PositionUpdateOne {
	_u.mutation.SetSide(v)
	return _u
}

// SetNillableSide sets the "side" field if the given value is not nil.
func (_u *PositionUpdateOne) SetNillableSide(v *string) *PositionUpdateOne {
	if v != nil {
		_u.SetSide(*v)
	}
	return _u
}

// SetEntryPrice sets the "entry_price" field.
func (_u *PositionUpdateOne) SetEntryPrice(v float64) *PositionUpdateOne {
	_u.mutation.ResetEntryPrice()
	_u.mutation.SetEntryPrice(v)
	return _u
}

// SetNillableEntryPrice sets the "entry_price" field if the given value is not nil.
func (_u *PositionUpdateOne) SetNillableEntryPrice(v *float64) *PositionUpdateOne {
	if v != nil {
		_u.SetEntryPrice(*v)
	}
	return _u
}

// AddEntryPrice adds value to the "entry_price" field.
func (_u *PositionUpdateOne) AddEntryPrice(v float64) *PositionUpdateOne {
	_u.mutation.AddEntryPrice(v)
	return _u
}

// SetCurrentPrice sets the "current_price" field.
func (_u *PositionUpdateOne) SetCurrentPrice(v float64) *PositionUpdateOne {
	_u.mutation.ResetCurrentPrice()
	_u.mutation.SetCurrentPrice(v)
	return _u
}

// SetNillableCurrentPrice sets the "current_price" field if the given value is not nil.
func (_u *PositionUpdateOne) SetNillableCurrentPrice(v *float64) *PositionUpdateOne {
	if v != nil {
		_u.SetCurrentPrice(*v)
	}
	return _u
}

// AddCurrentPrice adds value to the "current_price" field.
func (_u *PositionUpdateOne) AddCurrentPrice(v float64) *PositionUpdateOne {
	_u.mutation.AddCurrentPrice(v)
	return _u
}

// SetStopLoss sets the "stop_loss" field.
func (_u *PositionUpdateOne) SetStopLoss(v float64) *PositionUpdateOne {
	_u.mutation.ResetStopLoss()
	_u.mutation.SetStopLoss(v)
	return _u
}

// SetNillableStopLoss sets the "stop_loss" field if the given value is not nil.
func (_u *PositionUpdateOne) SetNillableStopLoss(v *float64) *PositionUpdateOne {
	if v != nil {
		_u.SetStopLoss(*v)
	}
	return _u
}

// AddStopLoss adds value to the "stop_loss" field.
func (_u *PositionUpdateOne) AddStopLoss(v float64) *PositionUpdateOne {
	_u.mutation.AddStopLoss(v)
	return _u
}

// SetTakeProfit sets the "take_profit" field.
func (_u *PositionUpdateOne) SetTakeProfit(v float64) *PositionUpdateOne {
	_u.mutation.ResetTakeProfit()
	_u.mutation.SetTakeProfit(v)
	return _u
}

// SetNillableTakeProfit sets the "take_profit" field if the given value is not nil.
func (_u *PositionUpdateOne) SetNillableTakeProfit(v *float64) *PositionUpdateOne {
	if v != nil {
		_u.SetTakeProfit(*v)
	}
	return _u
}

// AddTakeProfit adds value to the "take_profit" field.
func (_u *PositionUpdateOne) AddTakeProfit(v float64) *PositionUpdateOne {
	_u.mutation.AddTakeProfit(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PositionUpdateOne) SetStatus(v string) *PositionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PositionUpdateOne) SetNillableStatus(v *string) *PositionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSizeUsd sets the "size_usd" field.
func (_u *PositionUpdateOne) SetSizeUsd(v float64) *PositionUpdateOne {
	_u.mutation.ResetSizeUsd()
	_u.mutation.SetSizeUsd(v)
	return _u
}

// SetNillableSizeUsd sets the "size_usd" field if the given value is not nil.
func (_u *PositionUpdateOne) SetNillableSizeUsd(v *float64) *PositionUpdateOne {
	if v != nil {
		_u.SetSizeUsd(*v)
	}
	return _u
}

// AddSizeUsd adds value to the "size_usd" field.
func (_u *PositionUpdateOne) AddSizeUsd(v float64) *PositionUpdateOne {
	_u.mutation.AddSizeUsd(v)
	return _u
}

// SetSizeQty sets the "size_qty" field.
func (_u *PositionUpdateOne) SetSizeQty(v float64) *PositionUpdateOne {
	_u.mutation.ResetSizeQty()
	_u.mutation.SetSizeQty(v)
	return _u
}

// SetNillableSizeQty sets the "size_qty" field if the given value is not nil.
func (_u *PositionUpdateOne) SetNillableSizeQty(v *float64) *PositionUpdateOne {
	if v != nil {
		_u.SetSizeQty(*v)
	}
	return _u
}

// AddSizeQty adds value to the "size_qty" field.
func (_u *PositionUpdateOne) AddSizeQty(v float64) *PositionUpdateOne {
	_u.mutation.AddSizeQty(v)
	return _u
}

// SetRiskUsd sets the "risk_usd" field.
func (_u *PositionUpdateOne) SetRiskUsd(v float64) *PositionUpdateOne {
	_u.mutation.ResetRiskUsd()
	_u.mutation.SetRiskUsd(v)
	return _u
}

// SetNillableRiskUsd sets the "risk_usd" field if the given value is not nil.
func (_u *PositionUpdateOne) SetNillableRiskUsd(v *float64) *PositionUpdateOne {
	if v != nil {
		_u.SetRiskUsd(*v)
	}
	return _u
}

// AddRiskUsd adds value to the "risk_usd" field.
func (_u *PositionUpdateOne) AddRiskUsd(v float64) *PositionUpdateOne {
	_u.mutation.AddRiskUsd(v)
	return _u
}

// SetRiskPercent sets the "risk_percent" field.
func (_u *PositionUpdateOne) SetRiskPercent(v float64) *PositionUpdateOne {
	_u.mutation.ResetRiskPercent()
	_u.mutation.SetRiskPercent(v)
	return _u
}

// SetNillableRiskPercent sets the "risk_percent" field if the given value is not nil.
func (_u *PositionUpdateOne) SetNillableRiskPercent(v *float64) *PositionUpdateOne {
	if v != nil {
		_u.SetRiskPercent(*v)
	}
	return _u
}

// AddRiskPercent adds value to the "risk_percent" field.
func (_u *PositionUpdateOne) AddRiskPercent(v float64) *PositionUpdateOne {
	_u.mutation.AddRiskPercent(v)
	return _u
}

// SetExpectedRr sets the "expected_rr" field.
func (_u *PositionUpdateOne) SetExpectedRr(v float64) *PositionUpdateOne {
	_u.mutation.ResetExpectedRr()
	_u.mutation.SetExpectedRr(v)
	return _u
}

// SetNillableExpectedRr sets the "expected_rr" field if the given value is not nil.
func (_u *PositionUpdateOne) SetNillableExpectedRr(v *float64) *PositionUpdateOne {
	if v != nil {
		_u.SetExpectedRr(*v)
	}
	return _u
}

// AddExpectedRr adds value to the "expected_rr" field.
func (_u *PositionUpdateOne) AddExpectedRr(v float64) *PositionUpdateOne {
	_u.mutation.AddExpectedRr(v)
	return _u
}

// SetRealizedPnl sets the "realized_pnl" field.
func (_u *PositionUpdateOne) SetRealizedPnl(v float64) *PositionUpdateOne {
	_u.mutation.ResetRealizedPnl()
	_u.mutation.SetRealizedPnl(v)
	return _u
}

// SetNillableRealizedPnl sets the "realized_pnl" field if the given value is not nil.
func (_u *PositionUpdateOne) SetNillableRealizedPnl(v *float64) *PositionUpdateOne {
	if v != nil {
		_u.SetRealizedPnl(*v)
	}
	return _u
}

// AddRealizedPnl adds value to the "realized_pnl" field.
func (_u *PositionUpdateOne) AddRealizedPnl(v float64) *PositionUpdateOne {
	_u.mutation.AddRealizedPnl(v)
	return _u
}

// SetUnrealizedPnl sets the "unrealized_pnl" field.
func (_u *PositionUpdateOne) SetUnrealizedPnl(v float64) *PositionUpdateOne {
	_u.mutation.ResetUnrealizedPnl()
	_u.mutation.SetUnrealizedPnl(v)
	return _u
}

// SetNillableUnrealizedPnl sets the "unrealized_pnl" field if the given value is not nil.
func (_u *PositionUpdateOne) SetNillableUnrealizedPnl(v *float64) *PositionUpdateOne {
	if v != nil {
		_u.SetUnrealizedPnl(*v)
	}
	return _u
}

// AddUnrealizedPnl adds value to the "unrealized_pnl" field.
func (_u *PositionUpdateOne) AddUnrealizedPnl(v float64) *PositionUpdateOne {
	_u.mutation.AddUnrealizedPnl(v)
	return _u
}

// SetClosePrice sets the "close_price" field.
func (_u *PositionUpdateOne) SetClosePrice(v float64) *PositionUpdateOne {
	_u.mutation.ResetClosePrice()
	_u.mutation.SetClosePrice(v)
	return _u
}

// SetNillableClosePrice sets the "close_price" field if the given value is not nil.
func (_u *PositionUpdateOne) SetNillableClosePrice(v *float64) *PositionUpdateOne {
	if v != nil {
		_u.SetClosePrice(*v)
	}
	return _u
}

// AddClosePrice adds value to the "close_price" field.
func (_u *PositionUpdateOne) AddClosePrice(v float64) *PositionUpdateOne {
	_u.mutation.AddClosePrice(v)
	return _u
}

// ClearClosePrice clears the value of the "close_price" field.
func (_u *PositionUpdateOne) ClearClosePrice() *PositionUpdateOne {
	_u.mutation.ClearClosePrice()
	return _u
}

// SetCloseTime sets the "close_time" field.
func (_u *PositionUpdateOne) SetCloseTime(v time.Time) *PositionUpdateOne {
	_u.mutation.SetCloseTime(v)
	return _u
}

// SetNillableCloseTime sets the "close_time" field if the given value is not nil.
func (_u *PositionUpdateOne) SetNillableCloseTime(v *time.Time) *PositionUpdateOne {
	if v != nil {
		_u.SetCloseTime(*v)
	}
	return _u
}

// ClearCloseTime clears the value of the "close_time" field.
func (_u *PositionUpdateOne) ClearCloseTime() *PositionUpdateOne {
	_u.mutation.ClearCloseTime()
	return _u
}

// SetCloseReason sets the "close_reason" field.
func (_u *PositionUpdateOne) SetCloseReason(v string) *PositionUpdateOne {
	_u.mutation.SetCloseReason(v)
	return _u
}

// SetNillableCloseReason sets the "close_reason" field if the given value is not nil.
func (_u *PositionUpdateOne) SetNillableCloseReason(v *string) *PositionUpdateOne {
	if v != nil {
		_u.SetCloseReason(*v)
	}
	return _u
}

// ClearCloseReason clears the value of the "close_reason" field.
func (_u *PositionUpdateOne) ClearCloseReason() *PositionUpdateOne {
	_u.mutation.ClearCloseReason()
	return _u
}

// SetLinkedPredictionID sets the "linked_prediction_id" field.
func (_u *PositionUpdateOne) SetLinkedPredictionID(v int) *PositionUpdateOne {
	_u.mutation.ResetLinkedPredictionID()
	_u.mutation.SetLinkedPredictionID(v)
	return _u
}

// SetNillableLinkedPredictionID sets the "linked_prediction_id" field if the given value is not nil.
func (_u *PositionUpdateOne) SetNillableLinkedPredictionID(v *int) *PositionUpdateOne {
	if v != nil {
		_u.SetLinkedPredictionID(*v)
	}
	return _u
}

// AddLinkedPredictionID adds value to the "linked_prediction_id" field.
func (_u *PositionUpdateOne) AddLinkedPredictionID(v int) *PositionUpdateOne {
	_u.mutation.AddLinkedPredictionID(v)
	return _u
}

// ClearLinkedPredictionID clears the value of the "linked_prediction_id" field.
func (_u *PositionUpdateOne) ClearLinkedPredictionID() *PositionUpdateOne {
	_u.mutation.ClearLinkedPredictionID()
	return _u
}

// SetInvalidationLevel sets the "invalidation_level" field.
func (_u *PositionUpdateOne) SetInvalidationLevel(v float64) *PositionUpdateOne {
	_u.mutation.ResetInvalidationLevel()
	_u.mutation.SetInvalidationLevel(v)
	return _u
}

// SetNillableInvalidationLevel sets the "invalidation_level" field if the given value is not nil.
func (_u *PositionUpdateOne) SetNillableInvalidationLevel(v *float64) *PositionUpdateOne {
	if v != nil {
		_u.SetInvalidationLevel(*v)
	}
	return _u
}

// AddInvalidationLevel adds value to the "invalidation_level" field.
func (_u *PositionUpdateOne) AddInvalidationLevel(v float64) *PositionUpdateOne {
	_u.mutation.AddInvalidationLevel(v)
	return _u
}

// ClearInvalidationLevel clears the value of the "invalidation_level" field.
func (_u *PositionUpdateOne) ClearInvalidationLevel() *PositionUpdateOne {
	_u.mutation.ClearInvalidationLevel()
	return _u
}

// SetTp1Hit sets the "tp1_hit" field.
func (_u *PositionUpdateOne) SetTp1Hit(v int) *PositionUpdateOne {
	_u.mutation.ResetTp1Hit()
	_u.mutation.SetTp1Hit(v)
	return _u
}

// SetNillableTp1Hit sets the "tp1_hit" field if the given value is not nil.
func (_u *PositionUpdateOne) SetNillableTp1Hit(v *int) *PositionUpdateOne {
	if v != nil {
		_u.SetTp1Hit(*v)
	}
	return _u
}

// AddTp1Hit adds value to the "tp1_hit" field.
func (_u *PositionUpdateOne) AddTp1Hit(v int) *PositionUpdateOne {
	_u.mutation.AddTp1Hit(v)
	return _u
}

// SetIctStrategy sets the "ict_strategy" field.
func (_u *PositionUpdateOne) SetIctStrategy(v string) *PositionUpdateOne {
	_u.mutation.SetIctStrategy(v)
	return _u
}

// SetNillableIctStrategy sets the "ict_strategy" field if the given value is not nil.
func (_u *PositionUpdateOne) SetNillableIctStrategy(v *string) *PositionUpdateOne {
	if v != nil {
		_u.SetIctStrategy(*v)
	}
	return _u
}

// ClearIctStrategy clears the value of the "ict_strategy" field.
func (_u *PositionUpdateOne) ClearIctStrategy() *PositionUpdateOne {
	_u.mutation.ClearIctStrategy()
	return _u
}

// SetTpLevels sets the "tp_levels" field.
func (_u *PositionUpdateOne) SetTpLevels(v string) *PositionUpdateOne {
	_u.mutation.SetTpLevels(v)
	return _u
}

// SetNillableTpLevels sets the "tp_levels" field if the given value is not nil.
func (_u *PositionUpdateOne) SetNillableTpLevels(v *string) *PositionUpdateOne {
	if v != nil {
		_u.SetTpLevels(*v)
	}
	return _u
}

// ClearTpLevels clears the value of the "tp_levels" field.
func (_u *PositionUpdateOne) ClearTpLevels() *PositionUpdateOne {
	_u.mutation.ClearTpLevels()
	return _u
}

// SetTpHitCount sets the "tp_hit_count" field.
func (_u *PositionUpdateOne) SetTpHitCount(v int) *PositionUpdateOne {
	_u.mutation.ResetTpHitCount()
	_u.mutation.SetTpHitCount(v)
	return _u
}

// SetNillableTpHitCount sets the "tp_hit_count" field if the given value is not nil.
func (_u *PositionUpdateOne) SetNillableTpHitCount(v *int) *PositionUpdateOne {
	if v != nil {
		_u.SetTpHitCount(*v)
	}
	return _u
}

// AddTpHitCount adds value to the "tp_hit_count" field.
func (_u *PositionUpdateOne) AddTpHitCount(v int) *PositionUpdateOne {
	_u.mutation.AddTpHitCount(v)
	return _u
}

// SetPartialClosed sets the "partial_closed" field.
func (_u *PositionUpdateOne) SetPartialClosed(v float64) *PositionUpdateOne {
	_u.mutation.ResetPartialClosed()
	_u.mutation.SetPartialClosed(v)
	return _u
}

// SetNillablePartialClosed sets the "partial_closed" field if the given value is not nil.
func (_u *PositionUpdateOne) SetNillablePartialClosed(v *float64) *PositionUpdateOne {
	if v != nil {
		_u.SetPartialClosed(*v)
	}
	return _u
}

// AddPartialClosed adds value to the "partial_closed" field.
func (_u *PositionUpdateOne) AddPartialClosed(v float64) *PositionUpdateOne {
	_u.mutation.AddPartialClosed(v)
	return _u
}

// SetRMultiple sets the "r_multiple" field.
func (_u *PositionUpdateOne) SetRMultiple(v float64) *PositionUpdateOne {
	_u.mutation.ResetRMultiple()
	_u.mutation.SetRMultiple(v)
	return _u
}

// SetNillableRMultiple sets the "r_multiple" field if the given value is not nil.
func (_u *PositionUpdateOne) SetNillableRMultiple(v *float64) *PositionUpdateOne {
	if v != nil {
		_u.SetRMultiple(*v)
	}
	return _u
}

// AddRMultiple adds value to the "r_multiple" field.
func (_u *PositionUpdateOne) AddRMultiple(v float64) *PositionUpdateOne {
	_u.mutation.AddRMultiple(v)
	return _u
}

// SetMethodID sets the "method_id" field.
func (_u *PositionUpdateOne) SetMethodID(v string) *PositionUpdateOne {
	_u.mutation.SetMethodID(v)
	return _u
}

// SetNillableMethodID sets the "method_id" field if the given value is not nil.
func (_u *PositionUpdateOne) SetNillableMethodID(v *string) *PositionUpdateOne {
	if v != nil {
		_u.SetMethodID(*v)
	}
	return _u
}

// ClearMethodID clears the value of the "method_id" field.
func (_u *PositionUpdateOne) ClearMethodID() *PositionUpdateOne {
	_u.mutation.ClearMethodID()
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *PositionUpdateOne) SetAccount(v *Account) *PositionUpdateOne {
	return _u.SetAccountID(v.ID)
}

// AddEventIDs adds the "events" edge to the TradeEvent entity by IDs.
func (_u *PositionUpdateOne) AddEventIDs(ids ...int) *PositionUpdateOne {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the TradeEvent entity.
func (_u *PositionUpdateOne) AddEvents(v ...*TradeEvent) *PositionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// Mutation returns the PositionMutation object of the builder.
func (_u *PositionUpdateOne) Mutation() *PositionMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *PositionUpdateOne) ClearAccount() *PositionUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// ClearEvents clears all "events" edges to the TradeEvent entity.
func (_u *PositionUpdateOne) ClearEvents() *PositionUpdateOne {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to TradeEvent entities by IDs.
func (_u *PositionUpdateOne) RemoveEventIDs(ids ...int) *PositionUpdateOne {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to TradeEvent entities.
func (_u *PositionUpdateOne) RemoveEvents(v ...*TradeEvent) *PositionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// Where appends a list predicates to the PositionUpdate builder.
func (_u *PositionUpdateOne) Where(ps ...predicate.Position) *PositionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PositionUpdateOne) Select(field string, fields ...string) *PositionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Position entity.
func (_u *PositionUpdateOne) Save(ctx context.Context) (*Position, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PositionUpdateOne) SaveX(ctx context.Context) *Position {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PositionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PositionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PositionUpdateOne) check() error {
	if v, ok := _u.mutation.PositionID(); ok {
		if err := position.PositionIDValidator(v); err != nil {
			return &ValidationError{Name: "position_id", err: fmt.Errorf(`ent: validator failed for field "Position.position_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Symbol(); ok {
		if err := position.SymbolValidator(v); err != nil {
			return &ValidationError{Name: "symbol", err: fmt.Errorf(`ent: validator failed for field "Position.symbol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Side(); ok {
		if err := position.SideValidator(v); err != nil {
			return &ValidationError{Name: "side", err: fmt.Errorf(`ent: validator failed for field "Position.side": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := position.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Position.status": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Position.account"`)
	}
	return nil
}

func (_u *PositionUpdateOne) sqlSave(ctx context.Context) (_node *Position, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(position.Table, position.Columns, sqlgraph.NewFieldSpec(position.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Position.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, position.FieldID)
		for _, f := range fields {
			if !position.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != position.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PositionID(); ok {
		_spec.SetField(position.FieldPositionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Symbol(); ok {
		_spec.SetField(position.FieldSymbol, field.TypeString, value)
	}
	if value, ok := _u.mutation.Side(); ok {
		_spec.SetField(position.FieldSide, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntryPrice(); ok {
		_spec.SetField(position.FieldEntryPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEntryPrice(); ok {
		_spec.AddField(position.FieldEntryPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CurrentPrice(); ok {
		_spec.SetField(position.FieldCurrentPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCurrentPrice(); ok {
		_spec.AddField(position.FieldCurrentPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.StopLoss(); ok {
		_spec.SetField(position.FieldStopLoss, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedStopLoss(); ok {
		_spec.AddField(position.FieldStopLoss, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TakeProfit(); ok {
		_spec.SetField(position.FieldTakeProfit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTakeProfit(); ok {
		_spec.AddField(position.FieldTakeProfit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(position.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeUsd(); ok {
		_spec.SetField(position.FieldSizeUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSizeUsd(); ok {
		_spec.AddField(position.FieldSizeUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SizeQty(); ok {
		_spec.SetField(position.FieldSizeQty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSizeQty(); ok {
		_spec.AddField(position.FieldSizeQty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RiskUsd(); ok {
		_spec.SetField(position.FieldRiskUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRiskUsd(); ok {
		_spec.AddField(position.FieldRiskUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RiskPercent(); ok {
		_spec.SetField(position.FieldRiskPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRiskPercent(); ok {
		_spec.AddField(position.FieldRiskPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ExpectedRr(); ok {
		_spec.SetField(position.FieldExpectedRr, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedExpectedRr(); ok {
		_spec.AddField(position.FieldExpectedRr, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RealizedPnl(); ok {
		_spec.SetField(position.FieldRealizedPnl, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRealizedPnl(); ok {
		_spec.AddField(position.FieldRealizedPnl, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UnrealizedPnl(); ok {
		_spec.SetField(position.FieldUnrealizedPnl, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUnrealizedPnl(); ok {
		_spec.AddField(position.FieldUnrealizedPnl, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ClosePrice(); ok {
		_spec.SetField(position.FieldClosePrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedClosePrice(); ok {
		_spec.AddField(position.FieldClosePrice, field.TypeFloat64, value)
	}
	if _u.mutation.ClosePriceCleared() {
		_spec.ClearField(position.FieldClosePrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CloseTime(); ok {
		_spec.SetField(position.FieldCloseTime, field.TypeTime, value)
	}
	if _u.mutation.CloseTimeCleared() {
		_spec.ClearField(position.FieldCloseTime, field.TypeTime)
	}
	if value, ok := _u.mutation.CloseReason(); ok {
		_spec.SetField(position.FieldCloseReason, field.TypeString, value)
	}
	if _u.mutation.CloseReasonCleared() {
		_spec.ClearField(position.FieldCloseReason, field.TypeString)
	}
	if value, ok := _u.mutation.LinkedPredictionID(); ok {
		_spec.SetField(position.FieldLinkedPredictionID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLinkedPredictionID(); ok {
		_spec.AddField(position.FieldLinkedPredictionID, field.TypeInt, value)
	}
	if _u.mutation.LinkedPredictionIDCleared() {
		_spec.ClearField(position.FieldLinkedPredictionID, field.TypeInt)
	}
	if value, ok := _u.mutation.InvalidationLevel(); ok {
		_spec.SetField(position.FieldInvalidationLevel, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInvalidationLevel(); ok {
		_spec.AddField(position.FieldInvalidationLevel, field.TypeFloat64, value)
	}
	if _u.mutation.InvalidationLevelCleared() {
		_spec.ClearField(position.FieldInvalidationLevel, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Tp1Hit(); ok {
		_spec.SetField(position.FieldTp1Hit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTp1Hit(); ok {
		_spec.AddField(position.FieldTp1Hit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IctStrategy(); ok {
		_spec.SetField(position.FieldIctStrategy, field.TypeString, value)
	}
	if _u.mutation.IctStrategyCleared() {
		_spec.ClearField(position.FieldIctStrategy, field.TypeString)
	}
	if value, ok := _u.mutation.TpLevels(); ok {
		_spec.SetField(position.FieldTpLevels, field.TypeString, value)
	}
	if _u.mutation.TpLevelsCleared() {
		_spec.ClearField(position.FieldTpLevels, field.TypeString)
	}
	if value, ok := _u.mutation.TpHitCount(); ok {
		_spec.SetField(position.FieldTpHitCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTpHitCount(); ok {
		_spec.AddField(position.FieldTpHitCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PartialClosed(); ok {
		_spec.SetField(position.FieldPartialClosed, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPartialClosed(); ok {
		_spec.AddField(position.FieldPartialClosed, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RMultiple(); ok {
		_spec.SetField(position.FieldRMultiple, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRMultiple(); ok {
		_spec.AddField(position.FieldRMultiple, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MethodID(); ok {
		_spec.SetField(position.FieldMethodID, field.TypeString, value)
	}
	if _u.mutation.MethodIDCleared() {
		_spec.ClearField(position.FieldMethodID, field.TypeString)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   position.AccountTable,
			Columns: []string{position.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   position.AccountTable,
			Columns: []string{position.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.EventsTable,
			Columns: []string{position.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tradeevent.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.EventsTable,
			Columns: []string{position.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tradeevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.EventsTable,
			Columns: []string{position.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tradeevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Position{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{position.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
