// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/chuyen-gia-crypto/backend/internal/db/ent/account"
	"github.com/chuyen-gia-crypto/backend/internal/db/ent/position"
)

// Position is the model entity for the Position schema.
type Position struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// PositionID holds the value of the "position_id" field.
	PositionID string `json:"position_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int `json:"account_id,omitempty"`
	// Symbol holds the value of the "symbol" field.
	Symbol string `json:"symbol,omitempty"`
	// Side holds the value of the "side" field.
	Side string `json:"side,omitempty"`
	// EntryPrice holds the value of the "entry_price" field.
	EntryPrice float64 `json:"entry_price,omitempty"`
	// CurrentPrice holds the value of the "current_price" field.
	CurrentPrice float64 `json:"current_price,omitempty"`
	// StopLoss holds the value of the "stop_loss" field.
	StopLoss float64 `json:"stop_loss,omitempty"`
	// TakeProfit holds the value of the "take_profit" field.
	TakeProfit float64 `json:"take_profit,omitempty"`
	// EntryTime holds the value of the "entry_time" field.
	EntryTime time.Time `json:"entry_time,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// SizeUsd holds the value of the "size_usd" field.
	SizeUsd float64 `json:"size_usd,omitempty"`
	// SizeQty holds the value of the "size_qty" field.
	SizeQty float64 `json:"size_qty,omitempty"`
	// RiskUsd holds the value of the "risk_usd" field.
	RiskUsd float64 `json:"risk_usd,omitempty"`
	// RiskPercent holds the value of the "risk_percent" field.
	RiskPercent float64 `json:"risk_percent,omitempty"`
	// ExpectedRr holds the value of the "expected_rr" field.
	ExpectedRr float64 `json:"expected_rr,omitempty"`
	// RealizedPnl holds the value of the "realized_pnl" field.
	RealizedPnl float64 `json:"realized_pnl,omitempty"`
	// UnrealizedPnl holds the value of the "unrealized_pnl" field.
	UnrealizedPnl float64 `json:"unrealized_pnl,omitempty"`
	// ClosePrice holds the value of the "close_price" field.
	ClosePrice *float64 `json:"close_price,omitempty"`
	// CloseTime holds the value of the "close_time" field.
	CloseTime *time.Time `json:"close_time,omitempty"`
	// CloseReason holds the value of the "close_reason" field.
	CloseReason *string `json:"close_reason,omitempty"`
	// LinkedPredictionID holds the value of the "linked_prediction_id" field.
	LinkedPredictionID *int `json:"linked_prediction_id,omitempty"`
	// InvalidationLevel holds the value of the "invalidation_level" field.
	InvalidationLevel *float64 `json:"invalidation_level,omitempty"`
	// Tp1Hit holds the value of the "tp1_hit" field.
	Tp1Hit int `json:"tp1_hit,omitempty"`
	// IctStrategy holds the value of the "ict_strategy" field.
	IctStrategy string `json:"ict_strategy,omitempty"`
	// TpLevels holds the value of the "tp_levels" field.
	TpLevels string `json:"tp_levels,omitempty"`
	// TpHitCount holds the value of the "tp_hit_count" field.
	TpHitCount int `json:"tp_hit_count,omitempty"`
	// PartialClosed holds the value of the "partial_closed" field.
	PartialClosed float64 `json:"partial_closed,omitempty"`
	// RMultiple holds the value of the "r_multiple" field.
	RMultiple float64 `json:"r_multiple,omitempty"`
	// MethodID holds the value of the "method_id" field.
	MethodID string `json:"method_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PositionQuery when eager-loading is set.
	Edges        PositionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PositionEdges holds the relations/edges for other nodes in the graph.
type PositionEdges struct {
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// Events holds the value of the events edge.
	Events []*TradeEvent `json:"events,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PositionEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// EventsOrErr returns the Events value or an error if the edge
// was not loaded in eager-loading.
func (e PositionEdges) EventsOrErr() ([]*TradeEvent, error) {
	if e.loadedTypes[1] {
		return e.Events, nil
	}
	return nil, &NotLoadedError{edge: "events"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Position) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case position.FieldEntryPrice, position.FieldCurrentPrice, position.FieldStopLoss, position.FieldTakeProfit, position.FieldSizeUsd, position.FieldSizeQty, position.FieldRiskUsd, position.FieldRiskPercent, position.FieldExpectedRr, position.FieldRealizedPnl, position.FieldUnrealizedPnl, position.FieldClosePrice, position.FieldInvalidationLevel, position.FieldPartialClosed, position.FieldRMultiple:
			values[i] = new(sql.NullFloat64)
		case position.FieldID, position.FieldAccountID, position.FieldLinkedPredictionID, position.FieldTp1Hit, position.FieldTpHitCount:
			values[i] = new(sql.NullInt64)
		case position.FieldPositionID, position.FieldSymbol, position.FieldSide, position.FieldStatus, position.FieldCloseReason, position.FieldIctStrategy, position.FieldTpLevels, position.FieldMethodID:
			values[i] = new(sql.NullString)
		case position.FieldEntryTime, position.FieldCloseTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Position fields.
func (_m *Position) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case position.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case position.FieldPositionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field position_id", values[i])
			} else if value.Valid {
				_m.PositionID = value.String
			}
		case position.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = int(value.Int64)
			}
		case position.FieldSymbol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field symbol", values[i])
			} else if value.Valid {
				_m.Symbol = value.String
			}
		case position.FieldSide:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field side", values[i])
			} else if value.Valid {
				_m.Side = value.String
			}
		case position.FieldEntryPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field entry_price", values[i])
			} else if value.Valid {
				_m.EntryPrice = value.Float64
			}
		case position.FieldCurrentPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field current_price", values[i])
			} else if value.Valid {
				_m.CurrentPrice = value.Float64
			}
		case position.FieldStopLoss:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field stop_loss", values[i])
			} else if value.Valid {
				_m.StopLoss = value.Float64
			}
		case position.FieldTakeProfit:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field take_profit", values[i])
			} else if value.Valid {
				_m.TakeProfit = value.Float64
			}
		case position.FieldEntryTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field entry_time", values[i])
			} else if value.Valid {
				_m.EntryTime = value.Time
			}
		case position.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case position.FieldSizeUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field size_usd", values[i])
			} else if value.Valid {
				_m.SizeUsd = value.Float64
			}
		case position.FieldSizeQty:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field size_qty", values[i])
			} else if value.Valid {
				_m.SizeQty = value.Float64
			}
		case position.FieldRiskUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field risk_usd", values[i])
			} else if value.Valid {
				_m.RiskUsd = value.Float64
			}
		case position.FieldRiskPercent:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field risk_percent", values[i])
			} else if value.Valid {
				_m.RiskPercent = value.Float64
			}
		case position.FieldExpectedRr:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field expected_rr", values[i])
			} else if value.Valid {
				_m.ExpectedRr = value.Float64
			}
		case position.FieldRealizedPnl:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field realized_pnl", values[i])
			} else if value.Valid {
				_m.RealizedPnl = value.Float64
			}
		case position.FieldUnrealizedPnl:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field unrealized_pnl", values[i])
			} else if value.Valid {
				_m.UnrealizedPnl = value.Float64
			}
		case position.FieldClosePrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field close_price", values[i])
			} else if value.Valid {
				_m.ClosePrice = new(float64)
				*_m.ClosePrice = value.Float64
			}
		case position.FieldCloseTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field close_time", values[i])
			} else if value.Valid {
				_m.CloseTime = new(time.Time)
				*_m.CloseTime = value.Time
			}
		case position.FieldCloseReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field close_reason", values[i])
			} else if value.Valid {
				_m.CloseReason = new(string)
				*_m.CloseReason = value.String
			}
		case position.FieldLinkedPredictionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field linked_prediction_id", values[i])
			} else if value.Valid {
				_m.LinkedPredictionID = new(int)
				*_m.LinkedPredictionID = int(value.Int64)
			}
		case position.FieldInvalidationLevel:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field invalidation_level", values[i])
			} else if value.Valid {
				_m.InvalidationLevel = new(float64)
				*_m.InvalidationLevel = value.Float64
			}
		case position.FieldTp1Hit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tp1_hit", values[i])
			} else if value.Valid {
				_m.Tp1Hit = int(value.Int64)
			}
		case position.FieldIctStrategy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ict_strategy", values[i])
			} else if value.Valid {
				_m.IctStrategy = value.String
			}
		case position.FieldTpLevels:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tp_levels", values[i])
			} else if value.Valid {
				_m.TpLevels = value.String
			}
		case position.FieldTpHitCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tp_hit_count", values[i])
			} else if value.Valid {
				_m.TpHitCount = int(value.Int64)
			}
		case position.FieldPartialClosed:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field partial_closed", values[i])
			} else if value.Valid {
				_m.PartialClosed = value.Float64
			}
		case position.FieldRMultiple:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field r_multiple", values[i])
			} else if value.Valid {
				_m.RMultiple = value.Float64
			}
		case position.FieldMethodID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field method_id", values[i])
			} else if value.Valid {
				_m.MethodID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Position.
// This includes values selected through modifiers, order, etc.
func (_m *Position) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccount queries the "account" edge of the Position entity.
func (_m *Position) QueryAccount() *AccountQuery {
	return NewPositionClient(_m.config).QueryAccount(_m)
}

// QueryEvents queries the "events" edge of the Position entity.
func (_m *Position) QueryEvents() *TradeEventQuery {
	return NewPositionClient(_m.config).QueryEvents(_m)
}

// Update returns a builder for updating this Position.
// Note that you need to call Position.Unwrap() before calling this method if this Position
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Position) Update() *PositionUpdateOne {
	return NewPositionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Position entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Position) Unwrap() *Position {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Position is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Position) String() string {
	var builder strings.Builder
	builder.WriteString("Position(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("position_id=")
	builder.WriteString(_m.PositionID)
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("symbol=")
	builder.WriteString(_m.Symbol)
	builder.WriteString(", ")
	builder.WriteString("side=")
	builder.WriteString(_m.Side)
	builder.WriteString(", ")
	builder.WriteString("entry_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.EntryPrice))
	builder.WriteString(", ")
	builder.WriteString("current_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.CurrentPrice))
	builder.WriteString(", ")
	builder.WriteString("stop_loss=")
	builder.WriteString(fmt.Sprintf("%v", _m.StopLoss))
	builder.WriteString(", ")
	builder.WriteString("take_profit=")
	builder.WriteString(fmt.Sprintf("%v", _m.TakeProfit))
	builder.WriteString(", ")
	builder.WriteString("entry_time=")
	builder.WriteString(_m.EntryTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("size_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.SizeUsd))
	builder.WriteString(", ")
	builder.WriteString("size_qty=")
	builder.WriteString(fmt.Sprintf("%v", _m.SizeQty))
	builder.WriteString(", ")
	builder.WriteString("risk_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.RiskUsd))
	builder.WriteString(", ")
	builder.WriteString("risk_percent=")
	builder.WriteString(fmt.Sprintf("%v", _m.RiskPercent))
	builder.WriteString(", ")
	builder.WriteString("expected_rr=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExpectedRr))
	builder.WriteString(", ")
	builder.WriteString("realized_pnl=")
	builder.WriteString(fmt.Sprintf("%v", _m.RealizedPnl))
	builder.WriteString(", ")
	builder.WriteString("unrealized_pnl=")
	builder.WriteString(fmt.Sprintf("%v", _m.UnrealizedPnl))
	builder.WriteString(", ")
	if v := _m.ClosePrice; v != nil {
		builder.WriteString("close_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CloseTime; v != nil {
		builder.WriteString("close_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CloseReason; v != nil {
		builder.WriteString("close_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LinkedPredictionID; v != nil {
		builder.WriteString("linked_prediction_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.InvalidationLevel; v != nil {
		builder.WriteString("invalidation_level=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("tp1_hit=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tp1Hit))
	builder.WriteString(", ")
	builder.WriteString("ict_strategy=")
	builder.WriteString(_m.IctStrategy)
	builder.WriteString(", ")
	builder.WriteString("tp_levels=")
	builder.WriteString(_m.TpLevels)
	builder.WriteString(", ")
	builder.WriteString("tp_hit_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.TpHitCount))
	builder.WriteString(", ")
	builder.WriteString("partial_closed=")
	builder.WriteString(fmt.Sprintf("%v", _m.PartialClosed))
	builder.WriteString(", ")
	builder.WriteString("r_multiple=")
	builder.WriteString(fmt.Sprintf("%v", _m.RMultiple))
	builder.WriteString(", ")
	builder.WriteString("method_id=")
	builder.WriteString(_m.MethodID)
	builder.WriteByte(')')
	return builder.String()
}

// Positions is a parsable slice of Position.
type Positions []*Position
