// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/chuyen-gia-crypto/backend/internal/db/ent/testnetposition"
	"github.com/chuyen-gia-crypto/backend/internal/db/ent/testnettradeevent"
)

// TestnetTradeEventCreate is the builder for creating a TestnetTradeEvent entity.
type TestnetTradeEventCreate struct {
	config
	mutation *TestnetTradeEventMutation
	hooks    []Hook
}

// SetPositionID sets the "position_id" field.
func (_c *TestnetTradeEventCreate) SetPositionID(v int) *TestnetTradeEventCreate {
	_c.mutation.SetPositionID(v)
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *TestnetTradeEventCreate) SetEventType(v string) *TestnetTradeEventCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetEventData sets the "event_data" field.
func (_c *TestnetTradeEventCreate) SetEventData(v string) *TestnetTradeEventCreate {
	_c.mutation.SetEventData(v)
	return _c
}

// SetNillableEventData sets the "event_data" field if the given value is not nil.
func (_c *TestnetTradeEventCreate) SetNillableEventData(v *string) *TestnetTradeEventCreate {
	if v != nil {
		_c.SetEventData(*v)
	}
	return _c
}

// SetTimestamp sets the "timestamp" field.
func (_c *TestnetTradeEventCreate) SetTimestamp(v time.Time) *TestnetTradeEventCreate {
	_c.mutation.SetTimestamp(v)
	return _c
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_c *TestnetTradeEventCreate) SetNillableTimestamp(v *time.Time) *TestnetTradeEventCreate {
	if v != nil {
		_c.SetTimestamp(*v)
	}
	return _c
}

// SetPosition sets the "position" edge to the TestnetPosition entity.
func (_c *TestnetTradeEventCreate) SetPosition(v *TestnetPosition) *TestnetTradeEventCreate {
	return _c.SetPositionID(v.ID)
}

// Mutation returns the TestnetTradeEventMutation object of the builder.
func (_c *TestnetTradeEventCreate) Mutation() *TestnetTradeEventMutation {
	return _c.mutation
}

// Save creates the TestnetTradeEvent in the database.
func (_c *TestnetTradeEventCreate) Save(ctx context.Context) (*TestnetTradeEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TestnetTradeEventCreate) SaveX(ctx context.Context) *TestnetTradeEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TestnetTradeEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TestnetTradeEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TestnetTradeEventCreate) defaults() {
	if _, ok := _c.mutation.Timestamp(); !ok {
		v := testnettradeevent.DefaultTimestamp()
		_c.mutation.SetTimestamp(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TestnetTradeEventCreate) check() error {
	if _, ok := _c.mutation.PositionID(); !ok {
		return &ValidationError{Name: "position_id", err: errors.New(`ent: missing required field "TestnetTradeEvent.position_id"`)}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "TestnetTradeEvent.event_type"`)}
	}
	if v, ok := _c.mutation.EventType(); ok {
		if err := testnettradeevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "TestnetTradeEvent.event_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "TestnetTradeEvent.timestamp"`)}
	}
	if len(_c.mutation.PositionIDs()) == 0 {
		return &ValidationError{Name: "position", err: errors.New(`ent: missing required edge "TestnetTradeEvent.position"`)}
	}
	return nil
}

func (_c *TestnetTradeEventCreate) sqlSave(ctx context.Context) (*TestnetTradeEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TestnetTradeEventCreate) createSpec() (*TestnetTradeEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &TestnetTradeEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(testnettradeevent.Table, sqlgraph.NewFieldSpec(testnettradeevent.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(testnettradeevent.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.EventData(); ok {
		_spec.SetField(testnettradeevent.FieldEventData, field.TypeString, value)
		_node.EventData = value
	}
	if value, ok := _c.mutation.Timestamp(); ok {
		_spec.SetField(testnettradeevent.FieldTimestamp, field.TypeTime, value)
		_node.Timestamp = value
	}
	if nodes := _c.mutation.PositionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   testnettradeevent.PositionTable,
			Columns: []string{testnettradeevent.PositionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(testnetposition.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PositionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TestnetTradeEventCreateBulk is the builder for creating many TestnetTradeEvent entities in bulk.
type TestnetTradeEventCreateBulk struct {
	config
	err      error
	builders []*TestnetTradeEventCreate
}

// Save creates the TestnetTradeEvent entities in the database.
func (_c *TestnetTradeEventCreateBulk) Save(ctx context.Context) ([]*TestnetTradeEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TestnetTradeEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TestnetTradeEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TestnetTradeEventCreateBulk) SaveX(ctx context.Context) []*TestnetTradeEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TestnetTradeEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TestnetTradeEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
