// Code generated by ent, DO NOT EDIT.

package account

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/chuyen-gia-crypto/backend/internal/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldID, id))
}

// Symbol applies equality check predicate on the "symbol" field. It's identical to SymbolEQ.
func Symbol(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldSymbol, v))
}

// MethodID applies equality check predicate on the "method_id" field. It's identical to MethodIDEQ.
func MethodID(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldMethodID, v))
}

// StartingBalance applies equality check predicate on the "starting_balance" field. It's identical to StartingBalanceEQ.
func StartingBalance(v float64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldStartingBalance, v))
}

// CurrentBalance applies equality check predicate on the "current_balance" field. It's identical to CurrentBalanceEQ.
func CurrentBalance(v float64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldCurrentBalance, v))
}

// Equity applies equality check predicate on the "equity" field. It's identical to EquityEQ.
func Equity(v float64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldEquity, v))
}

// UnrealizedPnl applies equality check predicate on the "unrealized_pnl" field. It's identical to UnrealizedPnlEQ.
func UnrealizedPnl(v float64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldUnrealizedPnl, v))
}

// RealizedPnl applies equality check predicate on the "realized_pnl" field. It's identical to RealizedPnlEQ.
func RealizedPnl(v float64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldRealizedPnl, v))
}

// TotalTrades applies equality check predicate on the "total_trades" field. It's identical to TotalTradesEQ.
func TotalTrades(v int) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldTotalTrades, v))
}

// WinningTrades applies equality check predicate on the "winning_trades" field. It's identical to WinningTradesEQ.
func WinningTrades(v int) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldWinningTrades, v))
}

// LosingTrades applies equality check predicate on the "losing_trades" field. It's identical to LosingTradesEQ.
func LosingTrades(v int) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldLosingTrades, v))
}

// MaxDrawdown applies equality check predicate on the "max_drawdown" field. It's identical to MaxDrawdownEQ.
func MaxDrawdown(v float64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldMaxDrawdown, v))
}

// ConsecutiveLosses applies equality check predicate on the "consecutive_losses" field. It's identical to ConsecutiveLossesEQ.
func ConsecutiveLosses(v int) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldConsecutiveLosses, v))
}

// LastTradeTime applies equality check predicate on the "last_trade_time" field. It's identical to LastTradeTimeEQ.
func LastTradeTime(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldLastTradeTime, v))
}

// CooldownUntil applies equality check predicate on the "cooldown_until" field. It's identical to CooldownUntilEQ.
func CooldownUntil(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldCooldownUntil, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldUpdatedAt, v))
}

// SymbolEQ applies the EQ predicate on the "symbol" field.
func SymbolEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldSymbol, v))
}

// SymbolNEQ applies the NEQ predicate on the "symbol" field.
func SymbolNEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldSymbol, v))
}

// SymbolIn applies the In predicate on the "symbol" field.
func SymbolIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldSymbol, vs...))
}

// SymbolNotIn applies the NotIn predicate on the "symbol" field.
func SymbolNotIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldSymbol, vs...))
}

// SymbolGT applies the GT predicate on the "symbol" field.
func SymbolGT(v string) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldSymbol, v))
}

// SymbolGTE applies the GTE predicate on the "symbol" field.
func SymbolGTE(v string) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldSymbol, v))
}

// SymbolLT applies the LT predicate on the "symbol" field.
func SymbolLT(v string) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldSymbol, v))
}

// SymbolLTE applies the LTE predicate on the "symbol" field.
func SymbolLTE(v string) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldSymbol, v))
}

// SymbolContains applies the Contains predicate on the "symbol" field.
func SymbolContains(v string) predicate.Account {
	return predicate.Account(sql.FieldContains(FieldSymbol, v))
}

// SymbolHasPrefix applies the HasPrefix predicate on the "symbol" field.
func SymbolHasPrefix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasPrefix(FieldSymbol, v))
}

// SymbolHasSuffix applies the HasSuffix predicate on the "symbol" field.
func SymbolHasSuffix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasSuffix(FieldSymbol, v))
}

// SymbolEqualFold applies the EqualFold predicate on the "symbol" field.
func SymbolEqualFold(v string) predicate.Account {
	return predicate.Account(sql.FieldEqualFold(FieldSymbol, v))
}

// SymbolContainsFold applies the ContainsFold predicate on the "symbol" field.
func SymbolContainsFold(v string) predicate.Account {
	return predicate.Account(sql.FieldContainsFold(FieldSymbol, v))
}

// MethodIDEQ applies the EQ predicate on the "method_id" field.
func MethodIDEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldMethodID, v))
}

// MethodIDNEQ applies the NEQ predicate on the "method_id" field.
func MethodIDNEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldMethodID, v))
}

// MethodIDIn applies the In predicate on the "method_id" field.
func MethodIDIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldMethodID, vs...))
}

// MethodIDNotIn applies the NotIn predicate on the "method_id" field.
func MethodIDNotIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldMethodID, vs...))
}

// MethodIDGT applies the GT predicate on the "method_id" field.
func MethodIDGT(v string) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldMethodID, v))
}

// MethodIDGTE applies the GTE predicate on the "method_id" field.
func MethodIDGTE(v string) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldMethodID, v))
}

// MethodIDLT applies the LT predicate on the "method_id" field.
func MethodIDLT(v string) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldMethodID, v))
}

// MethodIDLTE applies the LTE predicate on the "method_id" field.
func MethodIDLTE(v string) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldMethodID, v))
}

// MethodIDContains applies the Contains predicate on the "method_id" field.
func MethodIDContains(v string) predicate.Account {
	return predicate.Account(sql.FieldContains(FieldMethodID, v))
}

// MethodIDHasPrefix applies the HasPrefix predicate on the "method_id" field.
func MethodIDHasPrefix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasPrefix(FieldMethodID, v))
}

// MethodIDHasSuffix applies the HasSuffix predicate on the "method_id" field.
func MethodIDHasSuffix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasSuffix(FieldMethodID, v))
}

// MethodIDEqualFold applies the EqualFold predicate on the "method_id" field.
func MethodIDEqualFold(v string) predicate.Account {
	return predicate.Account(sql.FieldEqualFold(FieldMethodID, v))
}

// MethodIDContainsFold applies the ContainsFold predicate on the "method_id" field.
func MethodIDContainsFold(v string) predicate.Account {
	return predicate.Account(sql.FieldContainsFold(FieldMethodID, v))
}

// StartingBalanceEQ applies the EQ predicate on the "starting_balance" field.
func StartingBalanceEQ(v float64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldStartingBalance, v))
}

// StartingBalanceNEQ applies the NEQ predicate on the "starting_balance" field.
func StartingBalanceNEQ(v float64) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldStartingBalance, v))
}

// StartingBalanceIn applies the In predicate on the "starting_balance" field.
func StartingBalanceIn(vs ...float64) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldStartingBalance, vs...))
}

// StartingBalanceNotIn applies the NotIn predicate on the "starting_balance" field.
func StartingBalanceNotIn(vs ...float64) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldStartingBalance, vs...))
}

// StartingBalanceGT applies the GT predicate on the "starting_balance" field.
func StartingBalanceGT(v float64) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldStartingBalance, v))
}

// StartingBalanceGTE applies the GTE predicate on the "starting_balance" field.
func StartingBalanceGTE(v float64) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldStartingBalance, v))
}

// StartingBalanceLT applies the LT predicate on the "starting_balance" field.
func StartingBalanceLT(v float64) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldStartingBalance, v))
}

// StartingBalanceLTE applies the LTE predicate on the "starting_balance" field.
func StartingBalanceLTE(v float64) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldStartingBalance, v))
}

// CurrentBalanceEQ applies the EQ predicate on the "current_balance" field.
func CurrentBalanceEQ(v float64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldCurrentBalance, v))
}

// CurrentBalanceNEQ applies the NEQ predicate on the "current_balance" field.
func CurrentBalanceNEQ(v float64) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldCurrentBalance, v))
}

// CurrentBalanceIn applies the In predicate on the "current_balance" field.
func CurrentBalanceIn(vs ...float64) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldCurrentBalance, vs...))
}

// CurrentBalanceNotIn applies the NotIn predicate on the "current_balance" field.
func CurrentBalanceNotIn(vs ...float64) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldCurrentBalance, vs...))
}

// CurrentBalanceGT applies the GT predicate on the "current_balance" field.
func CurrentBalanceGT(v float64) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldCurrentBalance, v))
}

// CurrentBalanceGTE applies the GTE predicate on the "current_balance" field.
func CurrentBalanceGTE(v float64) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldCurrentBalance, v))
}

// CurrentBalanceLT applies the LT predicate on the "current_balance" field.
func CurrentBalanceLT(v float64) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldCurrentBalance, v))
}

// CurrentBalanceLTE applies the LTE predicate on the "current_balance" field.
func CurrentBalanceLTE(v float64) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldCurrentBalance, v))
}

// EquityEQ applies the EQ predicate on the "equity" field.
func EquityEQ(v float64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldEquity, v))
}

// EquityNEQ applies the NEQ predicate on the "equity" field.
func EquityNEQ(v float64) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldEquity, v))
}

// EquityIn applies the In predicate on the "equity" field.
func EquityIn(vs ...float64) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldEquity, vs...))
}

// EquityNotIn applies the NotIn predicate on the "equity" field.
func EquityNotIn(vs ...float64) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldEquity, vs...))
}

// EquityGT applies the GT predicate on the "equity" field.
func EquityGT(v float64) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldEquity, v))
}

// EquityGTE applies the GTE predicate on the "equity" field.
func EquityGTE(v float64) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldEquity, v))
}

// EquityLT applies the LT predicate on the "equity" field.
func EquityLT(v float64) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldEquity, v))
}

// EquityLTE applies the LTE predicate on the "equity" field.
func EquityLTE(v float64) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldEquity, v))
}

// UnrealizedPnlEQ applies the EQ predicate on the "unrealized_pnl" field.
func UnrealizedPnlEQ(v float64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldUnrealizedPnl, v))
}

// UnrealizedPnlNEQ applies the NEQ predicate on the "unrealized_pnl" field.
func UnrealizedPnlNEQ(v float64) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldUnrealizedPnl, v))
}

// UnrealizedPnlIn applies the In predicate on the "unrealized_pnl" field.
func UnrealizedPnlIn(vs ...float64) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldUnrealizedPnl, vs...))
}

// UnrealizedPnlNotIn applies the NotIn predicate on the "unrealized_pnl" field.
func UnrealizedPnlNotIn(vs ...float64) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldUnrealizedPnl, vs...))
}

// UnrealizedPnlGT applies the GT predicate on the "unrealized_pnl" field.
func UnrealizedPnlGT(v float64) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldUnrealizedPnl, v))
}

// UnrealizedPnlGTE applies the GTE predicate on the "unrealized_pnl" field.
func UnrealizedPnlGTE(v float64) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldUnrealizedPnl, v))
}

// UnrealizedPnlLT applies the LT predicate on the "unrealized_pnl" field.
func UnrealizedPnlLT(v float64) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldUnrealizedPnl, v))
}

// UnrealizedPnlLTE applies the LTE predicate on the "unrealized_pnl" field.
func UnrealizedPnlLTE(v float64) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldUnrealizedPnl, v))
}

// RealizedPnlEQ applies the EQ predicate on the "realized_pnl" field.
func RealizedPnlEQ(v float64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldRealizedPnl, v))
}

// RealizedPnlNEQ applies the NEQ predicate on the "realized_pnl" field.
func RealizedPnlNEQ(v float64) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldRealizedPnl, v))
}

// RealizedPnlIn applies the In predicate on the "realized_pnl" field.
func RealizedPnlIn(vs ...float64) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldRealizedPnl, vs...))
}

// RealizedPnlNotIn applies the NotIn predicate on the "realized_pnl" field.
func RealizedPnlNotIn(vs ...float64) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldRealizedPnl, vs...))
}

// RealizedPnlGT applies the GT predicate on the "realized_pnl" field.
func RealizedPnlGT(v float64) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldRealizedPnl, v))
}

// RealizedPnlGTE applies the GTE predicate on the "realized_pnl" field.
func RealizedPnlGTE(v float64) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldRealizedPnl, v))
}

// RealizedPnlLT applies the LT predicate on the "realized_pnl" field.
func RealizedPnlLT(v float64) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldRealizedPnl, v))
}

// RealizedPnlLTE applies the LTE predicate on the "realized_pnl" field.
func RealizedPnlLTE(v float64) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldRealizedPnl, v))
}

// TotalTradesEQ applies the EQ predicate on the "total_trades" field.
func TotalTradesEQ(v int) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldTotalTrades, v))
}

// TotalTradesNEQ applies the NEQ predicate on the "total_trades" field.
func TotalTradesNEQ(v int) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldTotalTrades, v))
}

// TotalTradesIn applies the In predicate on the "total_trades" field.
func TotalTradesIn(vs ...int) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldTotalTrades, vs...))
}

// TotalTradesNotIn applies the NotIn predicate on the "total_trades" field.
func TotalTradesNotIn(vs ...int) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldTotalTrades, vs...))
}

// TotalTradesGT applies the GT predicate on the "total_trades" field.
func TotalTradesGT(v int) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldTotalTrades, v))
}

// TotalTradesGTE applies the GTE predicate on the "total_trades" field.
func TotalTradesGTE(v int) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldTotalTrades, v))
}

// TotalTradesLT applies the LT predicate on the "total_trades" field.
func TotalTradesLT(v int) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldTotalTrades, v))
}

// TotalTradesLTE applies the LTE predicate on the "total_trades" field.
func TotalTradesLTE(v int) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldTotalTrades, v))
}

// WinningTradesEQ applies the EQ predicate on the "winning_trades" field.
func WinningTradesEQ(v int) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldWinningTrades, v))
}

// WinningTradesNEQ applies the NEQ predicate on the "winning_trades" field.
func WinningTradesNEQ(v int) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldWinningTrades, v))
}

// WinningTradesIn applies the In predicate on the "winning_trades" field.
func WinningTradesIn(vs ...int) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldWinningTrades, vs...))
}

// WinningTradesNotIn applies the NotIn predicate on the "winning_trades" field.
func WinningTradesNotIn(vs ...int) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldWinningTrades, vs...))
}

// WinningTradesGT applies the GT predicate on the "winning_trades" field.
func WinningTradesGT(v int) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldWinningTrades, v))
}

// WinningTradesGTE applies the GTE predicate on the "winning_trades" field.
func WinningTradesGTE(v int) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldWinningTrades, v))
}

// WinningTradesLT applies the LT predicate on the "winning_trades" field.
func WinningTradesLT(v int) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldWinningTrades, v))
}

// WinningTradesLTE applies the LTE predicate on the "winning_trades" field.
func WinningTradesLTE(v int) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldWinningTrades, v))
}

// LosingTradesEQ applies the EQ predicate on the "losing_trades" field.
func LosingTradesEQ(v int) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldLosingTrades, v))
}

// LosingTradesNEQ applies the NEQ predicate on the "losing_trades" field.
func LosingTradesNEQ(v int) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldLosingTrades, v))
}

// LosingTradesIn applies the In predicate on the "losing_trades" field.
func LosingTradesIn(vs ...int) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldLosingTrades, vs...))
}

// LosingTradesNotIn applies the NotIn predicate on the "losing_trades" field.
func LosingTradesNotIn(vs ...int) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldLosingTrades, vs...))
}

// LosingTradesGT applies the GT predicate on the "losing_trades" field.
func LosingTradesGT(v int) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldLosingTrades, v))
}

// LosingTradesGTE applies the GTE predicate on the "losing_trades" field.
func LosingTradesGTE(v int) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldLosingTrades, v))
}

// LosingTradesLT applies the LT predicate on the "losing_trades" field.
func LosingTradesLT(v int) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldLosingTrades, v))
}

// LosingTradesLTE applies the LTE predicate on the "losing_trades" field.
func LosingTradesLTE(v int) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldLosingTrades, v))
}

// MaxDrawdownEQ applies the EQ predicate on the "max_drawdown" field.
func MaxDrawdownEQ(v float64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldMaxDrawdown, v))
}

// MaxDrawdownNEQ applies the NEQ predicate on the "max_drawdown" field.
func MaxDrawdownNEQ(v float64) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldMaxDrawdown, v))
}

// MaxDrawdownIn applies the In predicate on the "max_drawdown" field.
func MaxDrawdownIn(vs ...float64) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldMaxDrawdown, vs...))
}

// MaxDrawdownNotIn applies the NotIn predicate on the "max_drawdown" field.
func MaxDrawdownNotIn(vs ...float64) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldMaxDrawdown, vs...))
}

// MaxDrawdownGT applies the GT predicate on the "max_drawdown" field.
func MaxDrawdownGT(v float64) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldMaxDrawdown, v))
}

// MaxDrawdownGTE applies the GTE predicate on the "max_drawdown" field.
func MaxDrawdownGTE(v float64) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldMaxDrawdown, v))
}

// MaxDrawdownLT applies the LT predicate on the "max_drawdown" field.
func MaxDrawdownLT(v float64) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldMaxDrawdown, v))
}

// MaxDrawdownLTE applies the LTE predicate on the "max_drawdown" field.
func MaxDrawdownLTE(v float64) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldMaxDrawdown, v))
}

// ConsecutiveLossesEQ applies the EQ predicate on the "consecutive_losses" field.
func ConsecutiveLossesEQ(v int) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldConsecutiveLosses, v))
}

// ConsecutiveLossesNEQ applies the NEQ predicate on the "consecutive_losses" field.
func ConsecutiveLossesNEQ(v int) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldConsecutiveLosses, v))
}

// ConsecutiveLossesIn applies the In predicate on the "consecutive_losses" field.
func ConsecutiveLossesIn(vs ...int) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldConsecutiveLosses, vs...))
}

// ConsecutiveLossesNotIn applies the NotIn predicate on the "consecutive_losses" field.
func ConsecutiveLossesNotIn(vs ...int) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldConsecutiveLosses, vs...))
}

// ConsecutiveLossesGT applies the GT predicate on the "consecutive_losses" field.
func ConsecutiveLossesGT(v int) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldConsecutiveLosses, v))
}

// ConsecutiveLossesGTE applies the GTE predicate on the "consecutive_losses" field.
func ConsecutiveLossesGTE(v int) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldConsecutiveLosses, v))
}

// ConsecutiveLossesLT applies the LT predicate on the "consecutive_losses" field.
func ConsecutiveLossesLT(v int) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldConsecutiveLosses, v))
}

// ConsecutiveLossesLTE applies the LTE predicate on the "consecutive_losses" field.
func ConsecutiveLossesLTE(v int) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldConsecutiveLosses, v))
}

// LastTradeTimeEQ applies the EQ predicate on the "last_trade_time" field.
func LastTradeTimeEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldLastTradeTime, v))
}

// LastTradeTimeNEQ applies the NEQ predicate on the "last_trade_time" field.
func LastTradeTimeNEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldLastTradeTime, v))
}

// LastTradeTimeIn applies the In predicate on the "last_trade_time" field.
func LastTradeTimeIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldLastTradeTime, vs...))
}

// LastTradeTimeNotIn applies the NotIn predicate on the "last_trade_time" field.
func LastTradeTimeNotIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldLastTradeTime, vs...))
}

// LastTradeTimeGT applies the GT predicate on the "last_trade_time" field.
func LastTradeTimeGT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldLastTradeTime, v))
}

// LastTradeTimeGTE applies the GTE predicate on the "last_trade_time" field.
func LastTradeTimeGTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldLastTradeTime, v))
}

// LastTradeTimeLT applies the LT predicate on the "last_trade_time" field.
func LastTradeTimeLT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldLastTradeTime, v))
}

// LastTradeTimeLTE applies the LTE predicate on the "last_trade_time" field.
func LastTradeTimeLTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldLastTradeTime, v))
}

// LastTradeTimeIsNil applies the IsNil predicate on the "last_trade_time" field.
func LastTradeTimeIsNil() predicate.Account {
	return predicate.Account(sql.FieldIsNull(FieldLastTradeTime))
}

// LastTradeTimeNotNil applies the NotNil predicate on the "last_trade_time" field.
func LastTradeTimeNotNil() predicate.Account {
	return predicate.Account(sql.FieldNotNull(FieldLastTradeTime))
}

// CooldownUntilEQ applies the EQ predicate on the "cooldown_until" field.
func CooldownUntilEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldCooldownUntil, v))
}

// CooldownUntilNEQ applies the NEQ predicate on the "cooldown_until" field.
func CooldownUntilNEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldCooldownUntil, v))
}

// CooldownUntilIn applies the In predicate on the "cooldown_until" field.
func CooldownUntilIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldCooldownUntil, vs...))
}

// CooldownUntilNotIn applies the NotIn predicate on the "cooldown_until" field.
func CooldownUntilNotIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldCooldownUntil, vs...))
}

// CooldownUntilGT applies the GT predicate on the "cooldown_until" field.
func CooldownUntilGT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldCooldownUntil, v))
}

// CooldownUntilGTE applies the GTE predicate on the "cooldown_until" field.
func CooldownUntilGTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldCooldownUntil, v))
}

// CooldownUntilLT applies the LT predicate on the "cooldown_until" field.
func CooldownUntilLT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldCooldownUntil, v))
}

// CooldownUntilLTE applies the LTE predicate on the "cooldown_until" field.
func CooldownUntilLTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldCooldownUntil, v))
}

// CooldownUntilIsNil applies the IsNil predicate on the "cooldown_until" field.
func CooldownUntilIsNil() predicate.Account {
	return predicate.Account(sql.FieldIsNull(FieldCooldownUntil))
}

// CooldownUntilNotNil applies the NotNil predicate on the "cooldown_until" field.
func CooldownUntilNotNil() predicate.Account {
	return predicate.Account(sql.FieldNotNull(FieldCooldownUntil))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasPositions applies the HasEdge predicate on the "positions" edge.
func HasPositions() predicate.Account {
	return predicate.Account(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PositionsTable, PositionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPositionsWith applies the HasEdge predicate on the "positions" edge with a given conditions (other predicates).
func HasPositionsWith(preds ...predicate.Position) predicate.Account {
	return predicate.Account(func(s *sql.Selector) {
		step := newPositionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPendingOrders applies the HasEdge predicate on the "pending_orders" edge.
func HasPendingOrders() predicate.Account {
	return predicate.Account(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PendingOrdersTable, PendingOrdersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPendingOrdersWith applies the HasEdge predicate on the "pending_orders" edge with a given conditions (other predicates).
func HasPendingOrdersWith(preds ...predicate.PendingOrder) predicate.Account {
	return predicate.Account(func(s *sql.Selector) {
		step := newPendingOrdersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSnapshots applies the HasEdge predicate on the "snapshots" edge.
func HasSnapshots() predicate.Account {
	return predicate.Account(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SnapshotsTable, SnapshotsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSnapshotsWith applies the HasEdge predicate on the "snapshots" edge with a given conditions (other predicates).
func HasSnapshotsWith(preds ...predicate.AccountSnapshot) predicate.Account {
	return predicate.Account(func(s *sql.Selector) {
		step := newSnapshotsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Account) predicate.Account {
	return predicate.Account(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Account) predicate.Account {
	return predicate.Account(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Account) predicate.Account {
	return predicate.Account(sql.NotPredicates(p))
}
