// Code generated by ent, DO NOT EDIT.

package accountsnapshot

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/chuyen-gia-crypto/backend/internal/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldLTE(FieldID, id))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldEQ(FieldAccountID, v))
}

// Balance applies equality check predicate on the "balance" field. It's identical to BalanceEQ.
func Balance(v float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldEQ(FieldBalance, v))
}

// Equity applies equality check predicate on the "equity" field. It's identical to EquityEQ.
func Equity(v float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldEQ(FieldEquity, v))
}

// UnrealizedPnl applies equality check predicate on the "unrealized_pnl" field. It's identical to UnrealizedPnlEQ.
func UnrealizedPnl(v float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldEQ(FieldUnrealizedPnl, v))
}

// OpenPositions applies equality check predicate on the "open_positions" field. It's identical to OpenPositionsEQ.
func OpenPositions(v int) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldEQ(FieldOpenPositions, v))
}

// Timestamp applies equality check predicate on the "timestamp" field. It's identical to TimestampEQ.
func Timestamp(v time.Time) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldEQ(FieldTimestamp, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldNotIn(FieldAccountID, vs...))
}

// BalanceEQ applies the EQ predicate on the "balance" field.
func BalanceEQ(v float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldEQ(FieldBalance, v))
}

// BalanceNEQ applies the NEQ predicate on the "balance" field.
func BalanceNEQ(v float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldNEQ(FieldBalance, v))
}

// BalanceIn applies the In predicate on the "balance" field.
func BalanceIn(vs ...float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldIn(FieldBalance, vs...))
}

// BalanceNotIn applies the NotIn predicate on the "balance" field.
func BalanceNotIn(vs ...float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldNotIn(FieldBalance, vs...))
}

// BalanceGT applies the GT predicate on the "balance" field.
func BalanceGT(v float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldGT(FieldBalance, v))
}

// BalanceGTE applies the GTE predicate on the "balance" field.
func BalanceGTE(v float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldGTE(FieldBalance, v))
}

// BalanceLT applies the LT predicate on the "balance" field.
func BalanceLT(v float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldLT(FieldBalance, v))
}

// BalanceLTE applies the LTE predicate on the "balance" field.
func BalanceLTE(v float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldLTE(FieldBalance, v))
}

// EquityEQ applies the EQ predicate on the "equity" field.
func EquityEQ(v float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldEQ(FieldEquity, v))
}

// EquityNEQ applies the NEQ predicate on the "equity" field.
func EquityNEQ(v float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldNEQ(FieldEquity, v))
}

// EquityIn applies the In predicate on the "equity" field.
func EquityIn(vs ...float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldIn(FieldEquity, vs...))
}

// EquityNotIn applies the NotIn predicate on the "equity" field.
func EquityNotIn(vs ...float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldNotIn(FieldEquity, vs...))
}

// EquityGT applies the GT predicate on the "equity" field.
func EquityGT(v float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldGT(FieldEquity, v))
}

// EquityGTE applies the GTE predicate on the "equity" field.
func EquityGTE(v float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldGTE(FieldEquity, v))
}

// EquityLT applies the LT predicate on the "equity" field.
func EquityLT(v float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldLT(FieldEquity, v))
}

// EquityLTE applies the LTE predicate on the "equity" field.
func EquityLTE(v float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldLTE(FieldEquity, v))
}

// UnrealizedPnlEQ applies the EQ predicate on the "unrealized_pnl" field.
func UnrealizedPnlEQ(v float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldEQ(FieldUnrealizedPnl, v))
}

// UnrealizedPnlNEQ applies the NEQ predicate on the "unrealized_pnl" field.
func UnrealizedPnlNEQ(v float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldNEQ(FieldUnrealizedPnl, v))
}

// UnrealizedPnlIn applies the In predicate on the "unrealized_pnl" field.
func UnrealizedPnlIn(vs ...float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldIn(FieldUnrealizedPnl, vs...))
}

// UnrealizedPnlNotIn applies the NotIn predicate on the "unrealized_pnl" field.
func UnrealizedPnlNotIn(vs ...float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldNotIn(FieldUnrealizedPnl, vs...))
}

// UnrealizedPnlGT applies the GT predicate on the "unrealized_pnl" field.
func UnrealizedPnlGT(v float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldGT(FieldUnrealizedPnl, v))
}

// UnrealizedPnlGTE applies the GTE predicate on the "unrealized_pnl" field.
func UnrealizedPnlGTE(v float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldGTE(FieldUnrealizedPnl, v))
}

// UnrealizedPnlLT applies the LT predicate on the "unrealized_pnl" field.
func UnrealizedPnlLT(v float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldLT(FieldUnrealizedPnl, v))
}

// UnrealizedPnlLTE applies the LTE predicate on the "unrealized_pnl" field.
func UnrealizedPnlLTE(v float64) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldLTE(FieldUnrealizedPnl, v))
}

// OpenPositionsEQ applies the EQ predicate on the "open_positions" field.
func OpenPositionsEQ(v int) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldEQ(FieldOpenPositions, v))
}

// OpenPositionsNEQ applies the NEQ predicate on the "open_positions" field.
func OpenPositionsNEQ(v int) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldNEQ(FieldOpenPositions, v))
}

// OpenPositionsIn applies the In predicate on the "open_positions" field.
func OpenPositionsIn(vs ...int) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldIn(FieldOpenPositions, vs...))
}

// OpenPositionsNotIn applies the NotIn predicate on the "open_positions" field.
func OpenPositionsNotIn(vs ...int) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldNotIn(FieldOpenPositions, vs...))
}

// OpenPositionsGT applies the GT predicate on the "open_positions" field.
func OpenPositionsGT(v int) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldGT(FieldOpenPositions, v))
}

// OpenPositionsGTE applies the GTE predicate on the "open_positions" field.
func OpenPositionsGTE(v int) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldGTE(FieldOpenPositions, v))
}

// OpenPositionsLT applies the LT predicate on the "open_positions" field.
func OpenPositionsLT(v int) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldLT(FieldOpenPositions, v))
}

// OpenPositionsLTE applies the LTE predicate on the "open_positions" field.
func OpenPositionsLTE(v int) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldLTE(FieldOpenPositions, v))
}

// TimestampEQ applies the EQ predicate on the "timestamp" field.
func TimestampEQ(v time.Time) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldEQ(FieldTimestamp, v))
}

// TimestampNEQ applies the NEQ predicate on the "timestamp" field.
func TimestampNEQ(v time.Time) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldNEQ(FieldTimestamp, v))
}

// TimestampIn applies the In predicate on the "timestamp" field.
func TimestampIn(vs ...time.Time) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldIn(FieldTimestamp, vs...))
}

// TimestampNotIn applies the NotIn predicate on the "timestamp" field.
func TimestampNotIn(vs ...time.Time) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldNotIn(FieldTimestamp, vs...))
}

// TimestampGT applies the GT predicate on the "timestamp" field.
func TimestampGT(v time.Time) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldGT(FieldTimestamp, v))
}

// TimestampGTE applies the GTE predicate on the "timestamp" field.
func TimestampGTE(v time.Time) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldGTE(FieldTimestamp, v))
}

// TimestampLT applies the LT predicate on the "timestamp" field.
func TimestampLT(v time.Time) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldLT(FieldTimestamp, v))
}

// TimestampLTE applies the LTE predicate on the "timestamp" field.
func TimestampLTE(v time.Time) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.FieldLTE(FieldTimestamp, v))
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.AccountSnapshot {
	return predicate.AccountSnapshot(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccountSnapshot) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccountSnapshot) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccountSnapshot) predicate.AccountSnapshot {
	return predicate.AccountSnapshot(sql.NotPredicates(p))
}
