// Code generated by ent, DO NOT EDIT.

package testnetposition

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/chuyen-gia-crypto/backend/internal/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLTE(FieldID, id))
}

// PositionID applies equality check predicate on the "position_id" field. It's identical to PositionIDEQ.
func PositionID(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldPositionID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldAccountID, v))
}

// Symbol applies equality check predicate on the "symbol" field. It's identical to SymbolEQ.
func Symbol(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldSymbol, v))
}

// Side applies equality check predicate on the "side" field. It's identical to SideEQ.
func Side(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldSide, v))
}

// EntryPrice applies equality check predicate on the "entry_price" field. It's identical to EntryPriceEQ.
func EntryPrice(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldEntryPrice, v))
}

// CurrentPrice applies equality check predicate on the "current_price" field. It's identical to CurrentPriceEQ.
func CurrentPrice(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldCurrentPrice, v))
}

// StopLoss applies equality check predicate on the "stop_loss" field. It's identical to StopLossEQ.
func StopLoss(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldStopLoss, v))
}

// TakeProfit applies equality check predicate on the "take_profit" field. It's identical to TakeProfitEQ.
func TakeProfit(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldTakeProfit, v))
}

// EntryTime applies equality check predicate on the "entry_time" field. It's identical to EntryTimeEQ.
func EntryTime(v time.Time) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldEntryTime, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldStatus, v))
}

// SizeUsd applies equality check predicate on the "size_usd" field. It's identical to SizeUsdEQ.
func SizeUsd(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldSizeUsd, v))
}

// SizeQty applies equality check predicate on the "size_qty" field. It's identical to SizeQtyEQ.
func SizeQty(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldSizeQty, v))
}

// RiskUsd applies equality check predicate on the "risk_usd" field. It's identical to RiskUsdEQ.
func RiskUsd(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldRiskUsd, v))
}

// RiskPercent applies equality check predicate on the "risk_percent" field. It's identical to RiskPercentEQ.
func RiskPercent(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldRiskPercent, v))
}

// ExpectedRr applies equality check predicate on the "expected_rr" field. It's identical to ExpectedRrEQ.
func ExpectedRr(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldExpectedRr, v))
}

// RealizedPnl applies equality check predicate on the "realized_pnl" field. It's identical to RealizedPnlEQ.
func RealizedPnl(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldRealizedPnl, v))
}

// UnrealizedPnl applies equality check predicate on the "unrealized_pnl" field. It's identical to UnrealizedPnlEQ.
func UnrealizedPnl(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldUnrealizedPnl, v))
}

// ClosePrice applies equality check predicate on the "close_price" field. It's identical to ClosePriceEQ.
func ClosePrice(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldClosePrice, v))
}

// CloseTime applies equality check predicate on the "close_time" field. It's identical to CloseTimeEQ.
func CloseTime(v time.Time) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldCloseTime, v))
}

// CloseReason applies equality check predicate on the "close_reason" field. It's identical to CloseReasonEQ.
func CloseReason(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldCloseReason, v))
}

// LinkedPredictionID applies equality check predicate on the "linked_prediction_id" field. It's identical to LinkedPredictionIDEQ.
func LinkedPredictionID(v int) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldLinkedPredictionID, v))
}

// BinanceOrderID applies equality check predicate on the "binance_order_id" field. It's identical to BinanceOrderIDEQ.
func BinanceOrderID(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldBinanceOrderID, v))
}

// BinanceSlOrderID applies equality check predicate on the "binance_sl_order_id" field. It's identical to BinanceSlOrderIDEQ.
func BinanceSlOrderID(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldBinanceSlOrderID, v))
}

// BinanceTpOrderID applies equality check predicate on the "binance_tp_order_id" field. It's identical to BinanceTpOrderIDEQ.
func BinanceTpOrderID(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldBinanceTpOrderID, v))
}

// TpLevels applies equality check predicate on the "tp_levels" field. It's identical to TpLevelsEQ.
func TpLevels(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldTpLevels, v))
}

// TpHitCount applies equality check predicate on the "tp_hit_count" field. It's identical to TpHitCountEQ.
func TpHitCount(v int) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldTpHitCount, v))
}

// PartialClosed applies equality check predicate on the "partial_closed" field. It's identical to PartialClosedEQ.
func PartialClosed(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldPartialClosed, v))
}

// PositionIDEQ applies the EQ predicate on the "position_id" field.
func PositionIDEQ(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldPositionID, v))
}

// PositionIDNEQ applies the NEQ predicate on the "position_id" field.
func PositionIDNEQ(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNEQ(FieldPositionID, v))
}

// PositionIDIn applies the In predicate on the "position_id" field.
func PositionIDIn(vs ...string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIn(FieldPositionID, vs...))
}

// PositionIDNotIn applies the NotIn predicate on the "position_id" field.
func PositionIDNotIn(vs ...string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotIn(FieldPositionID, vs...))
}

// PositionIDGT applies the GT predicate on the "position_id" field.
func PositionIDGT(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGT(FieldPositionID, v))
}

// PositionIDGTE applies the GTE predicate on the "position_id" field.
func PositionIDGTE(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGTE(FieldPositionID, v))
}

// PositionIDLT applies the LT predicate on the "position_id" field.
func PositionIDLT(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLT(FieldPositionID, v))
}

// PositionIDLTE applies the LTE predicate on the "position_id" field.
func PositionIDLTE(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLTE(FieldPositionID, v))
}

// PositionIDContains applies the Contains predicate on the "position_id" field.
func PositionIDContains(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldContains(FieldPositionID, v))
}

// PositionIDHasPrefix applies the HasPrefix predicate on the "position_id" field.
func PositionIDHasPrefix(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldHasPrefix(FieldPositionID, v))
}

// PositionIDHasSuffix applies the HasSuffix predicate on the "position_id" field.
func PositionIDHasSuffix(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldHasSuffix(FieldPositionID, v))
}

// PositionIDEqualFold applies the EqualFold predicate on the "position_id" field.
func PositionIDEqualFold(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEqualFold(FieldPositionID, v))
}

// PositionIDContainsFold applies the ContainsFold predicate on the "position_id" field.
func PositionIDContainsFold(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldContainsFold(FieldPositionID, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotIn(FieldAccountID, vs...))
}

// SymbolEQ applies the EQ predicate on the "symbol" field.
func SymbolEQ(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldSymbol, v))
}

// SymbolNEQ applies the NEQ predicate on the "symbol" field.
func SymbolNEQ(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNEQ(FieldSymbol, v))
}

// SymbolIn applies the In predicate on the "symbol" field.
func SymbolIn(vs ...string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIn(FieldSymbol, vs...))
}

// SymbolNotIn applies the NotIn predicate on the "symbol" field.
func SymbolNotIn(vs ...string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotIn(FieldSymbol, vs...))
}

// SymbolGT applies the GT predicate on the "symbol" field.
func SymbolGT(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGT(FieldSymbol, v))
}

// SymbolGTE applies the GTE predicate on the "symbol" field.
func SymbolGTE(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGTE(FieldSymbol, v))
}

// SymbolLT applies the LT predicate on the "symbol" field.
func SymbolLT(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLT(FieldSymbol, v))
}

// SymbolLTE applies the LTE predicate on the "symbol" field.
func SymbolLTE(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLTE(FieldSymbol, v))
}

// SymbolContains applies the Contains predicate on the "symbol" field.
func SymbolContains(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldContains(FieldSymbol, v))
}

// SymbolHasPrefix applies the HasPrefix predicate on the "symbol" field.
func SymbolHasPrefix(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldHasPrefix(FieldSymbol, v))
}

// SymbolHasSuffix applies the HasSuffix predicate on the "symbol" field.
func SymbolHasSuffix(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldHasSuffix(FieldSymbol, v))
}

// SymbolEqualFold applies the EqualFold predicate on the "symbol" field.
func SymbolEqualFold(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEqualFold(FieldSymbol, v))
}

// SymbolContainsFold applies the ContainsFold predicate on the "symbol" field.
func SymbolContainsFold(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldContainsFold(FieldSymbol, v))
}

// SideEQ applies the EQ predicate on the "side" field.
func SideEQ(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldSide, v))
}

// SideNEQ applies the NEQ predicate on the "side" field.
func SideNEQ(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNEQ(FieldSide, v))
}

// SideIn applies the In predicate on the "side" field.
func SideIn(vs ...string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIn(FieldSide, vs...))
}

// SideNotIn applies the NotIn predicate on the "side" field.
func SideNotIn(vs ...string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotIn(FieldSide, vs...))
}

// SideGT applies the GT predicate on the "side" field.
func SideGT(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGT(FieldSide, v))
}

// SideGTE applies the GTE predicate on the "side" field.
func SideGTE(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGTE(FieldSide, v))
}

// SideLT applies the LT predicate on the "side" field.
func SideLT(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLT(FieldSide, v))
}

// SideLTE applies the LTE predicate on the "side" field.
func SideLTE(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLTE(FieldSide, v))
}

// SideContains applies the Contains predicate on the "side" field.
func SideContains(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldContains(FieldSide, v))
}

// SideHasPrefix applies the HasPrefix predicate on the "side" field.
func SideHasPrefix(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldHasPrefix(FieldSide, v))
}

// SideHasSuffix applies the HasSuffix predicate on the "side" field.
func SideHasSuffix(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldHasSuffix(FieldSide, v))
}

// SideEqualFold applies the EqualFold predicate on the "side" field.
func SideEqualFold(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEqualFold(FieldSide, v))
}

// SideContainsFold applies the ContainsFold predicate on the "side" field.
func SideContainsFold(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldContainsFold(FieldSide, v))
}

// EntryPriceEQ applies the EQ predicate on the "entry_price" field.
func EntryPriceEQ(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldEntryPrice, v))
}

// EntryPriceNEQ applies the NEQ predicate on the "entry_price" field.
func EntryPriceNEQ(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNEQ(FieldEntryPrice, v))
}

// EntryPriceIn applies the In predicate on the "entry_price" field.
func EntryPriceIn(vs ...float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIn(FieldEntryPrice, vs...))
}

// EntryPriceNotIn applies the NotIn predicate on the "entry_price" field.
func EntryPriceNotIn(vs ...float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotIn(FieldEntryPrice, vs...))
}

// EntryPriceGT applies the GT predicate on the "entry_price" field.
func EntryPriceGT(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGT(FieldEntryPrice, v))
}

// EntryPriceGTE applies the GTE predicate on the "entry_price" field.
func EntryPriceGTE(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGTE(FieldEntryPrice, v))
}

// EntryPriceLT applies the LT predicate on the "entry_price" field.
func EntryPriceLT(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLT(FieldEntryPrice, v))
}

// EntryPriceLTE applies the LTE predicate on the "entry_price" field.
func EntryPriceLTE(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLTE(FieldEntryPrice, v))
}

// CurrentPriceEQ applies the EQ predicate on the "current_price" field.
func CurrentPriceEQ(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldCurrentPrice, v))
}

// CurrentPriceNEQ applies the NEQ predicate on the "current_price" field.
func CurrentPriceNEQ(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNEQ(FieldCurrentPrice, v))
}

// CurrentPriceIn applies the In predicate on the "current_price" field.
func CurrentPriceIn(vs ...float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIn(FieldCurrentPrice, vs...))
}

// CurrentPriceNotIn applies the NotIn predicate on the "current_price" field.
func CurrentPriceNotIn(vs ...float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotIn(FieldCurrentPrice, vs...))
}

// CurrentPriceGT applies the GT predicate on the "current_price" field.
func CurrentPriceGT(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGT(FieldCurrentPrice, v))
}

// CurrentPriceGTE applies the GTE predicate on the "current_price" field.
func CurrentPriceGTE(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGTE(FieldCurrentPrice, v))
}

// CurrentPriceLT applies the LT predicate on the "current_price" field.
func CurrentPriceLT(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLT(FieldCurrentPrice, v))
}

// CurrentPriceLTE applies the LTE predicate on the "current_price" field.
func CurrentPriceLTE(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLTE(FieldCurrentPrice, v))
}

// StopLossEQ applies the EQ predicate on the "stop_loss" field.
func StopLossEQ(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldStopLoss, v))
}

// StopLossNEQ applies the NEQ predicate on the "stop_loss" field.
func StopLossNEQ(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNEQ(FieldStopLoss, v))
}

// StopLossIn applies the In predicate on the "stop_loss" field.
func StopLossIn(vs ...float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIn(FieldStopLoss, vs...))
}

// StopLossNotIn applies the NotIn predicate on the "stop_loss" field.
func StopLossNotIn(vs ...float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotIn(FieldStopLoss, vs...))
}

// StopLossGT applies the GT predicate on the "stop_loss" field.
func StopLossGT(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGT(FieldStopLoss, v))
}

// StopLossGTE applies the GTE predicate on the "stop_loss" field.
func StopLossGTE(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGTE(FieldStopLoss, v))
}

// StopLossLT applies the LT predicate on the "stop_loss" field.
func StopLossLT(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLT(FieldStopLoss, v))
}

// StopLossLTE applies the LTE predicate on the "stop_loss" field.
func StopLossLTE(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLTE(FieldStopLoss, v))
}

// TakeProfitEQ applies the EQ predicate on the "take_profit" field.
func TakeProfitEQ(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldTakeProfit, v))
}

// TakeProfitNEQ applies the NEQ predicate on the "take_profit" field.
func TakeProfitNEQ(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNEQ(FieldTakeProfit, v))
}

// TakeProfitIn applies the In predicate on the "take_profit" field.
func TakeProfitIn(vs ...float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIn(FieldTakeProfit, vs...))
}

// TakeProfitNotIn applies the NotIn predicate on the "take_profit" field.
func TakeProfitNotIn(vs ...float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotIn(FieldTakeProfit, vs...))
}

// TakeProfitGT applies the GT predicate on the "take_profit" field.
func TakeProfitGT(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGT(FieldTakeProfit, v))
}

// TakeProfitGTE applies the GTE predicate on the "take_profit" field.
func TakeProfitGTE(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGTE(FieldTakeProfit, v))
}

// TakeProfitLT applies the LT predicate on the "take_profit" field.
func TakeProfitLT(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLT(FieldTakeProfit, v))
}

// TakeProfitLTE applies the LTE predicate on the "take_profit" field.
func TakeProfitLTE(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLTE(FieldTakeProfit, v))
}

// EntryTimeEQ applies the EQ predicate on the "entry_time" field.
func EntryTimeEQ(v time.Time) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldEntryTime, v))
}

// EntryTimeNEQ applies the NEQ predicate on the "entry_time" field.
func EntryTimeNEQ(v time.Time) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNEQ(FieldEntryTime, v))
}

// EntryTimeIn applies the In predicate on the "entry_time" field.
func EntryTimeIn(vs ...time.Time) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIn(FieldEntryTime, vs...))
}

// EntryTimeNotIn applies the NotIn predicate on the "entry_time" field.
func EntryTimeNotIn(vs ...time.Time) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotIn(FieldEntryTime, vs...))
}

// EntryTimeGT applies the GT predicate on the "entry_time" field.
func EntryTimeGT(v time.Time) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGT(FieldEntryTime, v))
}

// EntryTimeGTE applies the GTE predicate on the "entry_time" field.
func EntryTimeGTE(v time.Time) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGTE(FieldEntryTime, v))
}

// EntryTimeLT applies the LT predicate on the "entry_time" field.
func EntryTimeLT(v time.Time) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLT(FieldEntryTime, v))
}

// EntryTimeLTE applies the LTE predicate on the "entry_time" field.
func EntryTimeLTE(v time.Time) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLTE(FieldEntryTime, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldContainsFold(FieldStatus, v))
}

// SizeUsdEQ applies the EQ predicate on the "size_usd" field.
func SizeUsdEQ(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldSizeUsd, v))
}

// SizeUsdNEQ applies the NEQ predicate on the "size_usd" field.
func SizeUsdNEQ(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNEQ(FieldSizeUsd, v))
}

// SizeUsdIn applies the In predicate on the "size_usd" field.
func SizeUsdIn(vs ...float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIn(FieldSizeUsd, vs...))
}

// SizeUsdNotIn applies the NotIn predicate on the "size_usd" field.
func SizeUsdNotIn(vs ...float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotIn(FieldSizeUsd, vs...))
}

// SizeUsdGT applies the GT predicate on the "size_usd" field.
func SizeUsdGT(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGT(FieldSizeUsd, v))
}

// SizeUsdGTE applies the GTE predicate on the "size_usd" field.
func SizeUsdGTE(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGTE(FieldSizeUsd, v))
}

// SizeUsdLT applies the LT predicate on the "size_usd" field.
func SizeUsdLT(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLT(FieldSizeUsd, v))
}

// SizeUsdLTE applies the LTE predicate on the "size_usd" field.
func SizeUsdLTE(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLTE(FieldSizeUsd, v))
}

// SizeQtyEQ applies the EQ predicate on the "size_qty" field.
func SizeQtyEQ(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldSizeQty, v))
}

// SizeQtyNEQ applies the NEQ predicate on the "size_qty" field.
func SizeQtyNEQ(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNEQ(FieldSizeQty, v))
}

// SizeQtyIn applies the In predicate on the "size_qty" field.
func SizeQtyIn(vs ...float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIn(FieldSizeQty, vs...))
}

// SizeQtyNotIn applies the NotIn predicate on the "size_qty" field.
func SizeQtyNotIn(vs ...float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotIn(FieldSizeQty, vs...))
}

// SizeQtyGT applies the GT predicate on the "size_qty" field.
func SizeQtyGT(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGT(FieldSizeQty, v))
}

// SizeQtyGTE applies the GTE predicate on the "size_qty" field.
func SizeQtyGTE(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGTE(FieldSizeQty, v))
}

// SizeQtyLT applies the LT predicate on the "size_qty" field.
func SizeQtyLT(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLT(FieldSizeQty, v))
}

// SizeQtyLTE applies the LTE predicate on the "size_qty" field.
func SizeQtyLTE(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLTE(FieldSizeQty, v))
}

// RiskUsdEQ applies the EQ predicate on the "risk_usd" field.
func RiskUsdEQ(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldRiskUsd, v))
}

// RiskUsdNEQ applies the NEQ predicate on the "risk_usd" field.
func RiskUsdNEQ(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNEQ(FieldRiskUsd, v))
}

// RiskUsdIn applies the In predicate on the "risk_usd" field.
func RiskUsdIn(vs ...float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIn(FieldRiskUsd, vs...))
}

// RiskUsdNotIn applies the NotIn predicate on the "risk_usd" field.
func RiskUsdNotIn(vs ...float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotIn(FieldRiskUsd, vs...))
}

// RiskUsdGT applies the GT predicate on the "risk_usd" field.
func RiskUsdGT(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGT(FieldRiskUsd, v))
}

// RiskUsdGTE applies the GTE predicate on the "risk_usd" field.
func RiskUsdGTE(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGTE(FieldRiskUsd, v))
}

// RiskUsdLT applies the LT predicate on the "risk_usd" field.
func RiskUsdLT(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLT(FieldRiskUsd, v))
}

// RiskUsdLTE applies the LTE predicate on the "risk_usd" field.
func RiskUsdLTE(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLTE(FieldRiskUsd, v))
}

// RiskPercentEQ applies the EQ predicate on the "risk_percent" field.
func RiskPercentEQ(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldRiskPercent, v))
}

// RiskPercentNEQ applies the NEQ predicate on the "risk_percent" field.
func RiskPercentNEQ(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNEQ(FieldRiskPercent, v))
}

// RiskPercentIn applies the In predicate on the "risk_percent" field.
func RiskPercentIn(vs ...float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIn(FieldRiskPercent, vs...))
}

// RiskPercentNotIn applies the NotIn predicate on the "risk_percent" field.
func RiskPercentNotIn(vs ...float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotIn(FieldRiskPercent, vs...))
}

// RiskPercentGT applies the GT predicate on the "risk_percent" field.
func RiskPercentGT(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGT(FieldRiskPercent, v))
}

// RiskPercentGTE applies the GTE predicate on the "risk_percent" field.
func RiskPercentGTE(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGTE(FieldRiskPercent, v))
}

// RiskPercentLT applies the LT predicate on the "risk_percent" field.
func RiskPercentLT(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLT(FieldRiskPercent, v))
}

// RiskPercentLTE applies the LTE predicate on the "risk_percent" field.
func RiskPercentLTE(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLTE(FieldRiskPercent, v))
}

// ExpectedRrEQ applies the EQ predicate on the "expected_rr" field.
func ExpectedRrEQ(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldExpectedRr, v))
}

// ExpectedRrNEQ applies the NEQ predicate on the "expected_rr" field.
func ExpectedRrNEQ(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNEQ(FieldExpectedRr, v))
}

// ExpectedRrIn applies the In predicate on the "expected_rr" field.
func ExpectedRrIn(vs ...float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIn(FieldExpectedRr, vs...))
}

// ExpectedRrNotIn applies the NotIn predicate on the "expected_rr" field.
func ExpectedRrNotIn(vs ...float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotIn(FieldExpectedRr, vs...))
}

// ExpectedRrGT applies the GT predicate on the "expected_rr" field.
func ExpectedRrGT(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGT(FieldExpectedRr, v))
}

// ExpectedRrGTE applies the GTE predicate on the "expected_rr" field.
func ExpectedRrGTE(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGTE(FieldExpectedRr, v))
}

// ExpectedRrLT applies the LT predicate on the "expected_rr" field.
func ExpectedRrLT(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLT(FieldExpectedRr, v))
}

// ExpectedRrLTE applies the LTE predicate on the "expected_rr" field.
func ExpectedRrLTE(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLTE(FieldExpectedRr, v))
}

// RealizedPnlEQ applies the EQ predicate on the "realized_pnl" field.
func RealizedPnlEQ(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldRealizedPnl, v))
}

// RealizedPnlNEQ applies the NEQ predicate on the "realized_pnl" field.
func RealizedPnlNEQ(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNEQ(FieldRealizedPnl, v))
}

// RealizedPnlIn applies the In predicate on the "realized_pnl" field.
func RealizedPnlIn(vs ...float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIn(FieldRealizedPnl, vs...))
}

// RealizedPnlNotIn applies the NotIn predicate on the "realized_pnl" field.
func RealizedPnlNotIn(vs ...float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotIn(FieldRealizedPnl, vs...))
}

// RealizedPnlGT applies the GT predicate on the "realized_pnl" field.
func RealizedPnlGT(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGT(FieldRealizedPnl, v))
}

// RealizedPnlGTE applies the GTE predicate on the "realized_pnl" field.
func RealizedPnlGTE(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGTE(FieldRealizedPnl, v))
}

// RealizedPnlLT applies the LT predicate on the "realized_pnl" field.
func RealizedPnlLT(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLT(FieldRealizedPnl, v))
}

// RealizedPnlLTE applies the LTE predicate on the "realized_pnl" field.
func RealizedPnlLTE(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLTE(FieldRealizedPnl, v))
}

// UnrealizedPnlEQ applies the EQ predicate on the "unrealized_pnl" field.
func UnrealizedPnlEQ(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldUnrealizedPnl, v))
}

// UnrealizedPnlNEQ applies the NEQ predicate on the "unrealized_pnl" field.
func UnrealizedPnlNEQ(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNEQ(FieldUnrealizedPnl, v))
}

// UnrealizedPnlIn applies the In predicate on the "unrealized_pnl" field.
func UnrealizedPnlIn(vs ...float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIn(FieldUnrealizedPnl, vs...))
}

// UnrealizedPnlNotIn applies the NotIn predicate on the "unrealized_pnl" field.
func UnrealizedPnlNotIn(vs ...float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotIn(FieldUnrealizedPnl, vs...))
}

// UnrealizedPnlGT applies the GT predicate on the "unrealized_pnl" field.
func UnrealizedPnlGT(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGT(FieldUnrealizedPnl, v))
}

// UnrealizedPnlGTE applies the GTE predicate on the "unrealized_pnl" field.
func UnrealizedPnlGTE(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGTE(FieldUnrealizedPnl, v))
}

// UnrealizedPnlLT applies the LT predicate on the "unrealized_pnl" field.
func UnrealizedPnlLT(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLT(FieldUnrealizedPnl, v))
}

// UnrealizedPnlLTE applies the LTE predicate on the "unrealized_pnl" field.
func UnrealizedPnlLTE(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLTE(FieldUnrealizedPnl, v))
}

// ClosePriceEQ applies the EQ predicate on the "close_price" field.
func ClosePriceEQ(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldClosePrice, v))
}

// ClosePriceNEQ applies the NEQ predicate on the "close_price" field.
func ClosePriceNEQ(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNEQ(FieldClosePrice, v))
}

// ClosePriceIn applies the In predicate on the "close_price" field.
func ClosePriceIn(vs ...float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIn(FieldClosePrice, vs...))
}

// ClosePriceNotIn applies the NotIn predicate on the "close_price" field.
func ClosePriceNotIn(vs ...float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotIn(FieldClosePrice, vs...))
}

// ClosePriceGT applies the GT predicate on the "close_price" field.
func ClosePriceGT(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGT(FieldClosePrice, v))
}

// ClosePriceGTE applies the GTE predicate on the "close_price" field.
func ClosePriceGTE(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGTE(FieldClosePrice, v))
}

// ClosePriceLT applies the LT predicate on the "close_price" field.
func ClosePriceLT(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLT(FieldClosePrice, v))
}

// ClosePriceLTE applies the LTE predicate on the "close_price" field.
func ClosePriceLTE(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLTE(FieldClosePrice, v))
}

// ClosePriceIsNil applies the IsNil predicate on the "close_price" field.
func ClosePriceIsNil() predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIsNull(FieldClosePrice))
}

// ClosePriceNotNil applies the NotNil predicate on the "close_price" field.
func ClosePriceNotNil() predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotNull(FieldClosePrice))
}

// CloseTimeEQ applies the EQ predicate on the "close_time" field.
func CloseTimeEQ(v time.Time) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldCloseTime, v))
}

// CloseTimeNEQ applies the NEQ predicate on the "close_time" field.
func CloseTimeNEQ(v time.Time) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNEQ(FieldCloseTime, v))
}

// CloseTimeIn applies the In predicate on the "close_time" field.
func CloseTimeIn(vs ...time.Time) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIn(FieldCloseTime, vs...))
}

// CloseTimeNotIn applies the NotIn predicate on the "close_time" field.
func CloseTimeNotIn(vs ...time.Time) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotIn(FieldCloseTime, vs...))
}

// CloseTimeGT applies the GT predicate on the "close_time" field.
func CloseTimeGT(v time.Time) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGT(FieldCloseTime, v))
}

// CloseTimeGTE applies the GTE predicate on the "close_time" field.
func CloseTimeGTE(v time.Time) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGTE(FieldCloseTime, v))
}

// CloseTimeLT applies the LT predicate on the "close_time" field.
func CloseTimeLT(v time.Time) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLT(FieldCloseTime, v))
}

// CloseTimeLTE applies the LTE predicate on the "close_time" field.
func CloseTimeLTE(v time.Time) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLTE(FieldCloseTime, v))
}

// CloseTimeIsNil applies the IsNil predicate on the "close_time" field.
func CloseTimeIsNil() predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIsNull(FieldCloseTime))
}

// CloseTimeNotNil applies the NotNil predicate on the "close_time" field.
func CloseTimeNotNil() predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotNull(FieldCloseTime))
}

// CloseReasonEQ applies the EQ predicate on the "close_reason" field.
func CloseReasonEQ(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldCloseReason, v))
}

// CloseReasonNEQ applies the NEQ predicate on the "close_reason" field.
func CloseReasonNEQ(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNEQ(FieldCloseReason, v))
}

// CloseReasonIn applies the In predicate on the "close_reason" field.
func CloseReasonIn(vs ...string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIn(FieldCloseReason, vs...))
}

// CloseReasonNotIn applies the NotIn predicate on the "close_reason" field.
func CloseReasonNotIn(vs ...string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotIn(FieldCloseReason, vs...))
}

// CloseReasonGT applies the GT predicate on the "close_reason" field.
func CloseReasonGT(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGT(FieldCloseReason, v))
}

// CloseReasonGTE applies the GTE predicate on the "close_reason" field.
func CloseReasonGTE(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGTE(FieldCloseReason, v))
}

// CloseReasonLT applies the LT predicate on the "close_reason" field.
func CloseReasonLT(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLT(FieldCloseReason, v))
}

// CloseReasonLTE applies the LTE predicate on the "close_reason" field.
func CloseReasonLTE(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLTE(FieldCloseReason, v))
}

// CloseReasonContains applies the Contains predicate on the "close_reason" field.
func CloseReasonContains(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldContains(FieldCloseReason, v))
}

// CloseReasonHasPrefix applies the HasPrefix predicate on the "close_reason" field.
func CloseReasonHasPrefix(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldHasPrefix(FieldCloseReason, v))
}

// CloseReasonHasSuffix applies the HasSuffix predicate on the "close_reason" field.
func CloseReasonHasSuffix(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldHasSuffix(FieldCloseReason, v))
}

// CloseReasonIsNil applies the IsNil predicate on the "close_reason" field.
func CloseReasonIsNil() predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIsNull(FieldCloseReason))
}

// CloseReasonNotNil applies the NotNil predicate on the "close_reason" field.
func CloseReasonNotNil() predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotNull(FieldCloseReason))
}

// CloseReasonEqualFold applies the EqualFold predicate on the "close_reason" field.
func CloseReasonEqualFold(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEqualFold(FieldCloseReason, v))
}

// CloseReasonContainsFold applies the ContainsFold predicate on the "close_reason" field.
func CloseReasonContainsFold(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldContainsFold(FieldCloseReason, v))
}

// LinkedPredictionIDEQ applies the EQ predicate on the "linked_prediction_id" field.
func LinkedPredictionIDEQ(v int) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldLinkedPredictionID, v))
}

// LinkedPredictionIDNEQ applies the NEQ predicate on the "linked_prediction_id" field.
func LinkedPredictionIDNEQ(v int) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNEQ(FieldLinkedPredictionID, v))
}

// LinkedPredictionIDIn applies the In predicate on the "linked_prediction_id" field.
func LinkedPredictionIDIn(vs ...int) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIn(FieldLinkedPredictionID, vs...))
}

// LinkedPredictionIDNotIn applies the NotIn predicate on the "linked_prediction_id" field.
func LinkedPredictionIDNotIn(vs ...int) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotIn(FieldLinkedPredictionID, vs...))
}

// LinkedPredictionIDGT applies the GT predicate on the "linked_prediction_id" field.
func LinkedPredictionIDGT(v int) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGT(FieldLinkedPredictionID, v))
}

// LinkedPredictionIDGTE applies the GTE predicate on the "linked_prediction_id" field.
func LinkedPredictionIDGTE(v int) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGTE(FieldLinkedPredictionID, v))
}

// LinkedPredictionIDLT applies the LT predicate on the "linked_prediction_id" field.
func LinkedPredictionIDLT(v int) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLT(FieldLinkedPredictionID, v))
}

// LinkedPredictionIDLTE applies the LTE predicate on the "linked_prediction_id" field.
func LinkedPredictionIDLTE(v int) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLTE(FieldLinkedPredictionID, v))
}

// LinkedPredictionIDIsNil applies the IsNil predicate on the "linked_prediction_id" field.
func LinkedPredictionIDIsNil() predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIsNull(FieldLinkedPredictionID))
}

// LinkedPredictionIDNotNil applies the NotNil predicate on the "linked_prediction_id" field.
func LinkedPredictionIDNotNil() predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotNull(FieldLinkedPredictionID))
}

// BinanceOrderIDEQ applies the EQ predicate on the "binance_order_id" field.
func BinanceOrderIDEQ(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldBinanceOrderID, v))
}

// BinanceOrderIDNEQ applies the NEQ predicate on the "binance_order_id" field.
func BinanceOrderIDNEQ(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNEQ(FieldBinanceOrderID, v))
}

// BinanceOrderIDIn applies the In predicate on the "binance_order_id" field.
func BinanceOrderIDIn(vs ...string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIn(FieldBinanceOrderID, vs...))
}

// BinanceOrderIDNotIn applies the NotIn predicate on the "binance_order_id" field.
func BinanceOrderIDNotIn(vs ...string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotIn(FieldBinanceOrderID, vs...))
}

// BinanceOrderIDGT applies the GT predicate on the "binance_order_id" field.
func BinanceOrderIDGT(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGT(FieldBinanceOrderID, v))
}

// BinanceOrderIDGTE applies the GTE predicate on the "binance_order_id" field.
func BinanceOrderIDGTE(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGTE(FieldBinanceOrderID, v))
}

// BinanceOrderIDLT applies the LT predicate on the "binance_order_id" field.
func BinanceOrderIDLT(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLT(FieldBinanceOrderID, v))
}

// BinanceOrderIDLTE applies the LTE predicate on the "binance_order_id" field.
func BinanceOrderIDLTE(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLTE(FieldBinanceOrderID, v))
}

// BinanceOrderIDContains applies the Contains predicate on the "binance_order_id" field.
func BinanceOrderIDContains(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldContains(FieldBinanceOrderID, v))
}

// BinanceOrderIDHasPrefix applies the HasPrefix predicate on the "binance_order_id" field.
func BinanceOrderIDHasPrefix(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldHasPrefix(FieldBinanceOrderID, v))
}

// BinanceOrderIDHasSuffix applies the HasSuffix predicate on the "binance_order_id" field.
func BinanceOrderIDHasSuffix(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldHasSuffix(FieldBinanceOrderID, v))
}

// BinanceOrderIDIsNil applies the IsNil predicate on the "binance_order_id" field.
func BinanceOrderIDIsNil() predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIsNull(FieldBinanceOrderID))
}

// BinanceOrderIDNotNil applies the NotNil predicate on the "binance_order_id" field.
func BinanceOrderIDNotNil() predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotNull(FieldBinanceOrderID))
}

// BinanceOrderIDEqualFold applies the EqualFold predicate on the "binance_order_id" field.
func BinanceOrderIDEqualFold(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEqualFold(FieldBinanceOrderID, v))
}

// BinanceOrderIDContainsFold applies the ContainsFold predicate on the "binance_order_id" field.
func BinanceOrderIDContainsFold(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldContainsFold(FieldBinanceOrderID, v))
}

// BinanceSlOrderIDEQ applies the EQ predicate on the "binance_sl_order_id" field.
func BinanceSlOrderIDEQ(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldBinanceSlOrderID, v))
}

// BinanceSlOrderIDNEQ applies the NEQ predicate on the "binance_sl_order_id" field.
func BinanceSlOrderIDNEQ(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNEQ(FieldBinanceSlOrderID, v))
}

// BinanceSlOrderIDIn applies the In predicate on the "binance_sl_order_id" field.
func BinanceSlOrderIDIn(vs ...string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIn(FieldBinanceSlOrderID, vs...))
}

// BinanceSlOrderIDNotIn applies the NotIn predicate on the "binance_sl_order_id" field.
func BinanceSlOrderIDNotIn(vs ...string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotIn(FieldBinanceSlOrderID, vs...))
}

// BinanceSlOrderIDGT applies the GT predicate on the "binance_sl_order_id" field.
func BinanceSlOrderIDGT(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGT(FieldBinanceSlOrderID, v))
}

// BinanceSlOrderIDGTE applies the GTE predicate on the "binance_sl_order_id" field.
func BinanceSlOrderIDGTE(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGTE(FieldBinanceSlOrderID, v))
}

// BinanceSlOrderIDLT applies the LT predicate on the "binance_sl_order_id" field.
func BinanceSlOrderIDLT(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLT(FieldBinanceSlOrderID, v))
}

// BinanceSlOrderIDLTE applies the LTE predicate on the "binance_sl_order_id" field.
func BinanceSlOrderIDLTE(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLTE(FieldBinanceSlOrderID, v))
}

// BinanceSlOrderIDContains applies the Contains predicate on the "binance_sl_order_id" field.
func BinanceSlOrderIDContains(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldContains(FieldBinanceSlOrderID, v))
}

// BinanceSlOrderIDHasPrefix applies the HasPrefix predicate on the "binance_sl_order_id" field.
func BinanceSlOrderIDHasPrefix(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldHasPrefix(FieldBinanceSlOrderID, v))
}

// BinanceSlOrderIDHasSuffix applies the HasSuffix predicate on the "binance_sl_order_id" field.
func BinanceSlOrderIDHasSuffix(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldHasSuffix(FieldBinanceSlOrderID, v))
}

// BinanceSlOrderIDIsNil applies the IsNil predicate on the "binance_sl_order_id" field.
func BinanceSlOrderIDIsNil() predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIsNull(FieldBinanceSlOrderID))
}

// BinanceSlOrderIDNotNil applies the NotNil predicate on the "binance_sl_order_id" field.
func BinanceSlOrderIDNotNil() predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotNull(FieldBinanceSlOrderID))
}

// BinanceSlOrderIDEqualFold applies the EqualFold predicate on the "binance_sl_order_id" field.
func BinanceSlOrderIDEqualFold(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEqualFold(FieldBinanceSlOrderID, v))
}

// BinanceSlOrderIDContainsFold applies the ContainsFold predicate on the "binance_sl_order_id" field.
func BinanceSlOrderIDContainsFold(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldContainsFold(FieldBinanceSlOrderID, v))
}

// BinanceTpOrderIDEQ applies the EQ predicate on the "binance_tp_order_id" field.
func BinanceTpOrderIDEQ(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldBinanceTpOrderID, v))
}

// BinanceTpOrderIDNEQ applies the NEQ predicate on the "binance_tp_order_id" field.
func BinanceTpOrderIDNEQ(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNEQ(FieldBinanceTpOrderID, v))
}

// BinanceTpOrderIDIn applies the In predicate on the "binance_tp_order_id" field.
func BinanceTpOrderIDIn(vs ...string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIn(FieldBinanceTpOrderID, vs...))
}

// BinanceTpOrderIDNotIn applies the NotIn predicate on the "binance_tp_order_id" field.
func BinanceTpOrderIDNotIn(vs ...string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotIn(FieldBinanceTpOrderID, vs...))
}

// BinanceTpOrderIDGT applies the GT predicate on the "binance_tp_order_id" field.
func BinanceTpOrderIDGT(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGT(FieldBinanceTpOrderID, v))
}

// BinanceTpOrderIDGTE applies the GTE predicate on the "binance_tp_order_id" field.
func BinanceTpOrderIDGTE(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGTE(FieldBinanceTpOrderID, v))
}

// BinanceTpOrderIDLT applies the LT predicate on the "binance_tp_order_id" field.
func BinanceTpOrderIDLT(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLT(FieldBinanceTpOrderID, v))
}

// BinanceTpOrderIDLTE applies the LTE predicate on the "binance_tp_order_id" field.
func BinanceTpOrderIDLTE(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLTE(FieldBinanceTpOrderID, v))
}

// BinanceTpOrderIDContains applies the Contains predicate on the "binance_tp_order_id" field.
func BinanceTpOrderIDContains(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldContains(FieldBinanceTpOrderID, v))
}

// BinanceTpOrderIDHasPrefix applies the HasPrefix predicate on the "binance_tp_order_id" field.
func BinanceTpOrderIDHasPrefix(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldHasPrefix(FieldBinanceTpOrderID, v))
}

// BinanceTpOrderIDHasSuffix applies the HasSuffix predicate on the "binance_tp_order_id" field.
func BinanceTpOrderIDHasSuffix(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldHasSuffix(FieldBinanceTpOrderID, v))
}

// BinanceTpOrderIDIsNil applies the IsNil predicate on the "binance_tp_order_id" field.
func BinanceTpOrderIDIsNil() predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIsNull(FieldBinanceTpOrderID))
}

// BinanceTpOrderIDNotNil applies the NotNil predicate on the "binance_tp_order_id" field.
func BinanceTpOrderIDNotNil() predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotNull(FieldBinanceTpOrderID))
}

// BinanceTpOrderIDEqualFold applies the EqualFold predicate on the "binance_tp_order_id" field.
func BinanceTpOrderIDEqualFold(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEqualFold(FieldBinanceTpOrderID, v))
}

// BinanceTpOrderIDContainsFold applies the ContainsFold predicate on the "binance_tp_order_id" field.
func BinanceTpOrderIDContainsFold(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldContainsFold(FieldBinanceTpOrderID, v))
}

// TpLevelsEQ applies the EQ predicate on the "tp_levels" field.
func TpLevelsEQ(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldTpLevels, v))
}

// TpLevelsNEQ applies the NEQ predicate on the "tp_levels" field.
func TpLevelsNEQ(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNEQ(FieldTpLevels, v))
}

// TpLevelsIn applies the In predicate on the "tp_levels" field.
func TpLevelsIn(vs ...string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIn(FieldTpLevels, vs...))
}

// TpLevelsNotIn applies the NotIn predicate on the "tp_levels" field.
func TpLevelsNotIn(vs ...string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotIn(FieldTpLevels, vs...))
}

// TpLevelsGT applies the GT predicate on the "tp_levels" field.
func TpLevelsGT(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGT(FieldTpLevels, v))
}

// TpLevelsGTE applies the GTE predicate on the "tp_levels" field.
func TpLevelsGTE(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGTE(FieldTpLevels, v))
}

// TpLevelsLT applies the LT predicate on the "tp_levels" field.
func TpLevelsLT(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLT(FieldTpLevels, v))
}

// TpLevelsLTE applies the LTE predicate on the "tp_levels" field.
func TpLevelsLTE(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLTE(FieldTpLevels, v))
}

// TpLevelsContains applies the Contains predicate on the "tp_levels" field.
func TpLevelsContains(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldContains(FieldTpLevels, v))
}

// TpLevelsHasPrefix applies the HasPrefix predicate on the "tp_levels" field.
func TpLevelsHasPrefix(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldHasPrefix(FieldTpLevels, v))
}

// TpLevelsHasSuffix applies the HasSuffix predicate on the "tp_levels" field.
func TpLevelsHasSuffix(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldHasSuffix(FieldTpLevels, v))
}

// TpLevelsIsNil applies the IsNil predicate on the "tp_levels" field.
func TpLevelsIsNil() predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIsNull(FieldTpLevels))
}

// TpLevelsNotNil applies the NotNil predicate on the "tp_levels" field.
func TpLevelsNotNil() predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotNull(FieldTpLevels))
}

// TpLevelsEqualFold applies the EqualFold predicate on the "tp_levels" field.
func TpLevelsEqualFold(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEqualFold(FieldTpLevels, v))
}

// TpLevelsContainsFold applies the ContainsFold predicate on the "tp_levels" field.
func TpLevelsContainsFold(v string) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldContainsFold(FieldTpLevels, v))
}

// TpHitCountEQ applies the EQ predicate on the "tp_hit_count" field.
func TpHitCountEQ(v int) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldTpHitCount, v))
}

// TpHitCountNEQ applies the NEQ predicate on the "tp_hit_count" field.
func TpHitCountNEQ(v int) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNEQ(FieldTpHitCount, v))
}

// TpHitCountIn applies the In predicate on the "tp_hit_count" field.
func TpHitCountIn(vs ...int) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIn(FieldTpHitCount, vs...))
}

// TpHitCountNotIn applies the NotIn predicate on the "tp_hit_count" field.
func TpHitCountNotIn(vs ...int) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotIn(FieldTpHitCount, vs...))
}

// TpHitCountGT applies the GT predicate on the "tp_hit_count" field.
func TpHitCountGT(v int) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGT(FieldTpHitCount, v))
}

// TpHitCountGTE applies the GTE predicate on the "tp_hit_count" field.
func TpHitCountGTE(v int) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGTE(FieldTpHitCount, v))
}

// TpHitCountLT applies the LT predicate on the "tp_hit_count" field.
func TpHitCountLT(v int) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLT(FieldTpHitCount, v))
}

// TpHitCountLTE applies the LTE predicate on the "tp_hit_count" field.
func TpHitCountLTE(v int) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLTE(FieldTpHitCount, v))
}

// PartialClosedEQ applies the EQ predicate on the "partial_closed" field.
func PartialClosedEQ(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldEQ(FieldPartialClosed, v))
}

// PartialClosedNEQ applies the NEQ predicate on the "partial_closed" field.
func PartialClosedNEQ(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNEQ(FieldPartialClosed, v))
}

// PartialClosedIn applies the In predicate on the "partial_closed" field.
func PartialClosedIn(vs ...float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldIn(FieldPartialClosed, vs...))
}

// PartialClosedNotIn applies the NotIn predicate on the "partial_closed" field.
func PartialClosedNotIn(vs ...float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldNotIn(FieldPartialClosed, vs...))
}

// PartialClosedGT applies the GT predicate on the "partial_closed" field.
func PartialClosedGT(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGT(FieldPartialClosed, v))
}

// PartialClosedGTE applies the GTE predicate on the "partial_closed" field.
func PartialClosedGTE(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldGTE(FieldPartialClosed, v))
}

// PartialClosedLT applies the LT predicate on the "partial_closed" field.
func PartialClosedLT(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLT(FieldPartialClosed, v))
}

// PartialClosedLTE applies the LTE predicate on the "partial_closed" field.
func PartialClosedLTE(v float64) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.FieldLTE(FieldPartialClosed, v))
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.TestnetPosition {
	return predicate.TestnetPosition(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.TestnetAccount) predicate.TestnetPosition {
	return predicate.TestnetPosition(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEvents applies the HasEdge predicate on the "events" edge.
func HasEvents() predicate.TestnetPosition {
	return predicate.TestnetPosition(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EventsTable, EventsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEventsWith applies the HasEdge predicate on the "events" edge with a given conditions (other predicates).
func HasEventsWith(preds ...predicate.TestnetTradeEvent) predicate.TestnetPosition {
	return predicate.TestnetPosition(func(s *sql.Selector) {
		step := newEventsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TestnetPosition) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TestnetPosition) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TestnetPosition) predicate.TestnetPosition {
	return predicate.TestnetPosition(sql.NotPredicates(p))
}
