// Code generated by ent, DO NOT EDIT.

package analysishistory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the analysishistory type in the database.
	Label = "analysis_history"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCoin holds the string denoting the coin field in the database.
	FieldCoin = "coin"
	// FieldTimestamp holds the string denoting the timestamp field in the database.
	FieldTimestamp = "timestamp"
	// FieldCurrentPrice holds the string denoting the current_price field in the database.
	FieldCurrentPrice = "current_price"
	// FieldBias holds the string denoting the bias field in the database.
	FieldBias = "bias"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// FieldConfidence holds the string denoting the confidence field in the database.
	FieldConfidence = "confidence"
	// FieldNarrative holds the string denoting the narrative field in the database.
	FieldNarrative = "narrative"
	// FieldComparison holds the string denoting the comparison field in the database.
	FieldComparison = "comparison"
	// FieldMarketSentiment holds the string denoting the market_sentiment field in the database.
	FieldMarketSentiment = "market_sentiment"
	// FieldDisclaimer holds the string denoting the disclaimer field in the database.
	FieldDisclaimer = "disclaimer"
	// FieldMethodID holds the string denoting the method_id field in the database.
	FieldMethodID = "method_id"
	// FieldBreakoutRetest holds the string denoting the breakout_retest field in the database.
	FieldBreakoutRetest = "breakout_retest"
	// FieldPositionDecisions holds the string denoting the position_decisions field in the database.
	FieldPositionDecisions = "position_decisions"
	// FieldAlternativeScenario holds the string denoting the alternative_scenario field in the database.
	FieldAlternativeScenario = "alternative_scenario"
	// FieldSuggestedEntry holds the string denoting the suggested_entry field in the database.
	FieldSuggestedEntry = "suggested_entry"
	// FieldSuggestedStopLoss holds the string denoting the suggested_stop_loss field in the database.
	FieldSuggestedStopLoss = "suggested_stop_loss"
	// FieldSuggestedTakeProfit holds the string denoting the suggested_take_profit field in the database.
	FieldSuggestedTakeProfit = "suggested_take_profit"
	// FieldExpectedRr holds the string denoting the expected_rr field in the database.
	FieldExpectedRr = "expected_rr"
	// FieldInvalidationLevel holds the string denoting the invalidation_level field in the database.
	FieldInvalidationLevel = "invalidation_level"
	// FieldRawQuestion holds the string denoting the raw_question field in the database.
	FieldRawQuestion = "raw_question"
	// FieldRawAnswer holds the string denoting the raw_answer field in the database.
	FieldRawAnswer = "raw_answer"
	// EdgePredictions holds the string denoting the predictions edge name in mutations.
	EdgePredictions = "predictions"
	// EdgeKeyLevels holds the string denoting the key_levels edge name in mutations.
	EdgeKeyLevels = "key_levels"
	// Table holds the table name of the analysishistory in the database.
	Table = "analysis_histories"
	// PredictionsTable is the table that holds the predictions relation/edge.
	PredictionsTable = "predictions"
	// PredictionsInverseTable is the table name for the Prediction entity.
	// It exists in this package in order to avoid circular dependency with the "prediction" package.
	PredictionsInverseTable = "predictions"
	// PredictionsColumn is the table column denoting the predictions relation/edge.
	PredictionsColumn = "analysis_id"
	// KeyLevelsTable is the table that holds the key_levels relation/edge.
	KeyLevelsTable = "key_levels"
	// KeyLevelsInverseTable is the table name for the KeyLevels entity.
	// It exists in this package in order to avoid circular dependency with the "keylevels" package.
	KeyLevelsInverseTable = "key_levels"
	// KeyLevelsColumn is the table column denoting the key_levels relation/edge.
	KeyLevelsColumn = "analysis_id"
)

// Columns holds all SQL columns for analysishistory fields.
var Columns = []string{
	FieldID,
	FieldCoin,
	FieldTimestamp,
	FieldCurrentPrice,
	FieldBias,
	FieldAction,
	FieldConfidence,
	FieldNarrative,
	FieldComparison,
	FieldMarketSentiment,
	FieldDisclaimer,
	FieldMethodID,
	FieldBreakoutRetest,
	FieldPositionDecisions,
	FieldAlternativeScenario,
	FieldSuggestedEntry,
	FieldSuggestedStopLoss,
	FieldSuggestedTakeProfit,
	FieldExpectedRr,
	FieldInvalidationLevel,
	FieldRawQuestion,
	FieldRawAnswer,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// CoinValidator is a validator for the "coin" field. It is called by the builders before save.
	CoinValidator func(string) error
	// DefaultTimestamp holds the default value on creation for the "timestamp" field.
	DefaultTimestamp func() time.Time
	// BiasValidator is a validator for the "bias" field. It is called by the builders before save.
	BiasValidator func(string) error
	// ActionValidator is a validator for the "action" field. It is called by the builders before save.
	ActionValidator func(string) error
	// DefaultMethodID holds the default value on creation for the "method_id" field.
	DefaultMethodID string
	// MethodIDValidator is a validator for the "method_id" field. It is called by the builders before save.
	MethodIDValidator func(string) error
)

// OrderOption defines the ordering options for the AnalysisHistory queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCoin orders the results by the coin field.
func ByCoin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCoin, opts...).ToFunc()
}

// ByTimestamp orders the results by the timestamp field.
func ByTimestamp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimestamp, opts...).ToFunc()
}

// ByCurrentPrice orders the results by the current_price field.
func ByCurrentPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentPrice, opts...).ToFunc()
}

// ByBias orders the results by the bias field.
func ByBias(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBias, opts...).ToFunc()
}

// ByAction orders the results by the action field.
func ByAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAction, opts...).ToFunc()
}

// ByConfidence orders the results by the confidence field.
func ByConfidence(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfidence, opts...).ToFunc()
}

// ByNarrative orders the results by the narrative field.
func ByNarrative(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNarrative, opts...).ToFunc()
}

// ByComparison orders the results by the comparison field.
func ByComparison(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldComparison, opts...).ToFunc()
}

// ByMarketSentiment orders the results by the market_sentiment field.
func ByMarketSentiment(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMarketSentiment, opts...).ToFunc()
}

// ByDisclaimer orders the results by the disclaimer field.
func ByDisclaimer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisclaimer, opts...).ToFunc()
}

// ByMethodID orders the results by the method_id field.
func ByMethodID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMethodID, opts...).ToFunc()
}

// ByBreakoutRetest orders the results by the breakout_retest field.
func ByBreakoutRetest(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBreakoutRetest, opts...).ToFunc()
}

// ByPositionDecisions orders the results by the position_decisions field.
func ByPositionDecisions(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPositionDecisions, opts...).ToFunc()
}

// ByAlternativeScenario orders the results by the alternative_scenario field.
func ByAlternativeScenario(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlternativeScenario, opts...).ToFunc()
}

// BySuggestedEntry orders the results by the suggested_entry field.
func BySuggestedEntry(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuggestedEntry, opts...).ToFunc()
}

// BySuggestedStopLoss orders the results by the suggested_stop_loss field.
func BySuggestedStopLoss(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuggestedStopLoss, opts...).ToFunc()
}

// BySuggestedTakeProfit orders the results by the suggested_take_profit field.
func BySuggestedTakeProfit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuggestedTakeProfit, opts...).ToFunc()
}

// ByExpectedRr orders the results by the expected_rr field.
func ByExpectedRr(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpectedRr, opts...).ToFunc()
}

// ByInvalidationLevel orders the results by the invalidation_level field.
func ByInvalidationLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvalidationLevel, opts...).ToFunc()
}

// ByRawQuestion orders the results by the raw_question field.
func ByRawQuestion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRawQuestion, opts...).ToFunc()
}

// ByRawAnswer orders the results by the raw_answer field.
func ByRawAnswer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRawAnswer, opts...).ToFunc()
}

// ByPredictionsCount orders the results by predictions count.
func ByPredictionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPredictionsStep(), opts...)
	}
}

// ByPredictions orders the results by predictions terms.
func ByPredictions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPredictionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByKeyLevelsCount orders the results by key_levels count.
func ByKeyLevelsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newKeyLevelsStep(), opts...)
	}
}

// ByKeyLevels orders the results by key_levels terms.
func ByKeyLevels(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newKeyLevelsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPredictionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PredictionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PredictionsTable, PredictionsColumn),
	)
}
func newKeyLevelsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(KeyLevelsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, KeyLevelsTable, KeyLevelsColumn),
	)
}
