// Code generated by ent, DO NOT EDIT.

package analysishistory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/chuyen-gia-crypto/backend/internal/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLTE(FieldID, id))
}

// Coin applies equality check predicate on the "coin" field. It's identical to CoinEQ.
func Coin(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldCoin, v))
}

// Timestamp applies equality check predicate on the "timestamp" field. It's identical to TimestampEQ.
func Timestamp(v time.Time) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldTimestamp, v))
}

// CurrentPrice applies equality check predicate on the "current_price" field. It's identical to CurrentPriceEQ.
func CurrentPrice(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldCurrentPrice, v))
}

// Bias applies equality check predicate on the "bias" field. It's identical to BiasEQ.
func Bias(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldBias, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldAction, v))
}

// Confidence applies equality check predicate on the "confidence" field. It's identical to ConfidenceEQ.
func Confidence(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldConfidence, v))
}

// Narrative applies equality check predicate on the "narrative" field. It's identical to NarrativeEQ.
func Narrative(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldNarrative, v))
}

// Comparison applies equality check predicate on the "comparison" field. It's identical to ComparisonEQ.
func Comparison(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldComparison, v))
}

// MarketSentiment applies equality check predicate on the "market_sentiment" field. It's identical to MarketSentimentEQ.
func MarketSentiment(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldMarketSentiment, v))
}

// Disclaimer applies equality check predicate on the "disclaimer" field. It's identical to DisclaimerEQ.
func Disclaimer(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldDisclaimer, v))
}

// MethodID applies equality check predicate on the "method_id" field. It's identical to MethodIDEQ.
func MethodID(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldMethodID, v))
}

// BreakoutRetest applies equality check predicate on the "breakout_retest" field. It's identical to BreakoutRetestEQ.
func BreakoutRetest(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldBreakoutRetest, v))
}

// PositionDecisions applies equality check predicate on the "position_decisions" field. It's identical to PositionDecisionsEQ.
func PositionDecisions(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldPositionDecisions, v))
}

// AlternativeScenario applies equality check predicate on the "alternative_scenario" field. It's identical to AlternativeScenarioEQ.
func AlternativeScenario(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldAlternativeScenario, v))
}

// SuggestedEntry applies equality check predicate on the "suggested_entry" field. It's identical to SuggestedEntryEQ.
func SuggestedEntry(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldSuggestedEntry, v))
}

// SuggestedStopLoss applies equality check predicate on the "suggested_stop_loss" field. It's identical to SuggestedStopLossEQ.
func SuggestedStopLoss(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldSuggestedStopLoss, v))
}

// SuggestedTakeProfit applies equality check predicate on the "suggested_take_profit" field. It's identical to SuggestedTakeProfitEQ.
func SuggestedTakeProfit(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldSuggestedTakeProfit, v))
}

// ExpectedRr applies equality check predicate on the "expected_rr" field. It's identical to ExpectedRrEQ.
func ExpectedRr(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldExpectedRr, v))
}

// InvalidationLevel applies equality check predicate on the "invalidation_level" field. It's identical to InvalidationLevelEQ.
func InvalidationLevel(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldInvalidationLevel, v))
}

// RawQuestion applies equality check predicate on the "raw_question" field. It's identical to RawQuestionEQ.
func RawQuestion(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldRawQuestion, v))
}

// RawAnswer applies equality check predicate on the "raw_answer" field. It's identical to RawAnswerEQ.
func RawAnswer(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldRawAnswer, v))
}

// CoinEQ applies the EQ predicate on the "coin" field.
func CoinEQ(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldCoin, v))
}

// CoinNEQ applies the NEQ predicate on the "coin" field.
func CoinNEQ(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNEQ(FieldCoin, v))
}

// CoinIn applies the In predicate on the "coin" field.
func CoinIn(vs ...string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIn(FieldCoin, vs...))
}

// CoinNotIn applies the NotIn predicate on the "coin" field.
func CoinNotIn(vs ...string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotIn(FieldCoin, vs...))
}

// CoinGT applies the GT predicate on the "coin" field.
func CoinGT(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGT(FieldCoin, v))
}

// CoinGTE applies the GTE predicate on the "coin" field.
func CoinGTE(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGTE(FieldCoin, v))
}

// CoinLT applies the LT predicate on the "coin" field.
func CoinLT(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLT(FieldCoin, v))
}

// CoinLTE applies the LTE predicate on the "coin" field.
func CoinLTE(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLTE(FieldCoin, v))
}

// CoinContains applies the Contains predicate on the "coin" field.
func CoinContains(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldContains(FieldCoin, v))
}

// CoinHasPrefix applies the HasPrefix predicate on the "coin" field.
func CoinHasPrefix(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldHasPrefix(FieldCoin, v))
}

// CoinHasSuffix applies the HasSuffix predicate on the "coin" field.
func CoinHasSuffix(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldHasSuffix(FieldCoin, v))
}

// CoinEqualFold applies the EqualFold predicate on the "coin" field.
func CoinEqualFold(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEqualFold(FieldCoin, v))
}

// CoinContainsFold applies the ContainsFold predicate on the "coin" field.
func CoinContainsFold(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldContainsFold(FieldCoin, v))
}

// TimestampEQ applies the EQ predicate on the "timestamp" field.
func TimestampEQ(v time.Time) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldTimestamp, v))
}

// TimestampNEQ applies the NEQ predicate on the "timestamp" field.
func TimestampNEQ(v time.Time) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNEQ(FieldTimestamp, v))
}

// TimestampIn applies the In predicate on the "timestamp" field.
func TimestampIn(vs ...time.Time) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIn(FieldTimestamp, vs...))
}

// TimestampNotIn applies the NotIn predicate on the "timestamp" field.
func TimestampNotIn(vs ...time.Time) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotIn(FieldTimestamp, vs...))
}

// TimestampGT applies the GT predicate on the "timestamp" field.
func TimestampGT(v time.Time) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGT(FieldTimestamp, v))
}

// TimestampGTE applies the GTE predicate on the "timestamp" field.
func TimestampGTE(v time.Time) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGTE(FieldTimestamp, v))
}

// TimestampLT applies the LT predicate on the "timestamp" field.
func TimestampLT(v time.Time) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLT(FieldTimestamp, v))
}

// TimestampLTE applies the LTE predicate on the "timestamp" field.
func TimestampLTE(v time.Time) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLTE(FieldTimestamp, v))
}

// CurrentPriceEQ applies the EQ predicate on the "current_price" field.
func CurrentPriceEQ(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldCurrentPrice, v))
}

// CurrentPriceNEQ applies the NEQ predicate on the "current_price" field.
func CurrentPriceNEQ(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNEQ(FieldCurrentPrice, v))
}

// CurrentPriceIn applies the In predicate on the "current_price" field.
func CurrentPriceIn(vs ...float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIn(FieldCurrentPrice, vs...))
}

// CurrentPriceNotIn applies the NotIn predicate on the "current_price" field.
func CurrentPriceNotIn(vs ...float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotIn(FieldCurrentPrice, vs...))
}

// CurrentPriceGT applies the GT predicate on the "current_price" field.
func CurrentPriceGT(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGT(FieldCurrentPrice, v))
}

// CurrentPriceGTE applies the GTE predicate on the "current_price" field.
func CurrentPriceGTE(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGTE(FieldCurrentPrice, v))
}

// CurrentPriceLT applies the LT predicate on the "current_price" field.
func CurrentPriceLT(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLT(FieldCurrentPrice, v))
}

// CurrentPriceLTE applies the LTE predicate on the "current_price" field.
func CurrentPriceLTE(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLTE(FieldCurrentPrice, v))
}

// BiasEQ applies the EQ predicate on the "bias" field.
func BiasEQ(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldBias, v))
}

// BiasNEQ applies the NEQ predicate on the "bias" field.
func BiasNEQ(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNEQ(FieldBias, v))
}

// BiasIn applies the In predicate on the "bias" field.
func BiasIn(vs ...string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIn(FieldBias, vs...))
}

// BiasNotIn applies the NotIn predicate on the "bias" field.
func BiasNotIn(vs ...string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotIn(FieldBias, vs...))
}

// BiasGT applies the GT predicate on the "bias" field.
func BiasGT(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGT(FieldBias, v))
}

// BiasGTE applies the GTE predicate on the "bias" field.
func BiasGTE(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGTE(FieldBias, v))
}

// BiasLT applies the LT predicate on the "bias" field.
func BiasLT(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLT(FieldBias, v))
}

// BiasLTE applies the LTE predicate on the "bias" field.
func BiasLTE(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLTE(FieldBias, v))
}

// BiasContains applies the Contains predicate on the "bias" field.
func BiasContains(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldContains(FieldBias, v))
}

// BiasHasPrefix applies the HasPrefix predicate on the "bias" field.
func BiasHasPrefix(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldHasPrefix(FieldBias, v))
}

// BiasHasSuffix applies the HasSuffix predicate on the "bias" field.
func BiasHasSuffix(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldHasSuffix(FieldBias, v))
}

// BiasEqualFold applies the EqualFold predicate on the "bias" field.
func BiasEqualFold(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEqualFold(FieldBias, v))
}

// BiasContainsFold applies the ContainsFold predicate on the "bias" field.
func BiasContainsFold(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldContainsFold(FieldBias, v))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldHasSuffix(FieldAction, v))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldContainsFold(FieldAction, v))
}

// ConfidenceEQ applies the EQ predicate on the "confidence" field.
func ConfidenceEQ(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldConfidence, v))
}

// ConfidenceNEQ applies the NEQ predicate on the "confidence" field.
func ConfidenceNEQ(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNEQ(FieldConfidence, v))
}

// ConfidenceIn applies the In predicate on the "confidence" field.
func ConfidenceIn(vs ...float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIn(FieldConfidence, vs...))
}

// ConfidenceNotIn applies the NotIn predicate on the "confidence" field.
func ConfidenceNotIn(vs ...float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotIn(FieldConfidence, vs...))
}

// ConfidenceGT applies the GT predicate on the "confidence" field.
func ConfidenceGT(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGT(FieldConfidence, v))
}

// ConfidenceGTE applies the GTE predicate on the "confidence" field.
func ConfidenceGTE(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGTE(FieldConfidence, v))
}

// ConfidenceLT applies the LT predicate on the "confidence" field.
func ConfidenceLT(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLT(FieldConfidence, v))
}

// ConfidenceLTE applies the LTE predicate on the "confidence" field.
func ConfidenceLTE(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLTE(FieldConfidence, v))
}

// NarrativeEQ applies the EQ predicate on the "narrative" field.
func NarrativeEQ(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldNarrative, v))
}

// NarrativeNEQ applies the NEQ predicate on the "narrative" field.
func NarrativeNEQ(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNEQ(FieldNarrative, v))
}

// NarrativeIn applies the In predicate on the "narrative" field.
func NarrativeIn(vs ...string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIn(FieldNarrative, vs...))
}

// NarrativeNotIn applies the NotIn predicate on the "narrative" field.
func NarrativeNotIn(vs ...string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotIn(FieldNarrative, vs...))
}

// NarrativeGT applies the GT predicate on the "narrative" field.
func NarrativeGT(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGT(FieldNarrative, v))
}

// NarrativeGTE applies the GTE predicate on the "narrative" field.
func NarrativeGTE(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGTE(FieldNarrative, v))
}

// NarrativeLT applies the LT predicate on the "narrative" field.
func NarrativeLT(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLT(FieldNarrative, v))
}

// NarrativeLTE applies the LTE predicate on the "narrative" field.
func NarrativeLTE(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLTE(FieldNarrative, v))
}

// NarrativeContains applies the Contains predicate on the "narrative" field.
func NarrativeContains(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldContains(FieldNarrative, v))
}

// NarrativeHasPrefix applies the HasPrefix predicate on the "narrative" field.
func NarrativeHasPrefix(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldHasPrefix(FieldNarrative, v))
}

// NarrativeHasSuffix applies the HasSuffix predicate on the "narrative" field.
func NarrativeHasSuffix(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldHasSuffix(FieldNarrative, v))
}

// NarrativeIsNil applies the IsNil predicate on the "narrative" field.
func NarrativeIsNil() predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIsNull(FieldNarrative))
}

// NarrativeNotNil applies the NotNil predicate on the "narrative" field.
func NarrativeNotNil() predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotNull(FieldNarrative))
}

// NarrativeEqualFold applies the EqualFold predicate on the "narrative" field.
func NarrativeEqualFold(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEqualFold(FieldNarrative, v))
}

// NarrativeContainsFold applies the ContainsFold predicate on the "narrative" field.
func NarrativeContainsFold(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldContainsFold(FieldNarrative, v))
}

// ComparisonEQ applies the EQ predicate on the "comparison" field.
func ComparisonEQ(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldComparison, v))
}

// ComparisonNEQ applies the NEQ predicate on the "comparison" field.
func ComparisonNEQ(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNEQ(FieldComparison, v))
}

// ComparisonIn applies the In predicate on the "comparison" field.
func ComparisonIn(vs ...string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIn(FieldComparison, vs...))
}

// ComparisonNotIn applies the NotIn predicate on the "comparison" field.
func ComparisonNotIn(vs ...string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotIn(FieldComparison, vs...))
}

// ComparisonGT applies the GT predicate on the "comparison" field.
func ComparisonGT(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGT(FieldComparison, v))
}

// ComparisonGTE applies the GTE predicate on the "comparison" field.
func ComparisonGTE(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGTE(FieldComparison, v))
}

// ComparisonLT applies the LT predicate on the "comparison" field.
func ComparisonLT(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLT(FieldComparison, v))
}

// ComparisonLTE applies the LTE predicate on the "comparison" field.
func ComparisonLTE(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLTE(FieldComparison, v))
}

// ComparisonContains applies the Contains predicate on the "comparison" field.
func ComparisonContains(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldContains(FieldComparison, v))
}

// ComparisonHasPrefix applies the HasPrefix predicate on the "comparison" field.
func ComparisonHasPrefix(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldHasPrefix(FieldComparison, v))
}

// ComparisonHasSuffix applies the HasSuffix predicate on the "comparison" field.
func ComparisonHasSuffix(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldHasSuffix(FieldComparison, v))
}

// ComparisonIsNil applies the IsNil predicate on the "comparison" field.
func ComparisonIsNil() predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIsNull(FieldComparison))
}

// ComparisonNotNil applies the NotNil predicate on the "comparison" field.
func ComparisonNotNil() predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotNull(FieldComparison))
}

// ComparisonEqualFold applies the EqualFold predicate on the "comparison" field.
func ComparisonEqualFold(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEqualFold(FieldComparison, v))
}

// ComparisonContainsFold applies the ContainsFold predicate on the "comparison" field.
func ComparisonContainsFold(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldContainsFold(FieldComparison, v))
}

// MarketSentimentEQ applies the EQ predicate on the "market_sentiment" field.
func MarketSentimentEQ(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldMarketSentiment, v))
}

// MarketSentimentNEQ applies the NEQ predicate on the "market_sentiment" field.
func MarketSentimentNEQ(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNEQ(FieldMarketSentiment, v))
}

// MarketSentimentIn applies the In predicate on the "market_sentiment" field.
func MarketSentimentIn(vs ...string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIn(FieldMarketSentiment, vs...))
}

// MarketSentimentNotIn applies the NotIn predicate on the "market_sentiment" field.
func MarketSentimentNotIn(vs ...string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotIn(FieldMarketSentiment, vs...))
}

// MarketSentimentGT applies the GT predicate on the "market_sentiment" field.
func MarketSentimentGT(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGT(FieldMarketSentiment, v))
}

// MarketSentimentGTE applies the GTE predicate on the "market_sentiment" field.
func MarketSentimentGTE(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGTE(FieldMarketSentiment, v))
}

// MarketSentimentLT applies the LT predicate on the "market_sentiment" field.
func MarketSentimentLT(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLT(FieldMarketSentiment, v))
}

// MarketSentimentLTE applies the LTE predicate on the "market_sentiment" field.
func MarketSentimentLTE(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLTE(FieldMarketSentiment, v))
}

// MarketSentimentContains applies the Contains predicate on the "market_sentiment" field.
func MarketSentimentContains(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldContains(FieldMarketSentiment, v))
}

// MarketSentimentHasPrefix applies the HasPrefix predicate on the "market_sentiment" field.
func MarketSentimentHasPrefix(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldHasPrefix(FieldMarketSentiment, v))
}

// MarketSentimentHasSuffix applies the HasSuffix predicate on the "market_sentiment" field.
func MarketSentimentHasSuffix(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldHasSuffix(FieldMarketSentiment, v))
}

// MarketSentimentIsNil applies the IsNil predicate on the "market_sentiment" field.
func MarketSentimentIsNil() predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIsNull(FieldMarketSentiment))
}

// MarketSentimentNotNil applies the NotNil predicate on the "market_sentiment" field.
func MarketSentimentNotNil() predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotNull(FieldMarketSentiment))
}

// MarketSentimentEqualFold applies the EqualFold predicate on the "market_sentiment" field.
func MarketSentimentEqualFold(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEqualFold(FieldMarketSentiment, v))
}

// MarketSentimentContainsFold applies the ContainsFold predicate on the "market_sentiment" field.
func MarketSentimentContainsFold(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldContainsFold(FieldMarketSentiment, v))
}

// DisclaimerEQ applies the EQ predicate on the "disclaimer" field.
func DisclaimerEQ(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldDisclaimer, v))
}

// DisclaimerNEQ applies the NEQ predicate on the "disclaimer" field.
func DisclaimerNEQ(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNEQ(FieldDisclaimer, v))
}

// DisclaimerIn applies the In predicate on the "disclaimer" field.
func DisclaimerIn(vs ...string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIn(FieldDisclaimer, vs...))
}

// DisclaimerNotIn applies the NotIn predicate on the "disclaimer" field.
func DisclaimerNotIn(vs ...string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotIn(FieldDisclaimer, vs...))
}

// DisclaimerGT applies the GT predicate on the "disclaimer" field.
func DisclaimerGT(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGT(FieldDisclaimer, v))
}

// DisclaimerGTE applies the GTE predicate on the "disclaimer" field.
func DisclaimerGTE(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGTE(FieldDisclaimer, v))
}

// DisclaimerLT applies the LT predicate on the "disclaimer" field.
func DisclaimerLT(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLT(FieldDisclaimer, v))
}

// DisclaimerLTE applies the LTE predicate on the "disclaimer" field.
func DisclaimerLTE(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLTE(FieldDisclaimer, v))
}

// DisclaimerContains applies the Contains predicate on the "disclaimer" field.
func DisclaimerContains(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldContains(FieldDisclaimer, v))
}

// DisclaimerHasPrefix applies the HasPrefix predicate on the "disclaimer" field.
func DisclaimerHasPrefix(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldHasPrefix(FieldDisclaimer, v))
}

// DisclaimerHasSuffix applies the HasSuffix predicate on the "disclaimer" field.
func DisclaimerHasSuffix(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldHasSuffix(FieldDisclaimer, v))
}

// DisclaimerIsNil applies the IsNil predicate on the "disclaimer" field.
func DisclaimerIsNil() predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIsNull(FieldDisclaimer))
}

// DisclaimerNotNil applies the NotNil predicate on the "disclaimer" field.
func DisclaimerNotNil() predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotNull(FieldDisclaimer))
}

// DisclaimerEqualFold applies the EqualFold predicate on the "disclaimer" field.
func DisclaimerEqualFold(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEqualFold(FieldDisclaimer, v))
}

// DisclaimerContainsFold applies the ContainsFold predicate on the "disclaimer" field.
func DisclaimerContainsFold(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldContainsFold(FieldDisclaimer, v))
}

// MethodIDEQ applies the EQ predicate on the "method_id" field.
func MethodIDEQ(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldMethodID, v))
}

// MethodIDNEQ applies the NEQ predicate on the "method_id" field.
func MethodIDNEQ(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNEQ(FieldMethodID, v))
}

// MethodIDIn applies the In predicate on the "method_id" field.
func MethodIDIn(vs ...string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIn(FieldMethodID, vs...))
}

// MethodIDNotIn applies the NotIn predicate on the "method_id" field.
func MethodIDNotIn(vs ...string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotIn(FieldMethodID, vs...))
}

// MethodIDGT applies the GT predicate on the "method_id" field.
func MethodIDGT(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGT(FieldMethodID, v))
}

// MethodIDGTE applies the GTE predicate on the "method_id" field.
func MethodIDGTE(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGTE(FieldMethodID, v))
}

// MethodIDLT applies the LT predicate on the "method_id" field.
func MethodIDLT(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLT(FieldMethodID, v))
}

// MethodIDLTE applies the LTE predicate on the "method_id" field.
func MethodIDLTE(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLTE(FieldMethodID, v))
}

// MethodIDContains applies the Contains predicate on the "method_id" field.
func MethodIDContains(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldContains(FieldMethodID, v))
}

// MethodIDHasPrefix applies the HasPrefix predicate on the "method_id" field.
func MethodIDHasPrefix(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldHasPrefix(FieldMethodID, v))
}

// MethodIDHasSuffix applies the HasSuffix predicate on the "method_id" field.
func MethodIDHasSuffix(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldHasSuffix(FieldMethodID, v))
}

// MethodIDEqualFold applies the EqualFold predicate on the "method_id" field.
func MethodIDEqualFold(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEqualFold(FieldMethodID, v))
}

// MethodIDContainsFold applies the ContainsFold predicate on the "method_id" field.
func MethodIDContainsFold(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldContainsFold(FieldMethodID, v))
}

// BreakoutRetestEQ applies the EQ predicate on the "breakout_retest" field.
func BreakoutRetestEQ(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldBreakoutRetest, v))
}

// BreakoutRetestNEQ applies the NEQ predicate on the "breakout_retest" field.
func BreakoutRetestNEQ(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNEQ(FieldBreakoutRetest, v))
}

// BreakoutRetestIn applies the In predicate on the "breakout_retest" field.
func BreakoutRetestIn(vs ...string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIn(FieldBreakoutRetest, vs...))
}

// BreakoutRetestNotIn applies the NotIn predicate on the "breakout_retest" field.
func BreakoutRetestNotIn(vs ...string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotIn(FieldBreakoutRetest, vs...))
}

// BreakoutRetestGT applies the GT predicate on the "breakout_retest" field.
func BreakoutRetestGT(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGT(FieldBreakoutRetest, v))
}

// BreakoutRetestGTE applies the GTE predicate on the "breakout_retest" field.
func BreakoutRetestGTE(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGTE(FieldBreakoutRetest, v))
}

// BreakoutRetestLT applies the LT predicate on the "breakout_retest" field.
func BreakoutRetestLT(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLT(FieldBreakoutRetest, v))
}

// BreakoutRetestLTE applies the LTE predicate on the "breakout_retest" field.
func BreakoutRetestLTE(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLTE(FieldBreakoutRetest, v))
}

// BreakoutRetestContains applies the Contains predicate on the "breakout_retest" field.
func BreakoutRetestContains(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldContains(FieldBreakoutRetest, v))
}

// BreakoutRetestHasPrefix applies the HasPrefix predicate on the "breakout_retest" field.
func BreakoutRetestHasPrefix(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldHasPrefix(FieldBreakoutRetest, v))
}

// BreakoutRetestHasSuffix applies the HasSuffix predicate on the "breakout_retest" field.
func BreakoutRetestHasSuffix(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldHasSuffix(FieldBreakoutRetest, v))
}

// BreakoutRetestIsNil applies the IsNil predicate on the "breakout_retest" field.
func BreakoutRetestIsNil() predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIsNull(FieldBreakoutRetest))
}

// BreakoutRetestNotNil applies the NotNil predicate on the "breakout_retest" field.
func BreakoutRetestNotNil() predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotNull(FieldBreakoutRetest))
}

// BreakoutRetestEqualFold applies the EqualFold predicate on the "breakout_retest" field.
func BreakoutRetestEqualFold(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEqualFold(FieldBreakoutRetest, v))
}

// BreakoutRetestContainsFold applies the ContainsFold predicate on the "breakout_retest" field.
func BreakoutRetestContainsFold(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldContainsFold(FieldBreakoutRetest, v))
}

// PositionDecisionsEQ applies the EQ predicate on the "position_decisions" field.
func PositionDecisionsEQ(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldPositionDecisions, v))
}

// PositionDecisionsNEQ applies the NEQ predicate on the "position_decisions" field.
func PositionDecisionsNEQ(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNEQ(FieldPositionDecisions, v))
}

// PositionDecisionsIn applies the In predicate on the "position_decisions" field.
func PositionDecisionsIn(vs ...string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIn(FieldPositionDecisions, vs...))
}

// PositionDecisionsNotIn applies the NotIn predicate on the "position_decisions" field.
func PositionDecisionsNotIn(vs ...string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotIn(FieldPositionDecisions, vs...))
}

// PositionDecisionsGT applies the GT predicate on the "position_decisions" field.
func PositionDecisionsGT(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGT(FieldPositionDecisions, v))
}

// PositionDecisionsGTE applies the GTE predicate on the "position_decisions" field.
func PositionDecisionsGTE(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGTE(FieldPositionDecisions, v))
}

// PositionDecisionsLT applies the LT predicate on the "position_decisions" field.
func PositionDecisionsLT(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLT(FieldPositionDecisions, v))
}

// PositionDecisionsLTE applies the LTE predicate on the "position_decisions" field.
func PositionDecisionsLTE(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLTE(FieldPositionDecisions, v))
}

// PositionDecisionsContains applies the Contains predicate on the "position_decisions" field.
func PositionDecisionsContains(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldContains(FieldPositionDecisions, v))
}

// PositionDecisionsHasPrefix applies the HasPrefix predicate on the "position_decisions" field.
func PositionDecisionsHasPrefix(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldHasPrefix(FieldPositionDecisions, v))
}

// PositionDecisionsHasSuffix applies the HasSuffix predicate on the "position_decisions" field.
func PositionDecisionsHasSuffix(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldHasSuffix(FieldPositionDecisions, v))
}

// PositionDecisionsIsNil applies the IsNil predicate on the "position_decisions" field.
func PositionDecisionsIsNil() predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIsNull(FieldPositionDecisions))
}

// PositionDecisionsNotNil applies the NotNil predicate on the "position_decisions" field.
func PositionDecisionsNotNil() predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotNull(FieldPositionDecisions))
}

// PositionDecisionsEqualFold applies the EqualFold predicate on the "position_decisions" field.
func PositionDecisionsEqualFold(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEqualFold(FieldPositionDecisions, v))
}

// PositionDecisionsContainsFold applies the ContainsFold predicate on the "position_decisions" field.
func PositionDecisionsContainsFold(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldContainsFold(FieldPositionDecisions, v))
}

// AlternativeScenarioEQ applies the EQ predicate on the "alternative_scenario" field.
func AlternativeScenarioEQ(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldAlternativeScenario, v))
}

// AlternativeScenarioNEQ applies the NEQ predicate on the "alternative_scenario" field.
func AlternativeScenarioNEQ(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNEQ(FieldAlternativeScenario, v))
}

// AlternativeScenarioIn applies the In predicate on the "alternative_scenario" field.
func AlternativeScenarioIn(vs ...string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIn(FieldAlternativeScenario, vs...))
}

// AlternativeScenarioNotIn applies the NotIn predicate on the "alternative_scenario" field.
func AlternativeScenarioNotIn(vs ...string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotIn(FieldAlternativeScenario, vs...))
}

// AlternativeScenarioGT applies the GT predicate on the "alternative_scenario" field.
func AlternativeScenarioGT(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGT(FieldAlternativeScenario, v))
}

// AlternativeScenarioGTE applies the GTE predicate on the "alternative_scenario" field.
func AlternativeScenarioGTE(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGTE(FieldAlternativeScenario, v))
}

// AlternativeScenarioLT applies the LT predicate on the "alternative_scenario" field.
func AlternativeScenarioLT(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLT(FieldAlternativeScenario, v))
}

// AlternativeScenarioLTE applies the LTE predicate on the "alternative_scenario" field.
func AlternativeScenarioLTE(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLTE(FieldAlternativeScenario, v))
}

// AlternativeScenarioContains applies the Contains predicate on the "alternative_scenario" field.
func AlternativeScenarioContains(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldContains(FieldAlternativeScenario, v))
}

// AlternativeScenarioHasPrefix applies the HasPrefix predicate on the "alternative_scenario" field.
func AlternativeScenarioHasPrefix(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldHasPrefix(FieldAlternativeScenario, v))
}

// AlternativeScenarioHasSuffix applies the HasSuffix predicate on the "alternative_scenario" field.
func AlternativeScenarioHasSuffix(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldHasSuffix(FieldAlternativeScenario, v))
}

// AlternativeScenarioIsNil applies the IsNil predicate on the "alternative_scenario" field.
func AlternativeScenarioIsNil() predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIsNull(FieldAlternativeScenario))
}

// AlternativeScenarioNotNil applies the NotNil predicate on the "alternative_scenario" field.
func AlternativeScenarioNotNil() predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotNull(FieldAlternativeScenario))
}

// AlternativeScenarioEqualFold applies the EqualFold predicate on the "alternative_scenario" field.
func AlternativeScenarioEqualFold(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEqualFold(FieldAlternativeScenario, v))
}

// AlternativeScenarioContainsFold applies the ContainsFold predicate on the "alternative_scenario" field.
func AlternativeScenarioContainsFold(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldContainsFold(FieldAlternativeScenario, v))
}

// SuggestedEntryEQ applies the EQ predicate on the "suggested_entry" field.
func SuggestedEntryEQ(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldSuggestedEntry, v))
}

// SuggestedEntryNEQ applies the NEQ predicate on the "suggested_entry" field.
func SuggestedEntryNEQ(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNEQ(FieldSuggestedEntry, v))
}

// SuggestedEntryIn applies the In predicate on the "suggested_entry" field.
func SuggestedEntryIn(vs ...float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIn(FieldSuggestedEntry, vs...))
}

// SuggestedEntryNotIn applies the NotIn predicate on the "suggested_entry" field.
func SuggestedEntryNotIn(vs ...float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotIn(FieldSuggestedEntry, vs...))
}

// SuggestedEntryGT applies the GT predicate on the "suggested_entry" field.
func SuggestedEntryGT(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGT(FieldSuggestedEntry, v))
}

// SuggestedEntryGTE applies the GTE predicate on the "suggested_entry" field.
func SuggestedEntryGTE(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGTE(FieldSuggestedEntry, v))
}

// SuggestedEntryLT applies the LT predicate on the "suggested_entry" field.
func SuggestedEntryLT(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLT(FieldSuggestedEntry, v))
}

// SuggestedEntryLTE applies the LTE predicate on the "suggested_entry" field.
func SuggestedEntryLTE(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLTE(FieldSuggestedEntry, v))
}

// SuggestedEntryIsNil applies the IsNil predicate on the "suggested_entry" field.
func SuggestedEntryIsNil() predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIsNull(FieldSuggestedEntry))
}

// SuggestedEntryNotNil applies the NotNil predicate on the "suggested_entry" field.
func SuggestedEntryNotNil() predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotNull(FieldSuggestedEntry))
}

// SuggestedStopLossEQ applies the EQ predicate on the "suggested_stop_loss" field.
func SuggestedStopLossEQ(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldSuggestedStopLoss, v))
}

// SuggestedStopLossNEQ applies the NEQ predicate on the "suggested_stop_loss" field.
func SuggestedStopLossNEQ(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNEQ(FieldSuggestedStopLoss, v))
}

// SuggestedStopLossIn applies the In predicate on the "suggested_stop_loss" field.
func SuggestedStopLossIn(vs ...float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIn(FieldSuggestedStopLoss, vs...))
}

// SuggestedStopLossNotIn applies the NotIn predicate on the "suggested_stop_loss" field.
func SuggestedStopLossNotIn(vs ...float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotIn(FieldSuggestedStopLoss, vs...))
}

// SuggestedStopLossGT applies the GT predicate on the "suggested_stop_loss" field.
func SuggestedStopLossGT(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGT(FieldSuggestedStopLoss, v))
}

// SuggestedStopLossGTE applies the GTE predicate on the "suggested_stop_loss" field.
func SuggestedStopLossGTE(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGTE(FieldSuggestedStopLoss, v))
}

// SuggestedStopLossLT applies the LT predicate on the "suggested_stop_loss" field.
func SuggestedStopLossLT(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLT(FieldSuggestedStopLoss, v))
}

// SuggestedStopLossLTE applies the LTE predicate on the "suggested_stop_loss" field.
func SuggestedStopLossLTE(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLTE(FieldSuggestedStopLoss, v))
}

// SuggestedStopLossIsNil applies the IsNil predicate on the "suggested_stop_loss" field.
func SuggestedStopLossIsNil() predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIsNull(FieldSuggestedStopLoss))
}

// SuggestedStopLossNotNil applies the NotNil predicate on the "suggested_stop_loss" field.
func SuggestedStopLossNotNil() predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotNull(FieldSuggestedStopLoss))
}

// SuggestedTakeProfitEQ applies the EQ predicate on the "suggested_take_profit" field.
func SuggestedTakeProfitEQ(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldSuggestedTakeProfit, v))
}

// SuggestedTakeProfitNEQ applies the NEQ predicate on the "suggested_take_profit" field.
func SuggestedTakeProfitNEQ(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNEQ(FieldSuggestedTakeProfit, v))
}

// SuggestedTakeProfitIn applies the In predicate on the "suggested_take_profit" field.
func SuggestedTakeProfitIn(vs ...float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIn(FieldSuggestedTakeProfit, vs...))
}

// SuggestedTakeProfitNotIn applies the NotIn predicate on the "suggested_take_profit" field.
func SuggestedTakeProfitNotIn(vs ...float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotIn(FieldSuggestedTakeProfit, vs...))
}

// SuggestedTakeProfitGT applies the GT predicate on the "suggested_take_profit" field.
func SuggestedTakeProfitGT(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGT(FieldSuggestedTakeProfit, v))
}

// SuggestedTakeProfitGTE applies the GTE predicate on the "suggested_take_profit" field.
func SuggestedTakeProfitGTE(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGTE(FieldSuggestedTakeProfit, v))
}

// SuggestedTakeProfitLT applies the LT predicate on the "suggested_take_profit" field.
func SuggestedTakeProfitLT(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLT(FieldSuggestedTakeProfit, v))
}

// SuggestedTakeProfitLTE applies the LTE predicate on the "suggested_take_profit" field.
func SuggestedTakeProfitLTE(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLTE(FieldSuggestedTakeProfit, v))
}

// SuggestedTakeProfitIsNil applies the IsNil predicate on the "suggested_take_profit" field.
func SuggestedTakeProfitIsNil() predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIsNull(FieldSuggestedTakeProfit))
}

// SuggestedTakeProfitNotNil applies the NotNil predicate on the "suggested_take_profit" field.
func SuggestedTakeProfitNotNil() predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotNull(FieldSuggestedTakeProfit))
}

// ExpectedRrEQ applies the EQ predicate on the "expected_rr" field.
func ExpectedRrEQ(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldExpectedRr, v))
}

// ExpectedRrNEQ applies the NEQ predicate on the "expected_rr" field.
func ExpectedRrNEQ(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNEQ(FieldExpectedRr, v))
}

// ExpectedRrIn applies the In predicate on the "expected_rr" field.
func ExpectedRrIn(vs ...float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIn(FieldExpectedRr, vs...))
}

// ExpectedRrNotIn applies the NotIn predicate on the "expected_rr" field.
func ExpectedRrNotIn(vs ...float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotIn(FieldExpectedRr, vs...))
}

// ExpectedRrGT applies the GT predicate on the "expected_rr" field.
func ExpectedRrGT(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGT(FieldExpectedRr, v))
}

// ExpectedRrGTE applies the GTE predicate on the "expected_rr" field.
func ExpectedRrGTE(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGTE(FieldExpectedRr, v))
}

// ExpectedRrLT applies the LT predicate on the "expected_rr" field.
func ExpectedRrLT(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLT(FieldExpectedRr, v))
}

// ExpectedRrLTE applies the LTE predicate on the "expected_rr" field.
func ExpectedRrLTE(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLTE(FieldExpectedRr, v))
}

// ExpectedRrIsNil applies the IsNil predicate on the "expected_rr" field.
func ExpectedRrIsNil() predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIsNull(FieldExpectedRr))
}

// ExpectedRrNotNil applies the NotNil predicate on the "expected_rr" field.
func ExpectedRrNotNil() predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotNull(FieldExpectedRr))
}

// InvalidationLevelEQ applies the EQ predicate on the "invalidation_level" field.
func InvalidationLevelEQ(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldInvalidationLevel, v))
}

// InvalidationLevelNEQ applies the NEQ predicate on the "invalidation_level" field.
func InvalidationLevelNEQ(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNEQ(FieldInvalidationLevel, v))
}

// InvalidationLevelIn applies the In predicate on the "invalidation_level" field.
func InvalidationLevelIn(vs ...float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIn(FieldInvalidationLevel, vs...))
}

// InvalidationLevelNotIn applies the NotIn predicate on the "invalidation_level" field.
func InvalidationLevelNotIn(vs ...float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotIn(FieldInvalidationLevel, vs...))
}

// InvalidationLevelGT applies the GT predicate on the "invalidation_level" field.
func InvalidationLevelGT(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGT(FieldInvalidationLevel, v))
}

// InvalidationLevelGTE applies the GTE predicate on the "invalidation_level" field.
func InvalidationLevelGTE(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGTE(FieldInvalidationLevel, v))
}

// InvalidationLevelLT applies the LT predicate on the "invalidation_level" field.
func InvalidationLevelLT(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLT(FieldInvalidationLevel, v))
}

// InvalidationLevelLTE applies the LTE predicate on the "invalidation_level" field.
func InvalidationLevelLTE(v float64) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLTE(FieldInvalidationLevel, v))
}

// InvalidationLevelIsNil applies the IsNil predicate on the "invalidation_level" field.
func InvalidationLevelIsNil() predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIsNull(FieldInvalidationLevel))
}

// InvalidationLevelNotNil applies the NotNil predicate on the "invalidation_level" field.
func InvalidationLevelNotNil() predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotNull(FieldInvalidationLevel))
}

// RawQuestionEQ applies the EQ predicate on the "raw_question" field.
func RawQuestionEQ(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldRawQuestion, v))
}

// RawQuestionNEQ applies the NEQ predicate on the "raw_question" field.
func RawQuestionNEQ(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNEQ(FieldRawQuestion, v))
}

// RawQuestionIn applies the In predicate on the "raw_question" field.
func RawQuestionIn(vs ...string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIn(FieldRawQuestion, vs...))
}

// RawQuestionNotIn applies the NotIn predicate on the "raw_question" field.
func RawQuestionNotIn(vs ...string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotIn(FieldRawQuestion, vs...))
}

// RawQuestionGT applies the GT predicate on the "raw_question" field.
func RawQuestionGT(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGT(FieldRawQuestion, v))
}

// RawQuestionGTE applies the GTE predicate on the "raw_question" field.
func RawQuestionGTE(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGTE(FieldRawQuestion, v))
}

// RawQuestionLT applies the LT predicate on the "raw_question" field.
func RawQuestionLT(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLT(FieldRawQuestion, v))
}

// RawQuestionLTE applies the LTE predicate on the "raw_question" field.
func RawQuestionLTE(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLTE(FieldRawQuestion, v))
}

// RawQuestionContains applies the Contains predicate on the "raw_question" field.
func RawQuestionContains(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldContains(FieldRawQuestion, v))
}

// RawQuestionHasPrefix applies the HasPrefix predicate on the "raw_question" field.
func RawQuestionHasPrefix(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldHasPrefix(FieldRawQuestion, v))
}

// RawQuestionHasSuffix applies the HasSuffix predicate on the "raw_question" field.
func RawQuestionHasSuffix(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldHasSuffix(FieldRawQuestion, v))
}

// RawQuestionIsNil applies the IsNil predicate on the "raw_question" field.
func RawQuestionIsNil() predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIsNull(FieldRawQuestion))
}

// RawQuestionNotNil applies the NotNil predicate on the "raw_question" field.
func RawQuestionNotNil() predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotNull(FieldRawQuestion))
}

// RawQuestionEqualFold applies the EqualFold predicate on the "raw_question" field.
func RawQuestionEqualFold(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEqualFold(FieldRawQuestion, v))
}

// RawQuestionContainsFold applies the ContainsFold predicate on the "raw_question" field.
func RawQuestionContainsFold(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldContainsFold(FieldRawQuestion, v))
}

// RawAnswerEQ applies the EQ predicate on the "raw_answer" field.
func RawAnswerEQ(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEQ(FieldRawAnswer, v))
}

// RawAnswerNEQ applies the NEQ predicate on the "raw_answer" field.
func RawAnswerNEQ(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNEQ(FieldRawAnswer, v))
}

// RawAnswerIn applies the In predicate on the "raw_answer" field.
func RawAnswerIn(vs ...string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIn(FieldRawAnswer, vs...))
}

// RawAnswerNotIn applies the NotIn predicate on the "raw_answer" field.
func RawAnswerNotIn(vs ...string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotIn(FieldRawAnswer, vs...))
}

// RawAnswerGT applies the GT predicate on the "raw_answer" field.
func RawAnswerGT(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGT(FieldRawAnswer, v))
}

// RawAnswerGTE applies the GTE predicate on the "raw_answer" field.
func RawAnswerGTE(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldGTE(FieldRawAnswer, v))
}

// RawAnswerLT applies the LT predicate on the "raw_answer" field.
func RawAnswerLT(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLT(FieldRawAnswer, v))
}

// RawAnswerLTE applies the LTE predicate on the "raw_answer" field.
func RawAnswerLTE(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldLTE(FieldRawAnswer, v))
}

// RawAnswerContains applies the Contains predicate on the "raw_answer" field.
func RawAnswerContains(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldContains(FieldRawAnswer, v))
}

// RawAnswerHasPrefix applies the HasPrefix predicate on the "raw_answer" field.
func RawAnswerHasPrefix(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldHasPrefix(FieldRawAnswer, v))
}

// RawAnswerHasSuffix applies the HasSuffix predicate on the "raw_answer" field.
func RawAnswerHasSuffix(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldHasSuffix(FieldRawAnswer, v))
}

// RawAnswerIsNil applies the IsNil predicate on the "raw_answer" field.
func RawAnswerIsNil() predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldIsNull(FieldRawAnswer))
}

// RawAnswerNotNil applies the NotNil predicate on the "raw_answer" field.
func RawAnswerNotNil() predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldNotNull(FieldRawAnswer))
}

// RawAnswerEqualFold applies the EqualFold predicate on the "raw_answer" field.
func RawAnswerEqualFold(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldEqualFold(FieldRawAnswer, v))
}

// RawAnswerContainsFold applies the ContainsFold predicate on the "raw_answer" field.
func RawAnswerContainsFold(v string) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.FieldContainsFold(FieldRawAnswer, v))
}

// HasPredictions applies the HasEdge predicate on the "predictions" edge.
func HasPredictions() predicate.AnalysisHistory {
	return predicate.AnalysisHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PredictionsTable, PredictionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPredictionsWith applies the HasEdge predicate on the "predictions" edge with a given conditions (other predicates).
func HasPredictionsWith(preds ...predicate.Prediction) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(func(s *sql.Selector) {
		step := newPredictionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasKeyLevels applies the HasEdge predicate on the "key_levels" edge.
func HasKeyLevels() predicate.AnalysisHistory {
	return predicate.AnalysisHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, KeyLevelsTable, KeyLevelsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasKeyLevelsWith applies the HasEdge predicate on the "key_levels" edge with a given conditions (other predicates).
func HasKeyLevelsWith(preds ...predicate.KeyLevels) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(func(s *sql.Selector) {
		step := newKeyLevelsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AnalysisHistory) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AnalysisHistory) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AnalysisHistory) predicate.AnalysisHistory {
	return predicate.AnalysisHistory(sql.NotPredicates(p))
}
