// Code generated by ent, DO NOT EDIT.

package testnetaccountsnapshot

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/chuyen-gia-crypto/backend/internal/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldLTE(FieldID, id))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldEQ(FieldAccountID, v))
}

// Balance applies equality check predicate on the "balance" field. It's identical to BalanceEQ.
func Balance(v float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldEQ(FieldBalance, v))
}

// Equity applies equality check predicate on the "equity" field. It's identical to EquityEQ.
func Equity(v float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldEQ(FieldEquity, v))
}

// UnrealizedPnl applies equality check predicate on the "unrealized_pnl" field. It's identical to UnrealizedPnlEQ.
func UnrealizedPnl(v float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldEQ(FieldUnrealizedPnl, v))
}

// RealizedPnl applies equality check predicate on the "realized_pnl" field. It's identical to RealizedPnlEQ.
func RealizedPnl(v float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldEQ(FieldRealizedPnl, v))
}

// OpenPositionsCount applies equality check predicate on the "open_positions_count" field. It's identical to OpenPositionsCountEQ.
func OpenPositionsCount(v int) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldEQ(FieldOpenPositionsCount, v))
}

// Timestamp applies equality check predicate on the "timestamp" field. It's identical to TimestampEQ.
func Timestamp(v time.Time) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldEQ(FieldTimestamp, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldNotIn(FieldAccountID, vs...))
}

// BalanceEQ applies the EQ predicate on the "balance" field.
func BalanceEQ(v float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldEQ(FieldBalance, v))
}

// BalanceNEQ applies the NEQ predicate on the "balance" field.
func BalanceNEQ(v float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldNEQ(FieldBalance, v))
}

// BalanceIn applies the In predicate on the "balance" field.
func BalanceIn(vs ...float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldIn(FieldBalance, vs...))
}

// BalanceNotIn applies the NotIn predicate on the "balance" field.
func BalanceNotIn(vs ...float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldNotIn(FieldBalance, vs...))
}

// BalanceGT applies the GT predicate on the "balance" field.
func BalanceGT(v float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldGT(FieldBalance, v))
}

// BalanceGTE applies the GTE predicate on the "balance" field.
func BalanceGTE(v float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldGTE(FieldBalance, v))
}

// BalanceLT applies the LT predicate on the "balance" field.
func BalanceLT(v float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldLT(FieldBalance, v))
}

// BalanceLTE applies the LTE predicate on the "balance" field.
func BalanceLTE(v float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldLTE(FieldBalance, v))
}

// EquityEQ applies the EQ predicate on the "equity" field.
func EquityEQ(v float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldEQ(FieldEquity, v))
}

// EquityNEQ applies the NEQ predicate on the "equity" field.
func EquityNEQ(v float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldNEQ(FieldEquity, v))
}

// EquityIn applies the In predicate on the "equity" field.
func EquityIn(vs ...float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldIn(FieldEquity, vs...))
}

// EquityNotIn applies the NotIn predicate on the "equity" field.
func EquityNotIn(vs ...float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldNotIn(FieldEquity, vs...))
}

// EquityGT applies the GT predicate on the "equity" field.
func EquityGT(v float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldGT(FieldEquity, v))
}

// EquityGTE applies the GTE predicate on the "equity" field.
func EquityGTE(v float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldGTE(FieldEquity, v))
}

// EquityLT applies the LT predicate on the "equity" field.
func EquityLT(v float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldLT(FieldEquity, v))
}

// EquityLTE applies the LTE predicate on the "equity" field.
func EquityLTE(v float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldLTE(FieldEquity, v))
}

// UnrealizedPnlEQ applies the EQ predicate on the "unrealized_pnl" field.
func UnrealizedPnlEQ(v float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldEQ(FieldUnrealizedPnl, v))
}

// UnrealizedPnlNEQ applies the NEQ predicate on the "unrealized_pnl" field.
func UnrealizedPnlNEQ(v float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldNEQ(FieldUnrealizedPnl, v))
}

// UnrealizedPnlIn applies the In predicate on the "unrealized_pnl" field.
func UnrealizedPnlIn(vs ...float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldIn(FieldUnrealizedPnl, vs...))
}

// UnrealizedPnlNotIn applies the NotIn predicate on the "unrealized_pnl" field.
func UnrealizedPnlNotIn(vs ...float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldNotIn(FieldUnrealizedPnl, vs...))
}

// UnrealizedPnlGT applies the GT predicate on the "unrealized_pnl" field.
func UnrealizedPnlGT(v float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldGT(FieldUnrealizedPnl, v))
}

// UnrealizedPnlGTE applies the GTE predicate on the "unrealized_pnl" field.
func UnrealizedPnlGTE(v float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldGTE(FieldUnrealizedPnl, v))
}

// UnrealizedPnlLT applies the LT predicate on the "unrealized_pnl" field.
func UnrealizedPnlLT(v float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldLT(FieldUnrealizedPnl, v))
}

// UnrealizedPnlLTE applies the LTE predicate on the "unrealized_pnl" field.
func UnrealizedPnlLTE(v float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldLTE(FieldUnrealizedPnl, v))
}

// RealizedPnlEQ applies the EQ predicate on the "realized_pnl" field.
func RealizedPnlEQ(v float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldEQ(FieldRealizedPnl, v))
}

// RealizedPnlNEQ applies the NEQ predicate on the "realized_pnl" field.
func RealizedPnlNEQ(v float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldNEQ(FieldRealizedPnl, v))
}

// RealizedPnlIn applies the In predicate on the "realized_pnl" field.
func RealizedPnlIn(vs ...float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldIn(FieldRealizedPnl, vs...))
}

// RealizedPnlNotIn applies the NotIn predicate on the "realized_pnl" field.
func RealizedPnlNotIn(vs ...float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldNotIn(FieldRealizedPnl, vs...))
}

// RealizedPnlGT applies the GT predicate on the "realized_pnl" field.
func RealizedPnlGT(v float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldGT(FieldRealizedPnl, v))
}

// RealizedPnlGTE applies the GTE predicate on the "realized_pnl" field.
func RealizedPnlGTE(v float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldGTE(FieldRealizedPnl, v))
}

// RealizedPnlLT applies the LT predicate on the "realized_pnl" field.
func RealizedPnlLT(v float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldLT(FieldRealizedPnl, v))
}

// RealizedPnlLTE applies the LTE predicate on the "realized_pnl" field.
func RealizedPnlLTE(v float64) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldLTE(FieldRealizedPnl, v))
}

// OpenPositionsCountEQ applies the EQ predicate on the "open_positions_count" field.
func OpenPositionsCountEQ(v int) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldEQ(FieldOpenPositionsCount, v))
}

// OpenPositionsCountNEQ applies the NEQ predicate on the "open_positions_count" field.
func OpenPositionsCountNEQ(v int) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldNEQ(FieldOpenPositionsCount, v))
}

// OpenPositionsCountIn applies the In predicate on the "open_positions_count" field.
func OpenPositionsCountIn(vs ...int) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldIn(FieldOpenPositionsCount, vs...))
}

// OpenPositionsCountNotIn applies the NotIn predicate on the "open_positions_count" field.
func OpenPositionsCountNotIn(vs ...int) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldNotIn(FieldOpenPositionsCount, vs...))
}

// OpenPositionsCountGT applies the GT predicate on the "open_positions_count" field.
func OpenPositionsCountGT(v int) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldGT(FieldOpenPositionsCount, v))
}

// OpenPositionsCountGTE applies the GTE predicate on the "open_positions_count" field.
func OpenPositionsCountGTE(v int) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldGTE(FieldOpenPositionsCount, v))
}

// OpenPositionsCountLT applies the LT predicate on the "open_positions_count" field.
func OpenPositionsCountLT(v int) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldLT(FieldOpenPositionsCount, v))
}

// OpenPositionsCountLTE applies the LTE predicate on the "open_positions_count" field.
func OpenPositionsCountLTE(v int) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldLTE(FieldOpenPositionsCount, v))
}

// TimestampEQ applies the EQ predicate on the "timestamp" field.
func TimestampEQ(v time.Time) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldEQ(FieldTimestamp, v))
}

// TimestampNEQ applies the NEQ predicate on the "timestamp" field.
func TimestampNEQ(v time.Time) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldNEQ(FieldTimestamp, v))
}

// TimestampIn applies the In predicate on the "timestamp" field.
func TimestampIn(vs ...time.Time) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldIn(FieldTimestamp, vs...))
}

// TimestampNotIn applies the NotIn predicate on the "timestamp" field.
func TimestampNotIn(vs ...time.Time) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldNotIn(FieldTimestamp, vs...))
}

// TimestampGT applies the GT predicate on the "timestamp" field.
func TimestampGT(v time.Time) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldGT(FieldTimestamp, v))
}

// TimestampGTE applies the GTE predicate on the "timestamp" field.
func TimestampGTE(v time.Time) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldGTE(FieldTimestamp, v))
}

// TimestampLT applies the LT predicate on the "timestamp" field.
func TimestampLT(v time.Time) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldLT(FieldTimestamp, v))
}

// TimestampLTE applies the LTE predicate on the "timestamp" field.
func TimestampLTE(v time.Time) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.FieldLTE(FieldTimestamp, v))
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.TestnetAccount) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TestnetAccountSnapshot) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TestnetAccountSnapshot) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TestnetAccountSnapshot) predicate.TestnetAccountSnapshot {
	return predicate.TestnetAccountSnapshot(sql.NotPredicates(p))
}
