// Code generated by ent, DO NOT EDIT.

package latestprice

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/chuyen-gia-crypto/backend/internal/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldLTE(FieldID, id))
}

// Coin applies equality check predicate on the "coin" field. It's identical to CoinEQ.
func Coin(v string) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldEQ(FieldCoin, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldEQ(FieldPrice, v))
}

// Change24h applies equality check predicate on the "change_24h" field. It's identical to Change24hEQ.
func Change24h(v float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldEQ(FieldChange24h, v))
}

// Change7d applies equality check predicate on the "change_7d" field. It's identical to Change7dEQ.
func Change7d(v float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldEQ(FieldChange7d, v))
}

// MarketCap applies equality check predicate on the "market_cap" field. It's identical to MarketCapEQ.
func MarketCap(v float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldEQ(FieldMarketCap, v))
}

// Volume24h applies equality check predicate on the "volume_24h" field. It's identical to Volume24hEQ.
func Volume24h(v float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldEQ(FieldVolume24h, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldEQ(FieldUpdatedAt, v))
}

// CoinEQ applies the EQ predicate on the "coin" field.
func CoinEQ(v string) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldEQ(FieldCoin, v))
}

// CoinNEQ applies the NEQ predicate on the "coin" field.
func CoinNEQ(v string) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldNEQ(FieldCoin, v))
}

// CoinIn applies the In predicate on the "coin" field.
func CoinIn(vs ...string) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldIn(FieldCoin, vs...))
}

// CoinNotIn applies the NotIn predicate on the "coin" field.
func CoinNotIn(vs ...string) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldNotIn(FieldCoin, vs...))
}

// CoinGT applies the GT predicate on the "coin" field.
func CoinGT(v string) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldGT(FieldCoin, v))
}

// CoinGTE applies the GTE predicate on the "coin" field.
func CoinGTE(v string) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldGTE(FieldCoin, v))
}

// CoinLT applies the LT predicate on the "coin" field.
func CoinLT(v string) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldLT(FieldCoin, v))
}

// CoinLTE applies the LTE predicate on the "coin" field.
func CoinLTE(v string) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldLTE(FieldCoin, v))
}

// CoinContains applies the Contains predicate on the "coin" field.
func CoinContains(v string) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldContains(FieldCoin, v))
}

// CoinHasPrefix applies the HasPrefix predicate on the "coin" field.
func CoinHasPrefix(v string) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldHasPrefix(FieldCoin, v))
}

// CoinHasSuffix applies the HasSuffix predicate on the "coin" field.
func CoinHasSuffix(v string) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldHasSuffix(FieldCoin, v))
}

// CoinEqualFold applies the EqualFold predicate on the "coin" field.
func CoinEqualFold(v string) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldEqualFold(FieldCoin, v))
}

// CoinContainsFold applies the ContainsFold predicate on the "coin" field.
func CoinContainsFold(v string) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldContainsFold(FieldCoin, v))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldLTE(FieldPrice, v))
}

// Change24hEQ applies the EQ predicate on the "change_24h" field.
func Change24hEQ(v float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldEQ(FieldChange24h, v))
}

// Change24hNEQ applies the NEQ predicate on the "change_24h" field.
func Change24hNEQ(v float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldNEQ(FieldChange24h, v))
}

// Change24hIn applies the In predicate on the "change_24h" field.
func Change24hIn(vs ...float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldIn(FieldChange24h, vs...))
}

// Change24hNotIn applies the NotIn predicate on the "change_24h" field.
func Change24hNotIn(vs ...float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldNotIn(FieldChange24h, vs...))
}

// Change24hGT applies the GT predicate on the "change_24h" field.
func Change24hGT(v float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldGT(FieldChange24h, v))
}

// Change24hGTE applies the GTE predicate on the "change_24h" field.
func Change24hGTE(v float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldGTE(FieldChange24h, v))
}

// Change24hLT applies the LT predicate on the "change_24h" field.
func Change24hLT(v float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldLT(FieldChange24h, v))
}

// Change24hLTE applies the LTE predicate on the "change_24h" field.
func Change24hLTE(v float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldLTE(FieldChange24h, v))
}

// Change24hIsNil applies the IsNil predicate on the "change_24h" field.
func Change24hIsNil() predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldIsNull(FieldChange24h))
}

// Change24hNotNil applies the NotNil predicate on the "change_24h" field.
func Change24hNotNil() predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldNotNull(FieldChange24h))
}

// Change7dEQ applies the EQ predicate on the "change_7d" field.
func Change7dEQ(v float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldEQ(FieldChange7d, v))
}

// Change7dNEQ applies the NEQ predicate on the "change_7d" field.
func Change7dNEQ(v float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldNEQ(FieldChange7d, v))
}

// Change7dIn applies the In predicate on the "change_7d" field.
func Change7dIn(vs ...float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldIn(FieldChange7d, vs...))
}

// Change7dNotIn applies the NotIn predicate on the "change_7d" field.
func Change7dNotIn(vs ...float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldNotIn(FieldChange7d, vs...))
}

// Change7dGT applies the GT predicate on the "change_7d" field.
func Change7dGT(v float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldGT(FieldChange7d, v))
}

// Change7dGTE applies the GTE predicate on the "change_7d" field.
func Change7dGTE(v float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldGTE(FieldChange7d, v))
}

// Change7dLT applies the LT predicate on the "change_7d" field.
func Change7dLT(v float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldLT(FieldChange7d, v))
}

// Change7dLTE applies the LTE predicate on the "change_7d" field.
func Change7dLTE(v float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldLTE(FieldChange7d, v))
}

// Change7dIsNil applies the IsNil predicate on the "change_7d" field.
func Change7dIsNil() predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldIsNull(FieldChange7d))
}

// Change7dNotNil applies the NotNil predicate on the "change_7d" field.
func Change7dNotNil() predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldNotNull(FieldChange7d))
}

// MarketCapEQ applies the EQ predicate on the "market_cap" field.
func MarketCapEQ(v float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldEQ(FieldMarketCap, v))
}

// MarketCapNEQ applies the NEQ predicate on the "market_cap" field.
func MarketCapNEQ(v float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldNEQ(FieldMarketCap, v))
}

// MarketCapIn applies the In predicate on the "market_cap" field.
func MarketCapIn(vs ...float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldIn(FieldMarketCap, vs...))
}

// MarketCapNotIn applies the NotIn predicate on the "market_cap" field.
func MarketCapNotIn(vs ...float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldNotIn(FieldMarketCap, vs...))
}

// MarketCapGT applies the GT predicate on the "market_cap" field.
func MarketCapGT(v float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldGT(FieldMarketCap, v))
}

// MarketCapGTE applies the GTE predicate on the "market_cap" field.
func MarketCapGTE(v float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldGTE(FieldMarketCap, v))
}

// MarketCapLT applies the LT predicate on the "market_cap" field.
func MarketCapLT(v float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldLT(FieldMarketCap, v))
}

// MarketCapLTE applies the LTE predicate on the "market_cap" field.
func MarketCapLTE(v float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldLTE(FieldMarketCap, v))
}

// MarketCapIsNil applies the IsNil predicate on the "market_cap" field.
func MarketCapIsNil() predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldIsNull(FieldMarketCap))
}

// MarketCapNotNil applies the NotNil predicate on the "market_cap" field.
func MarketCapNotNil() predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldNotNull(FieldMarketCap))
}

// Volume24hEQ applies the EQ predicate on the "volume_24h" field.
func Volume24hEQ(v float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldEQ(FieldVolume24h, v))
}

// Volume24hNEQ applies the NEQ predicate on the "volume_24h" field.
func Volume24hNEQ(v float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldNEQ(FieldVolume24h, v))
}

// Volume24hIn applies the In predicate on the "volume_24h" field.
func Volume24hIn(vs ...float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldIn(FieldVolume24h, vs...))
}

// Volume24hNotIn applies the NotIn predicate on the "volume_24h" field.
func Volume24hNotIn(vs ...float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldNotIn(FieldVolume24h, vs...))
}

// Volume24hGT applies the GT predicate on the "volume_24h" field.
func Volume24hGT(v float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldGT(FieldVolume24h, v))
}

// Volume24hGTE applies the GTE predicate on the "volume_24h" field.
func Volume24hGTE(v float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldGTE(FieldVolume24h, v))
}

// Volume24hLT applies the LT predicate on the "volume_24h" field.
func Volume24hLT(v float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldLT(FieldVolume24h, v))
}

// Volume24hLTE applies the LTE predicate on the "volume_24h" field.
func Volume24hLTE(v float64) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldLTE(FieldVolume24h, v))
}

// Volume24hIsNil applies the IsNil predicate on the "volume_24h" field.
func Volume24hIsNil() predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldIsNull(FieldVolume24h))
}

// Volume24hNotNil applies the NotNil predicate on the "volume_24h" field.
func Volume24hNotNil() predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldNotNull(FieldVolume24h))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.LatestPrice {
	return predicate.LatestPrice(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LatestPrice) predicate.LatestPrice {
	return predicate.LatestPrice(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LatestPrice) predicate.LatestPrice {
	return predicate.LatestPrice(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LatestPrice) predicate.LatestPrice {
	return predicate.LatestPrice(sql.NotPredicates(p))
}
